---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: terraria-playit-secret
  namespace: terraria
spec:
  encryptedData:
    SECRET_KEY: AgBMKWjIKu9B0s5e+g+oR0boq3uRAMPy6UJ0YndScMYfeXCy0jHJ4JsiUV2qdsuocPsrYphzYPtTqmAL/E5+7pK3ewBrUnP8ZUAZnLFZh1oKjb6PZbzSrM1qAGf9ryQxltgzJe4Gz7pUzhwb/z/1VcINANL95kp4E6lrZWJVtwkpGa6nLQty2C7qicPSdQLd4RyyFQwEXObLwj+G6SmrkXLabGyYifFf1vLWMUNUD/Tt9D05iIGeTDXe1QXSm/JvL1ooCvpHVLuQOI7IeqaGFMmqRuRDlHJpp6ss1Ur/cMVr/nhOHx31zNOsgYsipBXZe/UsCIYrvTRxP3mjpP5y3P9B1wHHWLskikec3hkJsMTYCDqriDDfuGsLtTc+CZYg6hzzV0wdicfBxrj6/adFhUWh8WWH0YH9U4znljXiJJHQTMCczSWZnkV6tfWLYw0z4XvyQvQU2AQ07h4wmhKyoP0tdFNGqWmJ+7I3J0hnDIsYV1DlsiIFtQJ7iSprNygsszMfNch/Aj3uU/5tn4tDCf2/Y+3uY6qBasZna1EecgYBqa5VNbWAPuJ9OVFHig2+/b0gRM8dCo8Utu3ipot5fi99AEcK8+IlZZ9ek2N+POxHL/xzjBZYP/kny9LlFwGIpcLwn8GFBCIRDFRElmlYJO61WOYdV+iHXdtsaHzqfFSIz1ckREqNjT68kNWtvsQVeSyeyTmLPwtB0tVJLWYoLKKma090LNegr8JrTjvw71PZSmtebsktAxp+mqrsN8uMKzZZd/Uq4ESbrjphhKohgUY2
  template:
    metadata:
      name: terraria-playit-secret
      namespace: terraria
