apiVersion: v1
kind: ConfigMap
metadata:
  name: site-config
data:
  site: md
  namespace: md
  host: md.waylonwalker.com
  webrootPath: /mnt/main/walkershare/waylon/sites/md.waylonwalker.com
  TELEMETRY_ENABLED: "disabled"
  TELEMETRY_APP_NAME: "md"
  TELEMETRY_ENVIRONMENT: "production"
  TELEMETRY_VERSION: "unknown"
