apiVersion: v1
kind: ConfigMap
metadata:
  name: site-config
data:
  site: gears
  namespace: gears
  host: gears.waylonwalker.com
  webrootPath: /mnt/main/walkershare/waylon/sites/gears.waylonwalker.com
