---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dropper-secret
  namespace: shot
spec:
  encryptedData:
    ACCESS_KEY: AgCJf8VwOWOL49uDK8jDL1pxolmwJNuW4rhyy/LUZYK/+LWF7dmjppjLuBQ2tQ86jnvlkc6dHRABH1EO0vf2rf0SSIik6u8Ys7am12WLsKKI21XmjfEBNmVjGkM2I8SUeKhxh8txtJRuDWZMTV+vsElFSChQtfmRpEWbpwq98Ctzty+5qEWks+xpTiSsRkgXP0BPuZIIVpAvt5Fs+NPYQonM5lLbw9kPvarsFHHHbMkeGNLIl3RAmjDh7aWSTFzE/TJbjmTRgquMWtGS1o9y8LaeQReFAuyQL68u+qrhCtsp+DalHjaMvEYiq5woJisK7bOyvn2UQxrlZVpsEGHfhlccLdKRGG93pcCIkTUCCnaVB988JydADdQQFH/ajoS2Gf07wZQUoQIZ8XEVMvKgWEB/q6hJ316bLJPL/aypR7wV8JMiqjyoYJivbK3f/m8OqKO+WOce3NfLfVjyfZmy4SL2QR7K0biV3Ow3M9Ml/H4kEcBJQ/0ahIyH/kZn7mGfb42hPV9P6kjW/BmxRzOITmFi0MNIJRAUiaVr3eYabIEjp0z6vtb+UM96acjZi28EaCeQIq8GaxbRhNY4VBg1gj0RKfl6PG2DHjjvhRUL7hg338sz7+KRZJxEOo/ijXu56AfBImIP+zihkxyNEwVK8UqBZWGa7Dg15m4b28ykBjMs4nyHESS1lS61W3yLak10vLgI9QG52IBfirQycHHLQFk0Ty1RvbU=
    SECRET_KEY: AgBB24tJ5Usht2XNo+FHSsGd0391NmjOKuhs1Gnff0jjXZqNueBbDyXJdLzJCbQesn4/4oJPwltxTu7Sg9kJNZq/6B9VFqwqMLIyClXRRspvVbVQmqfdrE/DQdstV6HU3S+nKHhYV1wTpJDdjw//eGW1/QqIqLhdqtnUYBhjFEHZKuCaTVRPZjMigpQU2IGkdo0NTMyydm/rQPzHHQn0esSOiySTAcS0BX6yHRfvZtNljRWfDsSNgeX+hHKX9i4RlG5piH9lfRpAMuzKAyMH5dyC5aTOH7clgHSS8S44rT+PJGOuhu6mkXKwXq3taqKH6j4pOXWk+yNrh//4otIFnVkT2CIwMiI38MHkC8mo5r7P2JFJjOKvCE4AHD3Xzc409ISOMbVSPAN8NwIgSsQO7zMW6BWuGONmUqq1Iuebr0ftWn9Keb/TBhK7H9RmT+7oPK7RlJrEfjAV/vjGl3XVmfgQsADC3oThXRO6h9SKy7TJ0r7CfdOh4gbHen3JuDD6lnTCyh8+3dJIR++MIfbU4lvUAVIguqy8iaVTCkoOMNqmJnLl+BSGTRDMkraoxTX36UTRoi9WxEYxzR8M2Xyd724JRWF5g5kIFBIPOhR/Xs0b4UlrKWw60miVpLCIgWs6V8bwwYo3/1FBpj+lZ2Z6qI03Pl85o4U06vZBqRIrehNJ2dAbu3i9i4K4FN2ytBUF30Ro4Vs75xqvOetdTLI2411oYA9wtLlnFjsIyAxgY+ZhAabDWynseiJ/kw==
  template:
    metadata:
      creationTimestamp: null
      name: dropper-secret
      namespace: shot
