version: '2'
services:
  kanboard:
    image: kanboard/kanboard:latest
    ports:
      - 80
      - 443
    volumes:
      - kanboard_data:/var/www/app/data
      - kanboard_plugins:/var/www/app/plugins
      - kanboard_ssl:/etc/nginx/ssl
    environment:
      - TZ=UTC
    labels:
      kompose.service.expose: kanboard.wayl.one
volumes:
  kanboard_data:
  kanboard_plugins:
  kanboard_ssl:
