version: "3.9"
services:
  emqx:
    image: emqx:latest
    container_name: emqx
    volumes:
      - emqx_data:/opt/emqx/data
    ports:
      - 18083
      - 1883
      - 8083
      - 8084
      - 8883
    labels:
      kompose.service.expose: eqmx.wayl.one
volumes:
  emqx_data:
