---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dozzle-auth-secret
  namespace: dozzle
spec:
  encryptedData:
    users.yml: AgBm58jcNxTW/TT0vQtnk23GZj1RllREjY+dguVRUH9InU96vzIa7IGToBFyYEvwOUfesNwTg+1qPwvQnDHLDja+JgI4P3pwWWFXV+gzW9BzUN1JjC9pda8WyQBOUmHAQ02fBLPMGvvLVU8vN0XkTMlNceJhxUwPvr3Gkk4KQZTyT7dDU4vtflpjWFj8XqI2PCln7XqYb1RlQjPeXa/QFOSag3943kKHxMff0xC//xxejF33oxWKcgOXqcrQvzzfDkuEkRmk/cRN4NlO5lb6q68SgsjuRh7nDqaqS81UPhd/TY20NeqnQF7lji1JsFee1ySeXxOp7Ar2Zl04HOe8oqIH5sYQIHilFFCzoVJ2xBnaREMOeIWCQmBnGAhBLkOhdAE7Pj4MnAX+8Jw5UHCPzUtXof37IxrftHKmJSPXfZ7PydIf0LQJ1i62bhXjXV67sCM2ntljJvVQFyirK1izSSkWkKQee/pfPE5AwNy9QEt6ai+c8V6wPbjEnT8x65CFeRKUkwd0Zyv4ZxO5y9/HjMyDJFTsJRmccWAAYt3MJN1fkJ346Pl5je11cu/WB/LN/aknNg4nOX6uJJOJXHE91rKtPiNH+KAWxeJeUMjuwSHJTFLYuwH9m+dWvxu5lrPFsrx3+F3laK33HZqhXbdSbM3cf+QixJv1WcyAYqYqMlfYnvMMI8tcIZ2KKYAbUz3KA4CxA7hW75M/AeR/MFpKC8w4plT2NLzu7QstlnDUG5hzgsQLxi66H/dpY2tawkKix411qGr/JXAg1wLSkKUWdh57n1jN/BuWuwJWXphNZZj3E7o0ur49/AK4ZMKsd66+1FmSnXCwPuymRFe+zA==
  template:
    metadata:
      name: dozzle-auth-secret
      namespace: dozzle
