---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dozzle-auth-secret
  namespace: dozzle
spec:
  encryptedData:
    users.yml: AgA3sZi7odYtD9cl8fHcbhGu8nmDjNnXG3Nygwcx6/JOt1qAWM0jPpB7MeKl8n7H1I1klKTXPz5X5ivImL2iMa11gn0w9BA+WMh6M6I0JOA4js4/52NAWWVUPmZ7ZDLsfzQ4q6LHKV4gvl1c2/ce2iTgjexXPxk+5LJHppBT4AWYqtJ6dAn3l3nFv7LK6hj4ABk2Nh9xAWXFnC5MfiAQjPE3gRnG0YOtNhA67Y+Q7C1d4T2q64XQXDwgkqRTQsnNwGsY5/O/d7L3wP5jsnLJg8OGiiXDnl6cz4kL4jjBvxh8FTjSb4uv1FeJGWmZJEQ+uT8ax8dwgoelgJtjmXy7w8kgmcKswcvUm1qI+/Jz8TOFPLb5lycySzcK3WoeBdn63zAnf89k0R4Hpbg2cZk6qtYFXL6dzTuE6GOLf7mK4nQpnBpR72Wt9ZVvZV7aqMN6v1B4k7FDjG+XBF9D2Qoeq+m/mbFF4qjPDBD+xCfiWUzQ6bjxs5g98M2/zIrdwHVoUjOcPkG1wMZt8QUsP4J/pA4X65nE4yvEKg8hrcdQ4R06zYU6LeQjYqK9jNVmfZpEqmGJd0OlWdff3qL3Ar7M4fYgE4Eo2ehKJIDbOa6SMUt84cZWdXalwsww3sudk7W/2CWQ7VGfATsd7LcFa3TIi0wXYAzfIKZFNWJafumteV/tcrzR2AfqW9s4ckjlwm1x7WOgzqRoYN/tL/t6DgMxEX4kA12WOM6FLj8O8cu8WSGuzIhYlFvuiVF/UPWLXBRnhjVP6ghVV+02JuF0cjuOoNpOM=
  template:
    metadata:
      name: dozzle-auth-secret
      namespace: dozzle
