---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dozzle-basic-auth-secret
  namespace: dozzle
spec:
  encryptedData:
    users: AgAlHaPaTOoJbCNWTq+QOytIcG/mF8mDKAl5UkL/DeDdNoDarH8/cr3UmFQ4zdwMEcccs9uClnuMP2q5uVa1mcLToQpFaBU+99WrMu8V27SuIbERNx09Nm79iApkMUwVyso4pR7tQxjBCbg2ize7GBEDODonm0o1tZWgwvqsaDd+L2q9p4KakiLZm4DLnEP5w4xqTLfn5bEIDGiIJnmXW9OnMOP3VId82c7SfnmVp7FeyVXxD1UNJ87rtZasBuWOyZ0Oo1AbyZPddwyDsmK6NKjUedhZ3jfc7nn9U4Q1U85+0R7YH95CRhRE/506ZpmE7Ize3jyGerW6BFI7KXAqfSIYgpI45aXCNAM4KwGj4MRz4vDzFm22oPrAFeudFeVNjjDzh3pBG4ZoSIWJ58oVZn6agjQK4QoDmaYUhBchCL9MGLpquuCk+fjtXHQzoTlne7CFjolzfdf+kHDgvTvwimaIlF9zWs10kLItkFlxjchOOd+yODawEcwWsl7/ihhY7fsQPtmHmeZQEOhc1FjQjYm+75+k88FJPXLfyyhzV52QyItTAvuSkNbOxwWwNtvNdv/ls3bscKhOkqlZW7TGkcurAQlSUe07l58fWRfnC/YYb/aGbx41Ei0Vb79gvU8n6adQVolf+M9dKOhAK//+pESTc769mlT5AZLq28TRrzvgV3PCmZMKlm+IDDdm/8XKVXFFPyRes6NRZ3+/kwSCsJ3DXNoLGO2TQPVg0OGB9jHjTJbONaM4CSIL5BcVfAuh3eg5LQt5IHzQnZ24STtFu4iiI6Q=
  template:
    metadata:
      name: dozzle-basic-auth-secret
      namespace: dozzle
