repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.9.0
    hooks:
      - id: yamllint
        args: [-c, .yamllint.yaml]
        files: \.(yaml|yml)$

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.9.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/Agilicus/pre-commit-hook-k8svalidate.git
    rev: v0.2.0
    hooks:
      - id: k8svalidate
        args: [--exclude, "**/*.patch.yaml", --exclude, "**/add-*.yaml"]
        files: \.(yaml|yml)$
        exclude: (^|/)(disabled/|.*compose\.ya?ml$|.*values\.ya?ml$|.*-crds\.ya?ml$)
