apiVersion: v1
kind: Pod
metadata:
  name: pvc-inspector
  namespace: minecraft
spec:
  containers:
    - image: docker.io/waylonwalker/devtainer:slim
      name: pvc-inspector
      command: ["sleep", "3600"]
      # env:
      #   - name: FOO
      #     valueFrom:
      #       secretKeyRef:
      #         name: mysecret
      #         key: foo
      volumeMounts:
        - mountPath: /data
          name: minecraft-data
          # - name: sealed-secret
          #   mountPath: /secret
          #   readOnly: true
  volumes:
    - name: minecraft-data
      persistentVolumeClaim:
        claimName: minecraft-data
  # - name: sealed-secret
  #   secret:
  #     secretName: mysecret
