---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: markata-go-encryption
  namespace: rhiannonwalker-com-prod-notes
spec:
  encryptedData:
    MARKATA_GO_ENCRYPTION_KEY_DEFAULT: AgCqLOUzB3JJkn1vk/sMfNnI+6Ez9xFsRi6LYYul8dvLhqZciuOSB0bbBrGkbLQLwnZVe5FT+YpZrr6JSfhACSlorDFe2xCOMPWaqea6lvdKjbNppSVCb9eRDMeAv4xUAsA1xLV6aPHRyMqRQoc3os16NeXFQN29MA3677T1AnB0Yx/dqwSjn3EVEoKxkScf+PSL5m/dobc6yrtjuoJ9SQHVaHKSojn3lbHJQ0eTmyCdNDrdVWZtcWFcjz5aO1f043qHqars4mJZo+LESL1H0jJRMZSfGJFw8BWwonihsiz23UYzoJti1jNkzXiZQ7VVua4MIYJsMYaA4PI63KuLZCH/3xUWY8Q1XkNxNkbmPcdo9rxSnEbP3mdshKnHuvaiaBTn0h8Omd+5F13Kb0I9iLfvNz/6sW5lAyJNsnIjzOJ93I4CFkEJx9KPXndOmF274wSddEy3to3axflmxTY+7WP2ZHIZPaqEg1uxdNoE/y+ZenEuH4ztnm+9dAtfUM9RyuWzADrM81hJTWeSH7nS1VtsyALwIJMzJqco9oHAtb8SzVm4QAkCIAT5SgpgP4BRPE0Q4sZyuErnp7LEji6WVoC6qyXfD0CBoRDpZ7XUXohlM9Xg6JjpZymbCI3mTgi9QJ538M6dfbXXxqHKjANv9n+OBwcGU+7LdsqxggEwFyXZ9/JxDqdz+oedc5LpVwht1b6ds95CYyyTprVqNfUTW3EnXCNcf/k=
  template:
    metadata:
      name: markata-go-encryption
      namespace: rhiannonwalker-com-prod-notes
