---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: markata-go-encryption
  namespace: rhiannonwalker-com-prod-notes
spec:
  encryptedData:
    MARKATA_GO_ENCRYPTION_KEY_DEFAULT: AgAZKs3pQh8lZzEzxlMI83DmyDC3gE6etBoAAvmoR5A6UnrAJbLUBNSHF4GLOo+yAPV1xKV7m2eZL7VL1SV9d5HZzWha1R46q2hb8f/WCJfEe0FDuKzL13CGTAAH/HBU8JYPmO8/Gk6+OzpTxbPVYrXwjvjlJEgNaH7qEmlV784FE4CyoiaopwtOfHUKWra1dckepFODiDZIj26wveD7fpJDAr/hGj5Xg8XmEvXczdLOLjSMABb4I1K55bnDOnbWJqyjjAKPc3TIzpmcF7I15dI4KSrB9MnYcFtVwKfLFFyUFIhow02oWxHfq3gY+ZsS0OjIJme6+xaoaq6qxt2llDK/SwQ7MBxVGj0KL7DYYzI6WiIRccpDuSgOeVNuSioYuZPJ4dGwRCsKkZ9N6UjcmvSA5+kt01NSu+WV0VS8US8kv2f26ztNCQMZdcNYqu7P8QTYBXS82SJ5FuAm2u+5BGmpCfSSEonZUJKE+4fhFfk07b8ZEQk20OGWGk0Gb2Zj71b1UDhmwKG/ubjEnn8LdytcVa8TF87u8lmwd5dH4PmQWdofWf2D2acC0yPzm4kEOTSw+U0bEDi1JAwJG7jL532xoJ444MtAqgIGGIn/sO7/H/nwSBl4KquJGGhXqDXsMDwpBG7H3h5QsqDYeGDBsCsbydYI7H0xHzb3hZppbF+2bigAXazG7CXRw7JUy1LjndCJmC1DDRU+azWDIeNHazCxBMaz7LXEcK8orJo1f1Doj48Ujbcvg8SbM9CnRNGiD+ooyJpdBvQkC5d9CboB0q3P
  template:
    metadata:
      name: markata-go-encryption
      namespace: rhiannonwalker-com-prod-notes
