apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o deployment.yaml -n wayl-one
    kompose.image-pull-secret: regcred
    kompose.service.expose: www.wayl.one
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: wayl-one
  name: wayl-one
  namespace: wayl-one
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: wayl-one
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: wayl-one
  namespace: wayl-one
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o deployment.yaml -n wayl-one
    kompose.image-pull-secret: regcred
    kompose.service.expose: www.wayl.one
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: wayl-one
  name: wayl-one
  namespace: wayl-one
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: wayl-one
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o deployment.yaml -n wayl-one
        kompose.image-pull-secret: regcred
        kompose.service.expose: www.wayl.one
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/home-default: "true"
        io.kompose.service: wayl-one
    spec:
      containers:
        - image: docker.io/waylonwalker/wayl-one:v2
          name: wayl-one
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
      # imagePullSecrets:
      #   - name: regcred
      restartPolicy: Always
status: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: wayl-one
  name: wayl-one
  namespace: wayl-one
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: www.wayl.one
      http:
        paths:
          - backend:
              service:
                name: wayl-one
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        # forwarded by dns
        # - www.wayl.one
        - wayl.one
      secretName: www-wayl-one-cert-tls
