apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: brainrot
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.host | quote }}
    {{- if .Values.ingress.auth.enabled }}
    traefik.ingress.kubernetes.io/router.middlewares: brainrot-brainrot-strip-hlab@kubernetescrd
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  tls:
    - hosts: [{{ .Values.ingress.host | quote }}]
      secretName: brainrot-cert-tls
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: brainrot
                port: {name: http}
