---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: example-pg-cluster-secret
  namespace: example-pg
spec:
  encryptedData:
    ACCESS_KEY_ID: AgA2PpMsmy3W5wkvap77byFc35q3Rua6/av9GoM3EyR1/XqAvYvjYRoeAp2utFyxeAYql7Z86yoXL5hEjnqIBHX8lTmeNcenXl2pQxcs1mqtrwr0xfosirKt2Hbmq8T5wX0QjVRZRsm202OEjhJWaOZCxgzQ5mByBFjtic7kwTXbvdMBkwws4SAhRWNU73n4W1kfCRiAc/R6zMYVyYPO4GKHa3uLVWTUN1VvUqSShcbLHwHMxCSmZgXVP3yylcr65a2tBi5iZtTSctWVcR3QJr+x0+OFJR6yhfmtds9+8oP4nwfK4/9WI5V7gGxaLOcEpTtpFf9s0iXyJofUmB76yr7V+F9vMBf9sexGx15sGOWaEGdgU9th/BEkdC8gGBkqOQcNuuY0TQoUCiksr+ABV7lwPaxfK55eraTlbX4APXeWc6F7kNdUQTWbBnKY0lSPL6B0I9dMb6Qd3KbqgurjEpKuzVEWmXla3pxL8lY0iVL6U3ost/Ji8VNe8eUN23AujtUTwCc99pPf39cjpoZE6mrE1LOEHOTVvfw0qlWnvOd167M9udx7L1pMusTnK7wlXwLheZ02p0ZiovLjKVyOPjivDInAGlw9lt72LsayopI8Hp9IjnKBNVNzN15rDys7O2eYJXVeLZ2XEbcbHqBrptJDdl9bIzybN+T58FVjOjN7dJ27bbP604Nr1YrA33GhIaOdbIAY/qvs0/uqeoFRdIq/NApLHdc=
    ACCESS_SECRET_KEY: AgCSRXVsJ9UoRih47a6U3Kq9Cm0etm+SSDWkmnPDgw6oovWcLtfJdzK6faxB1yw72SGYmt5SuopbXPNabb1syT3gcTQxA1YXgtSDk+iqOg+1V1t6VpRcU7DbSZ01rwEazapflef+QNSMQD/0rGwNsqRQWuswRd8aeND7wd6qjZ8sbMGZK92JJ4Mm1mLqgVpxgPQ201XV4PfwzUsxYL+0NVrnx7YM5FTJbBW5+3I1Lz/IOaO66D5thE3NARyRLsD9+yoTb+hjptn4N7yO2bhSVlRg8W+FoA3sysiW5KpaMdUhB5wLmTJjkZnlcM/EhUa/3F+dk5Dk0LFOo2+PnKnNqUXxa1EIj43rzmcD4R65vidn9qtOv2c7PAlptNhZPNU5exgax3aNACJ5L03Fs912Y4U1nErTu1MN96I5vZQ13V4vZuhq+XaTV2yanQwgjt/IzShPErmpOqSu33cZldYw39JqkU18dKZN/v2op0pjtwgSfmb0wJcMiiLj4loNQ4dYAdGldkaIa98dgfd4q0PqIQACuPI4zgu8lL5NwUrB7JWaVRCnSqXVj1x+iM2JFtOqqNblUmKuM5id4lQskUJNPadIF2XpzFCpl24B+jjCd2Xy3v4qmcZXhwvHmXGOFmhOioBWfqWwQ0nekDameLEkWXddokYriqWgzRRFrbSPyienoVOn0N3WIxEXNLglPKAF8K3CvnMmPv28zRS1QfGx+NCKXwmuqtA/LIm4LGo/0G0eJc4EB3sSnrOEIg==
  template:
    metadata:
      creationTimestamp: null
      name: example-pg-cluster-secret
      namespace: example-pg
    type: Opaque
