apiVersion: v1
kind: ConfigMap
metadata:
  name: site-config
data:
  site: go.wyattbubbylee.com
  namespace: go-wyattbubbylee-com
  host: go.wyattbubbylee.com
  webrootPath: /mnt/main/walkershare/wyatt/sites/go.wyattbubbylee.com
