apiVersion: v1
kind: Namespace
metadata:
  name: photoprism
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-photoprism-storage
  namespace: photoprism
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /mnt/main/walkershare/photoprism/storage
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: nextcloud-storage
              operator: In
              values:
                - "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-storage
  namespace: photoprism
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  volumeName: pv-photoprism-storage
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: Service
metadata:
  name: photoprism
  namespace: photoprism
spec:
  ports:
    - port: 2342
      targetPort: 2342
      protocol: TCP
      name: http
  selector:
    app: photoprism
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: photoprism
  namespace: photoprism
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photoprism
  template:
    metadata:
      labels:
        app: photoprism
      annotations:
        diun.enable: "true"
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      nodeSelector:
        nextcloud-storage: "true"
      containers:
        - name: photoprism
          image: photoprism/photoprism:latest
          ports:
            - containerPort: 2342
          env:
            - name: PHOTOPRISM_ORIGINALS_LIMIT
              value: "10000"
            - name: PHOTOPRISM_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: photoprism-secret
                  key: username
            - name: PHOTOPRISM_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: photoprism-secret
                  key: password
            - name: PHOTOPRISM_AUTH_MODE
              value: "password"
            - name: PHOTOPRISM_SITE_URL
              value: "https://photoprism.wayl.one"
            - name: PHOTOPRISM_DISABLE_TLS
              value: "true"
            - name: PHOTOPRISM_DEFAULT_TLS
              value: "false"
            - name: PHOTOPRISM_DATABASE_DRIVER
              value: sqlite
            # - name: PHOTOPRISM_DATABASE_DRIVER
            #   value: "mysql"
            # - name: PHOTOPRISM_DATABASE_SERVER
            #   value: "photoprism-db-rw.photoprism.svc"
            # - name: PHOTOPRISM_DATABASE_NAME
            #   value: "photoprism"
            # - name: PHOTOPRISM_DATABASE_USER
            #   valueFrom:
            #     secretKeyRef:
            #       name: photoprism-db-secret
            #       key: username
            # - name: PHOTOPRISM_DATABASE_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: photoprism-db-secret
            #       key: password
            - name: PHOTOPRISM_SITE_CAPTION
              value: "AI-Powered Photos App"
            - name: PHOTOPRISM_HTTP_COMPRESSION
              value: "gzip"
            - name: PHOTOPRISM_LOG_LEVEL
              value: "info"
            - name: PHOTOPRISM_BACKUP_DATABASE
              value: "true"
            - name: PHOTOPRISM_BACKUP_ALBUMS
              value: "true"
            - name: PHOTOPRISM_SIDECAR_YAML
              value: "true"
          volumeMounts:
            - name: parents
              mountPath: /photoprism/originals/parents
              readOnly: true
            - name: waylon
              mountPath: /photoprism/originals/waylon
              readOnly: true
            - name: rhiannon
              mountPath: /photoprism/originals/rhiannon
              readOnly: true
            - name: storage
              mountPath: /photoprism/storage
          workingDir: /photoprism
          securityContext:
            seccompProfile:
              type: Unconfined
            allowPrivilegeEscalation: false
      volumes:
        - name: parents
          hostPath:
            path: /mnt/main/walkershare/parents/photos
            type: Directory
        - name: waylon
          hostPath:
            path: /mnt/main/walkershare/waylon/photos
            type: Directory
        - name: rhiannon
          hostPath:
            path: /mnt/main/walkershare/rhiannon/photos
            type: Directory
        - name: storage
          persistentVolumeClaim:
            claimName: photoprism-storage
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: photoprism
  namespace: photoprism
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: photoprism.wayl.one
      http:
        paths:
          - backend:
              service:
                name: photoprism
                port:
                  number: 2342
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - photoprism.wayl.one
      secretName: photoprism-cert-tls
status:
  loadBalancer: {}
