---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-extra-secret
  namespace: nextcloud
spec:
  encryptedData:
    db-password: AgBoeVnQZ6H0i4zRpNEmxxNVEuvwiANe+2mHx9PuuPkRjX55DlhMVUWRHPEWahdZXGTp90ibID4CevlRbd46+t3j1na3k/xQ5FZeFmyM4lXm8UwbTXiAmlQF+4OUHsZITX3NZHOjUkVkaR3Z60QUk9uNyquw8saN6SklTvz6EW1DAsULS18e/bYQ+GTX2r0zpNNZz+UbBVrS/WGdFrQStBklpJ65Qlg2EVphpHY2Ikbf9pphTsByM0J2vFIcSLv9M3YaB9A0ABCTlMAX1hRfkLo1zPJkqzUx7LdMH+cvNLziMpv6ITJdXIzCRWFjzHnFech735f8Zb94BlVRKujBwx0i0XqWtAtTDTDXaxz7tSzlStlIQdx/yHvaC7cvfumZdy75kN7knfsOOzjxWk1Az8X3CMulfzIVXoi12cjFyB8x1Jn4OEYFjRA1pEYKFl5gkjFrlHaSSjmh+2SRcZ6hwIwlQNDI5yOyqb+HDOAId5+9aJLuhh+g9PyimOzWbuzq9Q+cwfpXhf/8B4Nl0PY13OiEmCMFosTdORWdE4xi59pe1tz8aT1htja7si6OOBXcNCLWhI6vj8SHC1d9qj1Wy6ajnFbt4C8LNACuNZB3I2wdG1/r8lQAM9gzLtDAdJh3Z5BA30KnKWVXKVz5qmtXQh2Pixj2E7ZHVf6FaeCoXIulGtAVOhcbl7o2dvCSV/oA41/8QHn0HpwpuSVNfgVN0Et0ffqsIwuBe8pDUSi70iW5m3z9c/xh7xojarWpcu61q+KN7tZq+ly0eXp2Zpt7tIxB
    db-user: AgB2P1B1PUcx1j153aC8pE2DJVW9mRtTgEdxGYVtRVCOyApX+xMKmKDA2gPIcJZh93ZKk6VsCBZT5XuE5Oqacbu30cENxa/BzHteN+WQh4z6Ox6hYo/B6M7Rczd4g2tB04eqZpx6yLERm0vCTPdEICcI1b6AFskjQZfuOtyaW9m/RQC5KFU+up4l+tolN8a4qj1Od9lTRk+t9F1Ho+nEufZLJ5wWzJ/ixqh2Wgj9oJIY8YaicseonlW9Km2Fay/v9hEuEFJ+rBMyH8ZkJqKx3e7nOe4AkmIWH92Shy2AcBciZeN858vrh4WYl15rgd05XL1QcErOzqbgC8fMZnygQ+YuIziPLksFn+bXfSXj/tnuC/luTpxr4B2CGYMw0Hd88QXKTOMH1bnqvZfnUjqVbATQsfmJFflM8ukm/OPARGML01OuLrQpIhlyszu9gBDhfgYvNd3AHLFg91ZAXlbvf2fLBtla4yR8IVT44tgIkaLtFLGgLc7MiF6dtYyYS9IbPT+BR7+sD4yimBvQHuyeSlMxnJDEIYVo/GB+iMzHpuMW02RQVsTqvjWzvi9va6nD/dkmRHMBiOCL8rCRExAd/Fc7qT2jxUO8p1980qQlrZaT35UOsQAKyLAJ6JoGOnNvI/KN0YNGvCMueuyHMl/CgHTu3JU0TjVJ+n7uX2oQTfQSLQf3uz4QRvoJCqf9UCeHiWkNcjFzKV9SxGA=
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-extra-secret
      namespace: nextcloud
