apiVersion: v1
kind: PersistentVolume
metadata:
  name: recipes
  labels:
    app.kubernetes.io/instance: recipes
    app.kubernetes.io/name: webroot
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/main/walkershare/waylon/sites/recipes.waylonwalker.com
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
