apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webroot
  namespace: recipes-waylonwalker-com
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app.kubernetes.io/instance: recipes
      app.kubernetes.io/name: webroot
  storageClassName: ""
  volumeName: recipes
