---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: dropper-dev
spec:
  encryptedData:
    .dockerconfigjson: AgCM1VkxBdEIojl9Lbltk6eFLmQsvG8Tf1DuNceSj3nPkbAfUxobUOJcyAVGHTFUv1UQ33/YASc3CMZ2ZVywZ83v1foWtm/Bo3lWMr83S+77nt3GhvMqSzbyYBTbXVtbkJKFaCsy68iMxD1o7RB4O8kVxBzYoiDnuDn++0ZsGI2zXGMILd4SPUbd5odT9vr0etPI1tcjmiGfLpVphRCzNLXPFrHhnEav0ezNfUfuF0Qx8yZCqVWMI8J3c0PDuZP0VSoGdn4RZdGb3moId6gR7sT4sQDx8FbgfRPmZ3V8LPHUNkAn/gEDgq2DbkX5mkz71OYA5Kf/8QKEKGUvpLFp54uktqrk8anahbn1bstVcVqeC7B/6QTtcrwry6pbOnSniNTYgQJr6bX/czuXRM0FAT5K0d+QlroC0wi8U7RExqKms+NPl1O7iCl89dLk8TI396CW3G8eQ8rEhyek2l9MgwgP1M/+ldNaDTO6P9diWEQtwxwsv/QFiiHLBF6wig5dh00snDNW04gwEaD329n84dDl7uBu1CUggPZrwVOGe5hLY/AClc0RLyHethWSmMKIQK0hjJPWhq3CEU7v2uEikoilGqZaVtqfTdCVyjLOAuv0c0YXx5QVbxOAp9VwE7Qf+/NmdzPrLofs4RMt6hxx6YoTY+5/7mT71zmRTBjATE3bU3eRK58BFXTQ+AIN7gArSFnDuhSi3nrWE40WJNhtL6iaQ3t8Oi1gmLuMvXdyRQvkXMA+ID1w23Rx+peCdTaRYdYqOiviQlJwH2yS1mb9GL0m0saGWcJCsI9AZmjY+cG1BYbo+IwSQ0N5OO+91Z5d14vsh3Ys2htbyg==
  template:
    metadata:
      name: regcred
      namespace: dropper-dev
    type: kubernetes.io/dockerconfigjson
