apiVersion: v1
kind: ConfigMap
metadata:
  name: site-config
data:
  site: strip-dev
  namespace: strip-dev
  host: strip-dev.waylonwalker.com
  webrootPath: /mnt/main/walkershare/waylon/sites/strip-dev.waylonwalker.com
  TELEMETRY_ENABLED: "true"
  TELEMETRY_APP_NAME: "strip"
  TELEMETRY_ENVIRONMENT: "development"
  TELEMETRY_VERSION: "unknown"
