apiVersion: v1
kind: ConfigMap
metadata:
  name: site-config
data:
  site: md-dev
  namespace: md-dev
  host: md-dev.waylonwalker.com
  webrootPath: /mnt/main/walkershare/waylon/sites/md-dev.waylonwalker.com
  TELEMETRY_ENABLED: "false"
  TELEMETRY_APP_NAME: "md"
  TELEMETRY_ENVIRONMENT: "development"
  TELEMETRY_VERSION: "unknown"
