---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: external-dns-cloudflare
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgASBVGTIIbYfd5pYqc7EHNRp4FpB2tOGoSiHxYu5M/qUWIG8K+phsudpzPZuheJ06O5bIX6yUtKRqdW2zr2toaHaKreS0hXHMcmilABGIQ3v2uNBvzTGRaocmFqYpxGkTUrB4YyLJ8xwhBf+9HT/TRca0AusMmeSaRtHk74sDMxJyn643CzUoaiQVnz9XFeINka+Foo0wBJuxYTbbgoRNmcWKj+QJ5AgeAjipvWWlN/JwJ7leuv+3kNtBENimS6j8+psxCOHsTRDwa2uJmVWFzUvo0yfOiEQJdxF2mXC/dlMNeXjEakVP4LaAB8Z6bZFGTVt7imoOud8WsXDsuX4JakI9WqTj+QYHzU94hwnXvILvN0s4dM3XOCRcEVIPfhusGpVfka/VT2kzSLXq4xflSPt4RE+/bzkKSiqL+sGeJV7S9MYnXjTh8nE0in9ekxB6QjPihN1ibHMERyKm0r65P8Zo7zSy9eUhuTq+sOEoryXVSvKV/0sHds47BljJ+ODPUZ1DntCdUC2SU+5f3xh2Ke/336SoKrpAKoiLgf1gkPtj9hu3xD0jkioqp4a7iep+H5bjewMWzyT928PFV4Nkz2L1RRXkQ2svpykmlbU7EnMcpcd7guhD9+on1N0vEBKBqAsUU8H5YG3hPQOmEPpiIhwBfo7RFnx6R+VjGGqFUcExT0veNWVAdyJPs+xSdmYHoJqozOqQwQQdX0MOtpi01eUm6442+ENgI+XZT9g1mn86sNgjKMLkToJc0XdO8psewqAxgjHg==
  template:
    metadata:
      name: external-dns-cloudflare
      namespace: external-dns
