apiVersion: v1
kind: ConfigMap
metadata:
  name: site-config
data:
  site: 3d
  namespace: 3d
  host: 3d.waylonwalker.com
  webrootPath: /mnt/main/walkershare/waylon/sites/3d.waylonwalker.com
  TELEMETRY_ENABLED: "enabled"
  TELEMETRY_APP_NAME: "3d-workshop"
  TELEMETRY_ENVIRONMENT: "production"
  TELEMETRY_VERSION: "unknown"
