apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: markata-go-encryption
  namespace: waylonwalker-com-prod-notes
  labels:
    environment: production
    app.kubernetes.io/environment: production
spec:
  encryptedData:
    MARKATA_GO_ENCRYPTION_KEY_DEFAULT: AgAyxcWSWq3hjpPWM+/YFgdRKk/Y3N+ZPanSbdIumJ8h7UlNv+ag0dsCliAvOLhRS6UUnkn23NkZx9gI/FoCtcKnfpcZIEb3pFnY59Te+uDYkLInW9bBM7hqGKnUIWS1tzAx3FfmabGfvxeKzI4RuSz9otpKR5B/5M6vGD0am4XOxZHDS7qrG3eTzOB7JIa94Y8LSFLX2pzy8V/Te+TcK0f0Q/f4vz5Im5k9JuJLOCjs5tKtH8ugg/UZMfzNIZG1y71RFmplKYWgw4CPQoHoJwEcz0uaW9fw+h4GqaklHtYYUykSvePwod9F91MTIdN6g4rxBeVAq/vzQKNuzB3cerjpEH0nA9ohO6+mfNtwkAKEPwaBGrZKVQCEO9wsi9oxgA4TDVCAOprVL52LP51pxDjofKMKj1PnBHezAmWVZUw7DdbfHJmubMI03U4uXQQPS49OQy7d46JEwQGSlXBncEfyStRY7tAXGY7tGOvFSLsem9iwRbmoAAyBR8xjnQO2RNyy4w5Da+w+5L9G/3xYi8trs7CssgX0NwfXUxuVx0hwxTiIc4EXzhirm4zSevDF5gKadJkPgleLXElZ2wqqWRsm9qR/gw8CP2hT/ZcVEPQDh7RBiVdJQXhvVsD7wYPyu2mZleMG5bZvMEkc2PaEypc3iEo5jo8EfrZ5UXKF/IQJQr8wrwjHr4CbL9dMBXIvQu6haT2bc8ZmkPjK4aikCZ1h+cpkI7kDq4/NPrjEf+3bg/Qt9M35LsMhurYeljKQ4KA9UdRimQ==
  template:
    metadata:
      name: markata-go-encryption
      namespace: waylonwalker-com-prod-notes
    type: Opaque
