apiVersion: v1
kind: Namespace
metadata:
  name: walkershare
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: walkershare-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Ti
  hostPath:
    path: /mnt/main/walkershare
    type: ''
  persistentVolumeReclaimPolicy: Retain
  storageClassName: walkershare
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: walkershare-pvc
  namespace: walkershare
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Ti
  storageClassName: walkershare
