apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - storage.yaml
  - cnpg.yaml
  - deployment.yaml
  - middleware.yaml
  - ingress.yaml
  - networkpolicy.yaml
images:
  - name: registry.wayl.one/models
    newName: registry.wayl.one/models
    newTag: f936776
