apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: build-wyattbubbylee-com-prod-tls
  namespace: wyattbubbylee-com-prod-notes
  labels:
    environment: production
    app.kubernetes.io/environment: production
spec:
  secretName: build-wyattbubbylee-com-prod-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-dns
  dnsNames:
    - build.wyattbubbylee.com
