apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: markata-go-encryption
  namespace: wyattbubbylee-com-prod-notes
  labels:
    environment: production
    app.kubernetes.io/environment: production
spec:
  encryptedData:
    MARKATA_GO_ENCRYPTION_KEY_DEFAULT: AgAvmcLKLIyAA2al5fkkQCb6xq+7s5MLNUJxYL1Z1z+9U33JHtGyv63IgbL6p8SEYTCLUONco8WZSN1BrCbIhgn+zvsf0IdIX9y8aCCH+DgU79aL1zfmOjScYEVOFGjqMO8Grq0UteoVm7uC72ohCwmu/WYk9LwFD/Qvak13qWBs1JRz0pxWffjJv3+ncuM9W+cicOjUP5RqNS+7RvFZcyAF6yLQCRLZ4rZydNT1xc3Ja/AMZaNpV+p7pIQAAwMg13B5eIcW+1LmARdjck9DDJIZHtGpQbJ/EhMPmJcngCxNVmzyQsRTCNJvl1bKHvX3YdPrJyA+zn6Pa6fUmGsnjKEDOf0cL8QyeGkr6MVPOlKQmQxWQJg7xUnCKYtlQLSnrGUlbywZNfMopEIaMfgiby4vdqVWOymrHXuCpEKja0eUDju1aP/gNlQ+swJ2DqvNRIQK5fjr7uRgCaG1U6QAiQl/1LpxsLvIQ7rC6+lQMVve30KSc5jRus04KcMmonGBm9PmsoeSkkyrsEBGxIwvgM7WhDSLmMAU8r9ga5HEiKJnUQa8B6oaIhSCR1iXoDjLERP4DQ/EOldq6OJLfeW+L5TMcTtrYqFEr7A3zPZ5eh1v9FD64SRFIMfZv9vRc0+/y8JMHkILbr3eBh9sVkGaDgIj51oWDp4FoD06/DZFzqHzTayHFIIy9MblXJT8u/SCmGP3RdWY6FOEDq6B32wnGBroiVET8hn500WJIBlkd2VuXlrVXXjiNgMGHwsfBD0=
  template:
    metadata:
      name: markata-go-encryption
      namespace: wyattbubbylee-com-prod-notes
    type: Opaque
