apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-production
provisioner: driver.longhorn.io
parameters:
  # The JSON here is how Longhorn wants you to format the recurringJobSelector.
  recurringJobSelector: '[{"name":"longhorn.io/recurring-job-group","operator":"In","values":["production"]}]'
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: snapshot-hourly
  namespace: longhorn-system
spec:
  # Add them to a logical group, so volumes can reference "production"
  groups:
    - production
  task: snapshot # Snapshot only (no backup)
  cron: "0 * * * *" # Every hour on the hour
  retain: 24 # Keep 24 snapshots
  concurrency: 1 # Run 1 at a time for this job
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: backup-daily
  namespace: longhorn-system
spec:
  groups:
    - production
  task: backup # Create snapshot, then backup to offsite
  cron: "0 2 * * *" # Every day at 02:00
  retain: 7 # Keep 7 daily backups
  concurrency: 1
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: backup-weekly
  namespace: longhorn-system
spec:
  groups:
    - production
  task: backup
  cron: "0 3 * * 0" # Every Sunday at 03:00
  retain: 4 # Keep 4 weekly backups
  concurrency: 1
