apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: snapshot-hourly
  namespace: longhorn-system
spec:
  task: snapshot
  cron: "0 * * * *"
  retain: 24
  concurrency: 1
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: backup-daily
  namespace: longhorn-system
spec:
  task: backup
  cron: "0 2 * * *"
  retain: 7
  concurrency: 1
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: backup-weekly
  namespace: longhorn-system
spec:
  task: backup
  cron: "0 3 * * 0"
  retain: 4
  concurrency: 1
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: snapshot-5min
  namespace: longhorn-system
spec:
  task: snapshot
  cron: "*/5 * * * *"  # Every 5 minutes
  retain: 12  # Keep last 1 hour worth of snapshots
  concurrency: 1
  selector:
    # Match volumes with this label
    recurring-job.longhorn.io/snapshot-5min: enabled
