# https://longhorn.io/docs/1.8.1/snapshots-and-backups/scheduling-backups-and-snapshots/
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-backup
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  # Select recurring jobs by name
  recurringJobSelector: '[
    {"name":"snapshot-hourly","isGroup":false},
    {"name":"backup-daily","isGroup":false},
    {"name":"backup-weekly","isGroup":false}
  ]'
