services:
  podfetch:
    image: samuel19982/podfetch:latest
    user: ${UID:-1000}:${GID:-1000}
    ports:
      - "80:8000"
    labels:
      kompose.service.expose: "podfetch.wayl.one"
    volumes:
      - podfetch-podcasts:/app/podcasts
      - podfetch-db:/app/db
    environment:
      - POLLING_INTERVAL=60
      - SERVER_URL=http://localhost:80
      - DATABASE_URL=sqlite:///app/db/podcast.db
volumes:
  podfetch-podcasts:
  podfetch-db:
