# ---
# apiVersion: v1
# kind: Service
# metadata:
#   annotations:
#     kompose.cmd: kompose convert --namespace matrix -o matrix.yaml
#     kompose.service.expose: m2.wayl.one
#     kompose.version: 1.31.2 (a92241f79)
#   creationTimestamp: null
#   labels:
#     io.kompose.service: synapse
#   name: synapse
#   namespace: matrix
# spec:
#   ports:
#     - name: "8448"
#       port: 8448
#       targetPort: 8448
#   selector:
#     io.kompose.service: synapse
# status:
#   loadBalancer: {}

apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: matrix
  namespace: matrix
spec: {}
status: {}

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   annotations:
#     kompose.cmd: kompose convert --namespace matrix -o matrix.yaml
#     kompose.service.expose: m2.wayl.one
#     kompose.version: 1.31.2 (a92241f79)
#   creationTimestamp: null
#   labels:
#     io.kompose.service: synapse
#   name: synapse
#   namespace: matrix
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       io.kompose.service: synapse
#   strategy:
#     type: Recreate
#   template:
#     metadata:
#       annotations:
#         kompose.cmd: kompose convert --namespace matrix -o matrix.yaml
#         kompose.service.expose: m2.wayl.one
#         kompose.version: 1.31.2 (a92241f79)
#       creationTimestamp: null
#       labels:
#         io.kompose.network/proxy: "true"
#         io.kompose.service: synapse
#     spec:
#       containers:
#         - image: docker.io/matrixdotorg/synapse:latest
#           name: synapse
#           ports:
#             - containerPort: 8448
#               hostPort: 8448
#               protocol: TCP
#           resources: {}
#           volumeMounts:
#             - mountPath: /data
#               name: synapse-data
#       restartPolicy: Always
#       volumes:
#         - name: synapse-data
#           persistentVolumeClaim:
#             claimName: synapse-data
# status: {}
#
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   annotations:
#     kompose.cmd: kompose convert --namespace matrix -o matrix.yaml
#     kompose.service.expose: m2.wayl.one
#     kompose.version: 1.31.2 (a92241f79)
#   creationTimestamp: null
#   labels:
#     io.kompose.service: synapse
#   name: synapse
#   namespace: matrix
# spec:
#   rules:
#     - host: m2.wayl.one
#       http:
#         paths:
#           - backend:
#               service:
#                 name: synapse
#                 port:
#                   number: 8448
#             path: /
#             pathType: Prefix
# status:
#   loadBalancer: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: synapse-data
  name: synapse-data
  namespace: matrix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
