---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: play-outside-secret
  namespace: play-outside
spec:
  encryptedData:
    PLAY_OUTSIDE_OPEN_WEATHER_API_KEY: AgAWpHVb5oYUyNknLqrhSOqhYXEvE3onsaBEpvSF3MEilWSrprTY6FwJizrYWjURVA2ASuQjEVmINKxVOT2qCRtmdWHm1yGfaz4b+2ps4m+FftQjmtzhDYLMvH3yHOxNjJNPkW2mJXeUeOg3pOtAMZ+hMSeUZ5eb+b6gQtoVIoSYTOlfH9WWuKhRGFJQiAAHmXNm8esLZrXyL9JykoGTQzxYRPbiATvYCjzYo/A5qZMtU9r0fxxL8UrCjPD3OwNhE3BrKDOaJ8HCcQJL6qQS4FzBR4t90Y+1rR2z9qH4sNWHawRo3KzVk6BkM+fwS6AcauyAHMFGMHzbTIAmb7MpknO/CFnFpWq0nWY82bKlncSOHW1xI+Rj0bJ5u7HRKGzSt/ITwx7Nw8BgsU+feZA34ivmuS7t5C7jxs7ouW8zoWuqj7gfaFxX5o4r+bQCXkOhcnf4JJy1N4I3p2An9NlMGMvCvBygCdzaO0YqQ28sccwU8veVh9m3LVauGbnU0qua09wKjDg5eqNkLfKzLV24121BmIiYeOWo/+BojY7dLP/9EsmxpAvAqZxj4GbtphGmKP4Sb9iGeSsb+mvuVMcuAi1zMXjlzYAMXQEU94LIpNiKgrQMca8STcpT5QvjhMcx4wlrQk7XBJGHcI8isWLbo0cSrpL8Xs0C4Go1xn9toqdif8bLq5qNfkOhEk46KksD+avDGiwvOgqodo9LhVSAijZeMttu1eOhekozMRavGcwHpQ==
  template:
    metadata:
      creationTimestamp: null
      name: play-outside-secret
      namespace: play-outside
