---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: play-outside-secret
  namespace: play-outside
spec:
  encryptedData:
    PLAY_OUTSIDE_OPEN_WEATHER_API_KEY: AgCUjC3q99QcKSJESB4kfq78qNB8G8dE14TJOCAmEzzaQLmad+cZ6zie6iExIuIbwP8zUZX+gfZJKKd4wi4Il+5RiVpgyJIegKkbeJhADlu4IvyhJmdj1O1TrcXJZoGJXRlyJZCIMfV2NkZ6MTd1+6bHmfBiwI9AAzUXCpbyxvgofjJ0V3m7qPurObPN9k04Rk9+njdW+ulLFFNzBLNsBZTf0YEz2WcmTbdnqbtj6I9s9RYiHQOv8ipqx7zV5ldXoCmjLnT/1JG86nKmj6r4siKoB6RcbS7bkuLb2FG8V1YknkIdc3Cgrsh1kCmgVeu1Tcag883wUdsGFcQ04cogLQ34ilgZgpjLigz0ectCxDEkhfrRmKVXyimJJjnEepKP1mZeVqs6w/E0Nl8QEw/0A9J11e0X/eCdMZszuvgVrSQ9MIUpZdR0dS2I/aeGughJDiRehvNSFnvO+j3Ev5kfnObMzkzmMXziv46ZeJ98IXZWBznRIz+5i2noI8tNSKX9SXa31UsdaszdMgm2FY9NWljbglxHD2ZOXSx/peBJdnE7+Mb1szkaQExvnMLkA2rTPQKJf4IlOJhnJpoC4Qjtxzrav9TqhY6h0DPZdp63L2VD+4Pa5XQIGTRFBeyzcmPICWBEq+mIirn9Yew+eE3HbCk9o4nniun83bZSdmJF6VJ1CyRlaC2uhfgWX90B46YVvRLjD6/E/Q9g99egvXiEiORS2N2ASB4OkTaYYLhMmWfjcA==
  template:
    metadata:
      creationTimestamp: null
      name: play-outside-secret
      namespace: play-outside
