apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    service: play-outside-wayl-one
  name: play-outside-wayl-one
  namespace: play-outside
spec:
  ports:
    - name: "8200"
      port: 8200
      targetPort: 8200
  selector:
    service: play-outside-wayl-one
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: play-outside
  namespace: play-outside
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: play-outside-wayl-one
  name: play-outside-wayl-one
  namespace: play-outside
spec:
  replicas: 1
  selector:
    matchLabels:
      service: play-outside-wayl-one
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: play-outside-wayl-one
    spec:
      tolerations:
        - key: "performance"
          operator: "Equal"
          effect: "NoSchedule"
          value: "low"
      containers:
        - env:
            - name: PLAY_OUTSIDE_API_SERVER__RELOAD
              valueFrom:
                configMapKeyRef:
                  key: PLAY_OUTSIDE_API_SERVER__RELOAD
                  name: tank-git-play-outside--env-prod
            - name: PLAY_OUTSIDE_API_SERVER__WORKERS
              valueFrom:
                configMapKeyRef:
                  key: PLAY_OUTSIDE_API_SERVER__WORKERS
                  name: tank-git-play-outside--env-prod
            - name: PLAY_OUTSIDE_OPEN_WEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  key: PLAY_OUTSIDE_OPEN_WEATHER_API_KEY
                  name: play-outside-secret
          image: docker.io/waylonwalker/play-outside:0.0.29
          name: play-outside-wayl-one
          ports:
            - containerPort: 8200
              protocol: TCP
          resources: {}
      # imagePullSecrets:
      #   - name: regcred
      restartPolicy: Always
status: {}
---
apiVersion: v1
data:
  PLAY_OUTSIDE_API_SERVER__RELOAD: "false"
  PLAY_OUTSIDE_API_SERVER__WORKERS: "3"
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    service: play-outside-wayl-one-tank-git-play-outside--env-prod
  name: tank-git-play-outside--env-prod
  namespace: play-outside
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    service: play-outside-wayl-one
  name: play-outside-wayl-one
  namespace: play-outside
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: play-outside.wayl.one
      http:
        paths:
          - backend:
              service:
                name: play-outside-wayl-one
                port:
                  number: 8200
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - play-outside.wayl.one
      secretName: play-outside-cert-tls
status:
  loadBalancer: {}
