---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: play-outside-secret
  namespace: play-outside
spec:
  encryptedData:
    PLAY_OUTSIDE_OPEN_WEATHER_API_KEY: AgAe98H40kmxelyuKWeebRG5RLWiQL7fa3hK9wJik5d7RF0FnOE0mHFBBjaKc5XSxAnh0vaDvFgHlZGbqpgnThE3mDIrZUrG4jdn7Io+3gveI1m1F/hQho2A47fQlpr8vvHbyrzltz3s5BwrqOD5j0rwBR33s98mX1rkKP8qR7d6kmVVKw+hhmvyJcVZwITfROI+4Xf3FZkCL6UZtv7NaZSS8s2v7SaDt+zdRTpm/RJpaefZeZFCJcGVN4X/EHTvd7+xYu0/yrk2E9m4VEUywd84j3jIR1JPXxyrXT4un/PSP+F6IqZ56VZ3ip0W3BpOaqCW/YHQfWHlnUCqtSmixjCtltb5SFC0b5JNOtL97VZ5RVRBl3F/07DlnYTrvGV29QhScqHGjPAPwCD8aur9d8KwbDnLWaveAxG80bVpnHvqKTYEWtqk9Oh79j4qy9k6bAMEVQ79VJs4vR44KRRVmoZ1FsvyD0L1ClOGfegnzXMfFhKyiGsqabiq/f1hDC4E35NwLIX9/Kc5xcBVPcryFRdH+L2MXfb2p1CRGtmC3m8W23J/9SLDHaEhBfb3SBj71YHSlMV9TCz7OgfQr65uA6l3efQF00PmlB7HwOZjIPewK6eijCCU1SbSsGVTNT85akvV8IVb18Z0k69UiYX2jG3MYMvczrLDgoM5oDixLOxCyHbh4/7At4pU7Qb/6SkDRjaDhgKL6ZzkVYKK8P/s7d6R0wCcgnPWH/rtAFQEXQJqeA==
  template:
    metadata:
      creationTimestamp: null
      name: play-outside-secret
      namespace: play-outside
