apiVersion: v1
kind: Namespace
metadata:
  name: forgejo
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: forgejo-db
  namespace: forgejo
spec:
  instances: 1
  storage:
    storageClass: longhorn-backup
    size: 10Gi
  bootstrap:
    initdb:
      database: forgejo
      owner: forgejo
      secret:
        name: forgejo-db-credentials
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-db-credentials
  namespace: forgejo
spec:
  encryptedData:
    username: AgAb+3w4y7vabESIP7XcnBFcpDStnFFrZYgPfrtK40AaJoTnpFveLK8y/hMQGrHooSfSAOicRqCKq1k+kxS96zo/jOGISYwo4JaMMyjiTKx5hWAMLVMck+rKmj1NDoNBWPV+9MnafLy/VOzRx0mohT+rKUv0bNoXtJfgH6+A9ThbPCkUyovTRdjpqzWA9KmLZSpQwheihJfHeY716E5B2ywyTZNRXOMHAOQoMhktnNW+/HfLe8K6sMYhuA7zEo2ZvXL6l7vLj8OO/4WECkZForQn162rMIyjj5a4klZIGNNIkw2EMk76ZFHzHCqYsgLIAmYJae78nBjkei5iLHn9tw18HqQ3VWEBgIMTFNC9AUTvI3Qecnrd54E4kJnUqLsZzT8shRDFj+iRlyrvCaR7PddlgQ0cLOlL3RUOD+41g9qY2eAwk0sOv0waxKqrrk3LOmoRmRHo1+Z26pMEEIeXqZ829vKLFFuXZ4AB/Ziuobgy0XmI5PTAYWBzV5xwtwL4nA95aSxWZrlXwA6lqaW+2n8MDnGtEKDe73Go5LvgXqq6PXZl5SSj7jOUzvd0s7mpUOb+2aXFj196d9TZIhDnxCyny17fZNLsOwhpURKX8SS8hy7jGBlAkwRfyGkcojlsMeWlwh99ltHhR+261knq6McJJctMwd6bAac+o60M6Iwn+3kR+T55nb+2n3LEvcf4px0jXC6BcIAv
    password: AgAvbHhBwxzrKJYaVnaNcfeeu5b9GH2j/Se6sMPRs8+kWbztqmLHXwuhYi+uxsXecpY9UDBFuTE42RESVR2PFOuBBYpz+G7xD49erkreSDBUU9JAMOnWjJKpujp9IyurGv6yL8fAQ8Koc0glAqsVuOHYIXltjNBnMEU8CHzLNCfncq2feHz4yMIv2eI+zJ3TUzmoYhxvsHZqrZB9X+FnDOV++C/VVP3UU7G9Py/Sj0w2Bgjq4E2tBnhjkV8J/bbIX6kUPmGGBGDtCl8TC8Ys2476Ru89plEv/Y4RT4ToFWHAk9Vh980zRVDxolNw1WCPJPhGkbXzhJymdA7rWyHFZiVZ0jCfwRMySa2H0+L6VYwd/DkbC38kX7tpiuggoVTDKHsyOsLFk0np84PTA2fnVR7PCCn+8TGyHJISrbxfT5UerDsH3tW/d2EBl5IEahrcpXKv+aEZcZOzfIUvVeFVaZkvZY2h2y0fFmaLxPZSd14vVXjGWmL/DyGMX6jweG5ymfn6OkBjVuQ5yznKpb3UCsJo0LuPKRVDW71Q7AUOhk+uOlcHHt7A5mjMQhAiGmsCxHbziNZivA9pkhNQOsH8R0OF/2ETFlYmTWGdtqbpCsFkBIaHSDODNbm8D72qFx9HCWp8w6N3lS0UuuC0++w1Nb2MHL7Bqh/4ij/Jud0+BEPXOEg7dkevbYkG+Ru8fQHSNbxAbOrocVydDYfITyVsA3SP96HlkBG1B49ephR3NB+W7Q==
    database: AgBR6oawKRIUEHkGY40oQs4bc7BqBOO3O4sPom1jxobD+3MIkcWxKqvaNTTxo2Ou8GQbtiko3XZAZ2df4OAi+IY7F6WASfLCSmZIB3Ox7jPDalseJD+2kELFlIxk+unSrexCBEF9ptv5aka8LOxO53uj1DYIXXThf/LwWDfALKOpweQ/dueOjAwuOxkYSrQavnyikvdYPcR6RxibQDHGxy3ooV5FZ/XmHS8yfaCbxhfojtCwSiWmD1TjP4kQ3L6giEZNeMpPw3WhNgCQ6FyJ8gA1TOR3ZY3ATJHjsiMV8v+EBrDIQBN6OIsiVvUcqg30jGutClLpv0lIeS2dZXNSfrraG50OSQdho4xXvZCk7JfN1Y66AFje2oMgOXwpdC87lEoW5xascsEmRtjUyih20Cy9tOp7kenQxdTDayR6e5XgNyhFZgSHLBwaVswHthUceLmsxL4zgpcf7UuYhVYvjIjUoepjMduNDFOqfzLqPhMyVhnVFeh0jiMHntyaXJb/sFrToMNR7KEPr+dKqvgZ7JkQ22QgszvnRXR3aHaTLG6bY4v8WWdqJNreiNDV3cmTAWpFh54m476Kb4xVf+J7nSkMlGXMdJ+R3sTUFI1LU9OayhfmwelWV0RG93Op/0Lu4Vx0A8mKpL+NhPRT82uS+RNqNM9SqXdq1Z1a4GUqZ+RGsaqiR7vPk9oZ1Kn2PzIUB1xBriO3XjZr
  template:
    metadata:
      name: forgejo-db-credentials
      namespace: forgejo
---
apiVersion: v1
kind: Service
metadata:
  name: forgejo
  namespace: forgejo
spec:
  selector:
    service: forgejo
  ports:
    - name: web
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo
  namespace: forgejo
  labels:
    service: forgejo
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      service: forgejo
  template:
    metadata:
      labels:
        service: forgejo
      annotations:
        diun.enable: "true"
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: forgejo
          image: codeberg.org/forgejo/forgejo:13
          env:
            - name: USER_UID
              value: "1000"
            - name: USER_GID
              value: "1000"
            - name: TZ
              value: America/Chicago
            - name: FORGEJO__server__ROOT_URL
              value: "https://git.waylonwalker.com/"
            - name: FORGEJO__server__PROTOCOL
              value: "http"
            - name: FORGEJO__server__HTTP_ADDR
              value: "0.0.0.0"
            - name: FORGEJO__server__HTTP_PORT
              value: "3000"
            - name: FORGEJO__repository__ENABLE_PUSH_CREATE_USER
              value: "true"
            - name: FORGEJO__repository__ENABLE_PUSH_CREATE_ORG
              value: "true"
            - name: FORGEJO__database__DB_TYPE
              value: postgres
            - name: FORGEJO__database__HOST
              value: forgejo-db-rw.forgejo.svc.cluster.local:5432
            - name: FORGEJO__database__NAME
              valueFrom:
                secretKeyRef:
                  name: forgejo-db-credentials
                  key: database
            - name: FORGEJO__database__USER
              valueFrom:
                secretKeyRef:
                  name: forgejo-db-credentials
                  key: username
            - name: FORGEJO__database__PASSWD
              valueFrom:
                secretKeyRef:
                  name: forgejo-db-credentials
                  key: password
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/version
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/version
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              cpu: "1"
              memory: 2Gi
            limits:
              cpu: "2"
              memory: 6Gi
          volumeMounts:
            - name: forgejo-data
              mountPath: /data
      volumes:
        - name: forgejo-data
          persistentVolumeClaim:
            claimName: forgejo-data-v2
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: forgejo
  namespace: forgejo
spec:
  minAvailable: 1
  selector:
    matchLabels:
      service: forgejo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-data-v2
  namespace: forgejo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn-backup
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forgejo
  namespace: forgejo
  labels:
    service: forgejo
    # If you're using cert-manager, you can add annotations like:
    # annotations:
    #   cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - git.wayl.one
        - git.waylonwalker.com
      secretName: forgejo-cert-tls
  rules:
    - host: git.wayl.one
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: forgejo
                port:
                  number: 3000
    - host: git.waylonwalker.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: forgejo
                port:
                  number: 3000
