---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kave-playit-secret
  namespace: kave
spec:
  encryptedData:
    SECRET_KEY: AgDEe8SziRzdHRiKb3pVj4Kj+d6cI7O8sDu7Ig6ILagZBinhwpihxxpXV97hKfc6EvHj5QYC8jBafIhheB5MM7C/kKt4aMrMkaKRCwxQUwzddjbw71FUAYqZ3m8ZUt7W8GOcyCydwOmwVo+dIoyrcmE13u0oBNEpUFv1m1+fsfj5OTVgnvcaIz3fplTkUCy7zDkUW50Q7MpSji9PK26sMo4t98czRShl2OsKW44hlSq+BOo4PvjyM4ZiLgdbzYMCuBLWeUWLDGnNHUI/8arGUf1CwJ6tfewggorbzQJfcgNwnGv1DLHePurahwH61M3SxCWN4dlxCSDLGR3mtXkIRfDjYi719XgQgDrBfkAj1Cogq/UKfriRNTP2a/pLodZV6MIbg50u2k4n1CSkvE+18pFJz5Hal7Dno5MUTZVTHedbR07uGFVIFl9VmNzVTb/eZ87S69qc49U6imU9QKJZImhfWIoczhF+lQBi83AcH+jQug2HQGoA2SM/Na4Yt/dQFV+qqIz0mBw/NLXIZdb9UJ7/JNi5mH+G6q4o4Zr0cOlEtqqyvp7UWW7raGu8l7qCZBVn9PJMedvHKPzTOtGfXCufVaIB7T8og8gtVoLB8AixpWVMMvDgPPX4shmH1E5zpK0B1Ia6os0sYIkXKvf4TYqupCjViSCoB11nu5NLAwuglWOKBmb97rf6h86Q8Ail6jlZuzsioZBpy/W4SWMCVps9mWig6U/SwKqRfoATDeQKKr9ZOpCIBX5AJRj5wqc6ywita/uiWRLsCNx2Uldoh/ff
  template:
    metadata:
      name: kave-playit-secret
      namespace: kave
