apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --namespace htmx-patterns -o htmx-patterns.yaml
    kompose.service.expose: htmx-patterns.wayl.one
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: htmx-patterns
  name: htmx-patterns
  namespace: htmx-patterns
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: htmx-patterns
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: htmx-patterns
  namespace: htmx-patterns
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --namespace htmx-patterns -o htmx-patterns.yaml
    kompose.service.expose: htmx-patterns.wayl.one
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: htmx-patterns
  name: htmx-patterns
  namespace: htmx-patterns
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: htmx-patterns
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --namespace htmx-patterns -o htmx-patterns.yaml
        kompose.service.expose: htmx-patterns.wayl.one
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/htmx-patterns-default: "true"
        io.kompose.service: htmx-patterns
    spec:
      tolerations:
        - key: "performance"
          operator: "Equal"
          effect: "NoSchedule"
          value: "low"
      containers:
        - image: docker.io/waylonwalker/htmx-patterns-waylonwalker-com:0.1.3
          # - image: docker.io/waylonwalker/htmx-patterns-waylonwalker-com:latest
          name: htmx-patterns
          ports:
            - containerPort: 5000
              protocol: TCP
          resources: {}
          env:
            - name: ENV
              value: prod
            - name: API_SERVER__RELOAD
              value: "0"
            - name: API_SERVER__WORKERS
              value: "3"
      restartPolicy: Always
status: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kompose.cmd: kompose convert --namespace htmx-patterns -o htmx-patterns.yaml
    kompose.service.expose: htmx-patterns.wayl.one
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: htmx-patterns
  name: htmx-patterns
  namespace: htmx-patterns
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: htmx-patterns.wayl.one
      http:
        paths:
          - backend:
              service:
                name: htmx-patterns
                port:
                  number: 5000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - librespeed.wayl.one
        - speed.wayl.one
      secretName: librespeed-cert-tls
status:
  loadBalancer: {}
