---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: registry
spec:
  encryptedData:
    .dockerconfigjson: AgB96Fgr+DK1an+A43SruaF8XjBxNIGS9fyO+q352WryTTdZJ4yRSarE/7IcRwEkQQr6Gyik94Fa/Vt4N+D+YMVu29mYMbKc7Jrl7MQxk1pGbYVJBYM477we3mJ2MaLy//PSG8M9GGFz0UPVaU1JFUr6tDEV1km400l1lFwbU/WhE0vdNPXJhfbpd8GJzZcCkLz5TmKu3alMUukjVSLK8mDOQ8JzMkEeED6hlDtNuJ+OOvdb+St7hrelrCkJ71Grib1zZS642CbiaZU6aJJxvei5652Nj3MFWiElMOv6qilrS7smbveFuI5Ya0MvxthValKgj4WIXxPVdEO+O373gTAaTwW78BkycnMRd1HQdMSlE2MiWpx9k4snBCrj0xsqsP+Fbj+HPFUpb7P0Zl+85Zn1RuqVaV46w0ootMH4hautGyH/S5wlX2toFRmf4fWtuEh8IGYYPkUQUhZtO8+utoSpS/ajkpKMDxvSMuqO5dCfJrYS+YSpAA4c0WN3rLK/zio2f82axBwk4Esj5rlAnxCOTy9eTUQUnqUClb77XT3PLD2EQ8MDsnFc/cC9nxL5x2tS5TzRBWCWLzYAlCYntJttLIe1gnF9G9b5GE8w5nXNgx0qpAs4GDA5teiCPpZWqJCttHJVABiqYUqI3FOe2HqgY+byyEwNsPouk/Mm42LV2OBwpxyFwKxqhXcmKVDW7K7QtTuBYOR+/vJSiGp9eZxqzkrrMpHd94DJ/6JEMh1Ze6zuDOrA87x7BsppSosLQAGGVKKeSL1RfGwnKmjbnUIA5V4/INYZpXB/loLFLiDeDspoA3otNgh6eDf218cd9baTJ8wvM2TE3A==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: registry
    type: kubernetes.io/dockerconfigjson
