---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-password
  namespace: registry
spec:
  encryptedData:
    htpasswd: AgA6D/zEdM6xPXp4vnaNYa0sWZT3ZvjDcoKOKTExoEvwsvQ5z4zQuxCptHcuoaitYxdizzytIkFX+pKqV2XnYQhpuFZrFlabmn17F72BgLiN9ZO1YzeH5Xan/mBfU91irnO7PknVh5U+ashMbURCTNB8yzeeFOJ/sLQfa6VJTQrc/s/EOnltcnFdb/wf0QCse0GY1EM31hcbRXs4OHZBDuJ7DzXyPFf2kvL3sfSy1tf75xsHLJKzrjfrOO0OgCHQrBZpgqdvG/rMsj+E7voFX8qP+LyLBJYYsWg8Ge0tX4ehv2NeKk7JsHs3do4PtVJrQ33aMy+K6pS6j+5vkb5wetHsBp4GsFeTT+Sr61w0u4fL1TJB5HCkeWWvqbzFmqLtiT5FOtHXDR9S1zBkcTWJ/HpbgFL7Umzt9enstGixOh9CjmN9tu9ri11cGlTPkWrL8V2zjcgHoSPywVPHeMZpU4dl1G/IfnvwEfm7739zkfIndwhxVda+UzgMbvnhRbqkLgxM/GOaV1aOKdc5/VysloBb//D5xnG6atzURN7JdO44Zgyd3xoRLK8auzTbK3Y/MQJbA2chjf1zOVp5PQSY25UqX9tmfR3BfobE6wvuok44QqzwSisl5U5p6mO8rV4qgkii99bf/27lJLV9de2a+vIRrLbSpfmn9xBQvdMBQDhM+GN3+uAW30chQcrG4dnSP3zO1oPTzZjM8IKmK1Kiy2PA9IiZ7N5Yh3Hnx/itTParkH2ns2NbDsWDK4K2n50GQTvEjEh8sUYyxlJO2N7zn46MFvwPePo=
  template:
    metadata:
      creationTimestamp: null
      name: registry-password
      namespace: registry
