---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: registry
spec:
  encryptedData:
    .dockerconfigjson: AgCN42ezS82UYba/xCuZHaMZJQw/WF97qmqaXbBydEjvedRXi2wqQQN4SbIICZb7b9Ci/POeZuo04cvdva7PV4ynWHoBpcYAyU/MNrFmXsl33Bl8zZ+NR3kzAiZUJ5SUNelze0cg0OnLsm2VNC6ZvEMUJoVBtPgarEdDswZ6CyWbGtnII5sbPPJiAp+nsWQoI4cfREgp6pDHJc9vDHnerPHL9VN5oA0D2bpYuilc60xIgCKx7JCZlSm9IzwB4Sf/q4hbiA+eOyz6I/A2ACUdcRw0dwcwPjmfWU2bS+SVziMEfDEpOz/Pm49GGgMuegDycol2EcguAINw8wJkudSjqxnAS3fY+D1K2l7HVlUC62TO1ZLE02G0w1PgV6c6u2rH7D0PrwKhlWF5WU2Rd0nT9O+sA/w3wc55Rvtch8iahJuVS8SVYqLAOjtlnp6h9jQ8jb25vwduswJDVdJTgX8OMNK12Zkau3A4bLfDk2dCIcPUoFHE+VdlV5OD4jzoJwNrjLZ1Oactvfh4y21efKSCi6K+UNXtk96NigdueLF2WyzE2uSuV7kWhsCRQCl3lGu12aG0w8jPMk4etfUDpSJHfnqGCWaIkFldYyT9YB3EnAzkJhpPwIZw2G2nCXSM1qfLB8HZLVLjNDgrWbZtuDVHBA5Nhi2f6ZudO1lH0b/daDZK618L7+I4NnN2b+REJbTd1jP2wo+3GZq/GNb9o7y/bCgyHo2xKY82SlpagQnsL8Z2GEUWUYISEEFxsrnKrXc1mJ6aNt0WTRO9LKNT4o4jTRl0Dkzk31SwwE+PH9wpbUfkMLt+gUr2JLkDsd8oh1H1rpqF3b04kpY1XA==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: registry
    type: kubernetes.io/dockerconfigjson
