apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: rwcode
spec: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: code-server
  name: code-server
  namespace: rwcode
spec:
  ports:
    - name: "8443"
      port: 8443
      targetPort: 8443
  selector:
    service: code-server
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: code-server
  name: code-server
  namespace: rwcode
spec:
  replicas: 1
  selector:
    matchLabels:
      service: code-server
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        network/code-server-default: "true"
        service: code-server
    spec:
      containers:
        - env:
            - name: DEFAULT_WORKSPACE
              value: /config/workspace
            - name: PASSWORD
              value: password
            - name: PGID
              value: "1000"
            - name: PROXY_DOMAIN
              value: rwcode.wayl.one
            - name: PUID
              value: "1000"
            # - name: SUDO_PASSWORD
            #   value: password
            - name: TZ
              value: Etc/UTC
          image: lscr.io/linuxserver/code-server:latest
          name: code-server
          ports:
            - containerPort: 8443
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: code-server-data
      restartPolicy: Always
      volumes:
        - name: code-server-data
          persistentVolumeClaim:
            claimName: code-server-data
status: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    service: code-server
  name: code-server
  namespace: rwcode
spec:
  rules:
    - host: rwcode.wayl.one
      http:
        paths:
          - backend:
              service:
                name: code-server
                port:
                  number: 8443
            path: /
            pathType: Prefix
status:
  loadBalancer: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    service: code-server-data
  name: code-server-data
  namespace: rwcode
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: watch
  namespace: rwcode
spec:
  containers:
    - name: cleanup
      image: registry.wayl.one/rhiannonwalker-com:50
      imagePullSecrets:
        - name: cluster-regcred
      command: ["sleep", "3600"]
      volumeMounts:
        - mountPath: /config
          name: code-server-data
  restartPolicy: Always
  volumes:
    - name: code-server-data
      persistentVolumeClaim:
        claimName: code-server-data
