---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCYEueiPP0T/J1yzRg0P0ql/uXwScFA5OBVFq519pMxSTwQGaJyJZwMXtlRqvokmYjEtYv11qDfD1O15gWWVyj2r0wvRCesLpwWfe8uQUYyduICceI2wpUsrxMzDMUQ3QJFiMz4XK95PqPEk/2f8aVdYngnac4pe81ULwbUi/OxP3aG3SCeGHwa//Su6kRsSA0BX4vRnGFBnIMms4QjzXGty6IB9zffzQGFtzfkIbIiUTv58NnZhs6MbVkzb7jSag+8dmCgbY3XoMfUdojMjkRNNW+rLVnvMVQRp0nx3LFYAhegGcO8iZyR8KDqhHlyI27/uwppkGG9xcebIhokQznN+CcQdlhMEtsqPI7oJXYZjDpptYoNvj4IkBBS2/3o0Qq84VSmPmpEZbn9XM+kWimuLyfgMgj8VSuj/3F6SfwrzJPwq95dmgtCppB2WM4sbzUQycRghTC8u8rpabfwXk3HZkh7uGHIEBPi2J9q+W/RNlda19CvPvM2/m0nuduWEdBP9KD0mFFBm9wpKpTRCpIrDfr5a1aiy0ivzngJeyYsHzVPWoQFwWZd2VlVSnAbue2/n7aHhlg+vYRwoj82zaaqJah2w/IeIuvXThQNxSLAmRD6YFfGXOx2S0SSpDPHYq+CzwLKFRv/JKivI1drWl+PWdt0H0Iy+lLJv3FO8I/VH2cDldsl41SCNkNIjzYMXJhPgnvHnhliJyNMoFJG8hyYzXmgH9thxjL+1A9MvxvVQbfcgLwRxx4RnnINFgMjw2seVsCdAw==
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
