---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBSLhl42qNjGYmqJcKQ+K0TfCXa9d7UjTUQGOftsEt53xIskyUDDRy374NOkIZIqAXH0aJ6tuSWq12JseIm778uDGouUN2l4DcYbCsRYdAfDpSXHfwPjEJehkyiUyf1DY0ryN7BjB2zffWHh+oy/i7EOburEtc73tmtTg+yOM07OXMP0qOjWwh/lc7dJRt56aeGyxq4pF/Q7U8adwKoRzP3uQIS6cmp5d3LH5Fh6+660AP1kxS0fUI4NpZhIJXJpfsAG58ED5INm5hcEx5KW8l9k8OIiCyPs7mi9393QZKHuWU81qH3X/Up5sQgWuos0MtmiTMczD4LQTcPTm7q/5sDoBNQTT+m8+WMHyDWNra7Q4U0HFpiWpDM6KjijhH1pIxoFItZILxhtqNolLCbD+BwL4t8nswvaF0DhpVT67mNl/H9Yw8NVDQobsHQtTeLxFBJi1l9aOaEt4L2zlbLYBIhcRmFDmAui6MzcHoRM9wIkUgp4/al6EPmpFRtlGMZmRVpBM3NuEiHh31F4NFwpII4cjkp83lSLlqoWqUTWibjcKiObEeIh1nAtF5fpD5Mb6AL3CRvHpWHlmgHgsET/mbJFgG2zIjrvnVBN/O4+0sLHKZEaZdspq8CQAok8lStfPwnRu9RW7wyBMEB5nQfSMPV3A5DTwmcLWTNC/MAC7CtsMMKfbnuuaK9SYIVrHkHhbPBIbuyAvZ3qvcr/10KcoAn4mC2v6PS4q9LaORWv/7MMZR0+0dNnmdUKS0l5jjBrnxIy3Y4LA==
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
