apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: waylon
  namespace: default
rules:
  - apiGroups: ["argoproj.io"]
    resources:
      - workflows
      - workflows/finalizers
      - workfloweventbindings
      - workfloweventbindings/finalizers
      - workflowtemplates
      - workflowtemplates/finalizers
      - cronworkflows
      - cronworkflows/finalizers
      - clusterworkflowtemplates
      - clusterworkflowtemplates/finalizers
      - workflowtasksets
      - workflowtasksets/finalizers
      - workflowtaskresults
      - workflowtaskresults/finalizers
      - workflowartifactgctasks
      - workflowartifactgctasks/finalizers
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: waylon
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: waylon
  namespace: default
subjects:
  - kind: ServiceAccount
    name: waylon
    namespace: default
roleRef:
  kind: Role
  name: waylon
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: waylon.service-account-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: waylon
type: kubernetes.io/service-account-token
