apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: waylon
  namespace: argo
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflows", "workflowtemplates", "workflow-events", "clusterworkflowtemplates", "cronworkflows", "eventsources", "sensors", "workfloweventbindings", "workflowtemplates"]
    verbs: ["list", "get", "watch", "create", "update", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: waylon
  namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: waylon
  namespace: argo
subjects:
  - kind: ServiceAccount
    name: waylon
    namespace: argo
roleRef:
  kind: Role
  name: waylon
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: waylon.service-account-token
  namespace: argo
  annotations:
    kubernetes.io/service-account.name: waylon
type: kubernetes.io/service-account-token
