apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fokais-cloudflared
  name: fokais-cloudflared-deployment
  namespace: fokais-cloudflared
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: fokais-cloudflared
  template:
    metadata:
      creationTimestamp: null
      labels:
        pod: fokais-cloudflared
    spec:
      containers:
        - command:
            - cloudflared
            - tunnel
            - --no-autoupdate
            - --metrics
            - 0.0.0.0:2000
            - run
          # args:
          # - --credentials-file
          # - /etc/cloudflared/token.txt
          args:
            - --token
            - "$(CLOUDFLARED_TOKEN)"
          image: cloudflare/cloudflared:latest
          name: fokais-cloudflared
          volumeMounts:
            - name: fokais-cloudflared-token
              mountPath: /etc/cloudflared
              readOnly: true
          env:
            - name: CLOUDFLARED_TOKEN
              valueFrom:
                secretKeyRef:
                  name: fokais-cloudflared-token
                  key: token
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: fokais-cloudflared-token
          secret:
            secretName: fokais-cloudflared-token
