apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: article-listener-auth
  namespace: article-listener
spec:
  encryptedData:
    APP_PASSWORD: AgBD/oUFACbmYKlU1Kpfk3qNR+WfA1EXYASbSTfgtIDyZ3d8mOArTcCndujOMFD305zBFlT0p+nDOKXLu04X4Xsi/Y0pSictCns1m5qhQyvT5sDOEIRW18CRqNpdqmUFeAA7CgZc1N7EFCm+wTVZaUV7QpETP+5uFJC6ApD0fqiczT8m2DPVqW0YS3MEtu5axXUqyaFTt2cXOXKC2lJB2taWJQsHu1C2aeYFyA6MNrFoS3PHCPypCQvY7j7S9a3fs7bfSFdLD3QZ6J6EA30t62IiqKoM+bnbQNTHX97QPsKi8jMpacmVNTb6yKLZQuMGV2v/5+hof3hKxrUNrZ6lpdAPETganFHQ9twdnJCPgUvsB51ml98yvPVQvgJflWnwe+XBwsxC2xDy3R92j6HLBmNqTrh+2N7vSYpW8SUrtXTIMTEatzZd+C+0IAakmLv+fyl7X1yYgwWWT+AQpctwLmjo+7dHmlv10IMZ4Zki1hlOyjE3tpZSYn0CwBTywF08P0kNt7YvSxKWCnwSOFjcMFEZqhrVcD4atwtrjPwm+aQxMdhqyvKuWIFDTHqYUz3lQWdzGbjocSy5qw5gsyxsz3etIU/9PkB7CNhyh6vukKNBczVxO+aeyjDpv3lXhxGnwhJWls/eFRJHz4AcwZNtdePO+VvTiIqgHQIzPAdtWPlMmJyFf3OAPVZo8nDvvUkajwTNduG3zj2OLKwphG5KvlA3Fr2IZ0knGGZQKwZIsCaCHtz0W/KUhhasS8pqbeTqnDc=
  template:
    metadata:
      name: article-listener-auth
      namespace: article-listener
    type: Opaque
