apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: article-listener
spec:
  encryptedData:
    .dockerconfigjson: AgAiYJSwQlzuHSq1jBQeJlFkcTUt3UQ3Vxi3AQw1Uj3PxjQlB3B0UC4IlmXy6OMGlRlurmEtQiEiJTJ3OoefC7ZMyacEo7Wj5lkDG3zri1IlngyVi7cJAoiCG3J4//YRzv8ZvF/XYU8Tni9OTm7cOyJF1Mgd8uxZl6uGsag76vnNLCa1sbvjvhr28O8n/BFQdnoWVv+D3X1TZRs2nG9fb9rd20U9ZFId1hTqj1Iih9YZW/WhAriZQ+TFE76UsuggwNTlm8HeuDFQHTsxH7N+cNB/5LS6XztTOnC72BPyqJxjW6a1CmbOKeh+45yUnHJjjfVn8sDC+GURjg6Nc4E91QUTQAe0OtBpFHpK92vkf/TllzQbM/eLS3PRXwhnzrw6OvzS7HIb9rJEGxTCNqH3u7s7Xo4jkG9LsBd8mGSNoRKPsofbjV8ao/iUdj3micYmVgoCE4hYlubv/tviIwarARX/JDKBi/x/mxl6t7y/51KgAJlezjM8ZyrsUKEzEdRlQmBHfFisdpPriba+HCRgFJn96cUROdIzIQVTAuN6qkrxiQTBCVmgUOsdQL0OaZ2Rob9VbkgGKUoD2+9vcix7lhzwPcFW5r0wm2sSCx10tSAWFD8apMIV4uLun0CpgcOladAZlm/D8VX8YahQXhavyC9LP+pu64kj5KusYw+RGs18tf+gWqF2feWBVPp3o/LqPHqLgYTFhclot3/3iiEhAg9gP3pBfRDJMuurA/HL8jHAul7ugO8r/EZA7aPjibofIoxUPE80zqGGwUhsVl9RACsG3TSwRmMVdpTj8tRpKeqLcK7WWtMm8wl7hfTPK9ZkSIc43X3I9+Dypg==
  template:
    metadata:
      name: regcred
      namespace: article-listener
    type: kubernetes.io/dockerconfigjson
