apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: buildah-docker-build-
  namespace: build
spec:
  entrypoint: main
  serviceAccountName: build
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  volumes:
    - name: docker-config
      projected:
        sources:
          - secret:
              name: regcred
              items:
                - key: .dockerconfigjson
                  path: config.json
    - name: shared-tmp
      emptyDir: {}
  templates:
    - name: main
      steps:
        - - name: get-sha
            template: git-get-sha
        - - name: get-version
            template: git-get-version
            arguments:
              parameters:
                - name: commit-sha
                  value: "{{steps.get-sha.outputs.parameters.commit-sha}}"
        - - name: ruff-lint
            template: ruff-lint
            arguments:
              parameters:
                - name: commit-sha
                  value: "{{steps.get-sha.outputs.parameters.commit-sha}}"
                - name: version
                  value: "{{steps.get-version.outputs.parameters.version}}"
        - - name: buildah-build
            template: buildah-build
            arguments:
              parameters:
                - name: commit-sha
                  value: "{{steps.get-sha.outputs.parameters.commit-sha}}"
                - name: version
                  value: "{{steps.get-version.outputs.parameters.version}}"
    - name: git-get-sha
      script:
        image: alpine/git:latest
        command: [sh]
        source: |
          set -e
          git clone --depth 1 --branch main https://github.com/waylonwalker/htmx-patterns.git repo
          cd repo
          COMMIT_SHA=$(git rev-parse HEAD)
          echo $COMMIT_SHA > /mnt/shared-tmp/commit-sha.txt
      outputs:
        parameters:
          - name: commit-sha
            valueFrom:
              path: /mnt/shared-tmp/commit-sha.txt
      volumeMounts:
        - name: shared-tmp
          mountPath: /mnt/shared-tmp
    - name: git-get-version
      inputs:
        parameters:
          - name: commit-sha
      script:
        image: alpine:latest
        command: [sh]
        source: |
          set -e
          apk add --no-cache git
          git clone --depth 1 --branch main https://github.com/waylonwalker/htmx-patterns.git repo
          cd repo/htmx_patterns
          VERSION=$(grep '__version__ =' __about__.py | cut -d\" -f2)
          echo $VERSION > /mnt/shared-tmp/version.txt
      outputs:
        parameters:
          - name: version
            valueFrom:
              path: /mnt/shared-tmp/version.txt
      volumeMounts:
        - name: shared-tmp
          mountPath: /mnt/shared-tmp
    - name: ruff-lint
      inputs:
        parameters:
          - name: commit-sha
          - name: version
      script:
        image: python:3.11-slim
        command: [sh]
        source: |
          set -e
          apt-get update && apt-get install -y git
          git clone --depth 1 --branch main https://github.com/waylonwalker/htmx-patterns.git repo
          cd repo
          pip install ruff
          ruff check .
    - name: buildah-build
      inputs:
        parameters:
          - name: commit-sha
          - name: version
      container:
        image: quay.io/buildah/stable:latest
        command: ["buildah"]
        args:
          - "bud"
          - "--file=Dockerfile"
          - "--tag=registry.wayl.one/htmx-patterns:{{inputs.parameters.commit-sha}}"
          - "--tag=registry.wayl.one/htmx-patterns:latest"
          - "--tag=registry.wayl.one/htmx-patterns:{{inputs.parameters.version}}"
          - "."
        env:
          - name: DOCKER_CONFIG
            value: "/var/lib/containers/auth.json"
        securityContext:
          privileged: true
        volumeMounts:
          - name: docker-config
            mountPath: /var/lib/containers/auth.json
            subPath: config.json
          - name: shared-tmp
            mountPath: /mnt/shared-tmp
