apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: build-dropper-
spec:
  entrypoint: build-dropper
  serviceAccountName: waylon
  volumeClaimTemplates:
    - metadata:
        name: buildah-cache
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi # Adjust based on your cache size requirements
  templates:
    - name: build-dropper
      inputs:
        artifacts:
          - name: devtainer-source
            path: /src
            git:
              repo: https://github.com/waylonwalker/dropper.git
              revision: "main"
      container:
        image: quay.io/buildah/stable
        securityContext:
          runAsUser: 0
          privileged: true
        env:
          - name: STORAGE_DRIVER
            value: vfs
          - name: STORAGE_ROOT
            value: /cache/buildah
          - name: DOCKER_USERNAME
            valueFrom:
              secretKeyRef:
                name: registry-wayl-one
                key: username
          - name: DOCKER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: registry-wayl-one
                key: password
        command: [sh, -c]
        args:
          - |
            mkdir -p $STORAGE_ROOT
            buildah --storage-driver=$STORAGE_DRIVER --root=$STORAGE_ROOT login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.wayl.one
            buildah --cache-to=registry.wayl.one/dropper \
              --cache-from=registry.wayl.one/dropper \
              --storage-driver=$STORAGE_DRIVER \
              --root=$STORAGE_ROOT \
              bud \
              -f /src/Dockerfile \
              -t registry.wayl.one/dropper:latest \
              /src
            buildah --storage-driver=$STORAGE_DRIVER --root=$STORAGE_ROOT push registry.wayl.one/dropper:latest
        volumeMounts:
          - name: buildah-cache
            mountPath: /cache
