---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-secret
  namespace: cloudflared
spec:
  encryptedData:
    token: AgBwHEsDnAzTG5xtEkiJsHm+HPOBDfQqWoYohJPpQf5g+S5q+UZuEAwOu3+yybxGApoSLFULpLOpngV7FDQV44XiUzMl+vX7ycdqVzeHVgC0MMnZNIoQ3DIy0uJdJqFxjuw/yZSOxk4qfScpH35RF1ZEMfJxNE/e+HrGjD/F1XBOWAlTddn9g3el0FbiUHTCAH82Hk90i0wtBUHv/J2NZRv50xiu5oyPg3PZPuI10gOlegljnkx0QpmlgedK4abzkxlQyddFeJxDRz0SpyX10v7HodXncv4RSW38XEeRjrGxy6eip/b1lvGZpVxiYD13kds/clH1jQ0TbCCOvFi8E/sNBUXRIa/h1lO2PIOwhbrRJCgnkeDTndopOkERjKoRlCFw8S2noPLYD77x0t75Hxkd1OOptRYdPu2Z61BZq6cpmolSRZ7kv16TMmRDVAwlT4eh3Ua6HNlCGc2mHsVC5KH9XM//MXn32/Zy+hHKwsnnbBmJUZaGFuG9NnB72tVMuUv0I6uxzB+mJOR1Dh2iYGpruD+xJKYvzjXyNT8/bWV8fE1EAwB9znSvjny6yxuLzvRGqUy+Pbf1nI/AQT8LQvItFR2r39BuuQ1kbU/uT08BNWedWiy5jML/q8iMVMS9bRGq2EKiie4ZEvTjfYClwM5WVR/T2dr9W3TIz5/482jF8IxmXALnG0VDqgVgMKX8HpFybz59H/e2fUnpOI0ewcGqe6GTDuB8g++460YWGXJiteDMdedQAw9CpD1Xiujl8AQIR7ml0a7WCP1cViQyD7cDY3DfRzb8kud1BH5t34K20RAzm7KgA/I1HD8lXS6PHe/te4NCsAod0gKUGGXZkyK02ae1hx2hfSt3594YlO0oEuu0NTZIwTfissP+EViZmDPBA+AEra7MJgBe7BdPDVKgvMFTIab2E/TmgXlpbLPRyAH3J8Vwc0TSHKg23qQ5c3R91HD3iTaWXbp+4muFBNw6RJEqdNamFWogMJU2EFWPVEwcI2Fcs0djt9dqt281P+EH4MpFKh61w/kf32/DQS396q5/kkU=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-secret
      namespace: cloudflared
