apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudflared
  name: cloudflared-deployment
  namespace: cloudflared
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: cloudflared
  template:
    metadata:
      creationTimestamp: null
      labels:
        pod: cloudflared
    spec:
      containers:
        - command:
            - cloudflared
            - tunnel
            - --no-autoupdate
            - --metrics
            - 0.0.0.0:2000
            - run
          args:
            - --credentials-file
            - /etc/cloudflared/token.txt
          # args:
          #   - --token
          #   - "$(CLOUDFLARED_TOKEN)"
          image: cloudflare/cloudflared:latest
          name: cloudflared
          volumeMounts:
            - name: cloudflared-token
              mountPath: /etc/cloudflared
              readOnly: true
          env:
            - name: CLOUDFLARED_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflared-secret
                  key: token
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: cloudflared-token
          secret:
            secretName: cloudflared-token-file
