---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-secret
  namespace: cloudflared
spec:
  encryptedData:
    token: AgA93yx1k62SPK55BQ6evoIXtUFd0mPf9mWBtsibT2x9AKvgqMIDxIo5+XANR40JW7rO5jXeD1ic9K2IITFN/rPmno6GoLFnh/q/4zel89lW0hVzvHEkt110jHrm3QKJ4ZiteQXkOTOBFjKJPRGs8/QsK0tVTlL6fwj8k4gajELBvk1eOzxAGirSvHtczgNBEHAKuRGVYpPmJZ549ArpKMr3KyoGTHHvB21eSGASW0F/vp4n5FYCHABhIYeURgw+lVSpxKQ1STjTb7Xdyj4Wh7HzJyt5yBOKVAzH9l4hEbLBnMdlTtW3hUBuM/9yIVRFUanncGEX98W/G3J5bEaVVhs/CyD8iMebTkzXsSKH3rJHZsT1w4Onl1JKNOzjj4CkmY0wCmFo4Te60KbE+RrwrUsvEf73SqssKS3PVdKnZkYYQJuFCtwPxtEBbuAWWAWLk0nRJQSdNtFrtfF6MFDgJ/WpNCShzKrq05U1AlRlP8rA0pTVW2HOTWmMugyBo5RKSWOzObgER7KxW2w9J0VAB3gd6WMlDG83qvdmjOcZ7vu9OsVTcK2bc4jgYdTKdhqLgT1/GhleEkB93yKed0IhZI40rceBmDSofQXib57y69BWF/vxoCssGWZUSHITlhuv3UlSiTIsRjRIfpkJ0T8uPttN3eShlLWazE9tfMMmxI3kik9GSOCMx+xKpA4f4lg8xepiy8exLKm5fv9jDpab39u9P4/zmNaHuVSaFqzQBFMv/G27ZSo3ssARSUR/I2UsnSPGHWAJrTKLz0jvDmE0xhjYzKtIbGU8l7ZNEP5OPSmhxJRPe3QUWExYQpPoE0vHxehYjCSRWqfGkiqM43m4+8fRN9wWmyJ+PNILRZsihJlcTJ5PaVANCkp6Uke2zKFXFEXHI/IG9Qbd7iqVvSv4j3q/AcCWv+kWq/c3sRTirbZiKiigpua/+vsQDA==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-secret
      namespace: cloudflared
