apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: reader
  namespace: reader
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: reader-cronjob
  namespace: reader
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 6
  failedJobsHistoryLimit: 6
  jobTemplate:
    spec:
      template:
        tolerations:
          - key: "performance"
            operator: "Equal"
            value: "low"
            effect: "NoSchedule"
        nodeSelector:
          kubernetes.io/hostname: falcon-fx6860
        spec:
          containers:
            - name: reader-container
              image: registry.wayl.one/reader-waylonwalker-com:0.2.8
              env:
                - name: CLOUDFLARE_API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: reader-secret
                      key: cloudflare-secret
          imagePullSecrets:
            - name: regcred
          restartPolicy: OnFailure
