---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: reader
  namespace: reader
spec:
  encryptedData:
    cloudflare-secret: AgBOxxunw4M++IdBYZ8bk1urrPNXY43La2wsRCVFG/K4m3jzG0+gRkshJo4WYIEyUJj8XJ0rgsdlYVla0N0TlYZflQge/9lVSHpqdSdDJU+bfL+kOTvx3rcrLV1vTwLEh/7L3RRo33k++mGsh2V8iOUkwKdlm29X/24wvGXOMY1q0b+jyxHHgUPA13Fb8jLR3daqtnjSjYZXwmnJmW9dDAf+WBg/MnCIES4egkSU0sT5zDNuSLwCxL337lnrZb+sYLeMUui6rYqEGSRcFgl6IA454vBF8tQy1JuDw17ff3pUMdsqCOivpIqQYSSeRvdE9FKFfyF8avua9jelp7hc010IhAKvNqa+lqFzQOZggGYBmfdCKfM3laBrFomy8+r9StZb5yr63OVFWds2yMg9hZ2+FQ8gcxzwWVwz8mYxPH2FJYgBb0bdgrsQ3nXd1mgvKJLL9qkxSRoN5Dwf4rBk3PaZhV5B7BPJRu2PsddHR3nvLsu4zlZ0Lu8DOyQY89YorRNWqkWA6PEy68MCziM8c9/RhZyIdiSoqrDf8ocURH7j4a6zlFoXz5QkZK1JR0589Lut0qRcpZWlF0p9ozFdoLfAUijcMl2oyTYo3QrKIZ9WacLvR1gcHMnCXtEMLeiO0ioBfwmhH7FHhSXw/5lzNR++8NESsZhwzWvi7/Bz2NdRIfStEi+mDj6C7cLKWvgLzYoRLW+oPOuqANLgGwdEC2g1mVamaQ6PRQbCKWE8MdyI+gaL2pif5osD
  template:
    metadata:
      creationTimestamp: null
      name: reader
      namespace: reader
