---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: reader-secret
  namespace: reader
spec:
  encryptedData:
    cloudflare-secret: AgBu2avDYUbdvN5jLOjatOdTs0aw47wcus6CknR7t9BWPpOK3Cbu98bR9hPcdAJDp7nJCfXFpBfXEVo7NEZAGIIt+HaBWkhZMQEfMbnNekNFCoXbNmZ6RWPiaGSIvyicuvMfOb33GzHh9GiVct9UC//3Lxs7rFPc6kzwnrOm4ujytAdzLbwZNCHPN7N08syS97mMU992DjHDFC0krDgGijapIJNzg/wZeGzfDUk9gOByrkbYgJzPkUE3sgpSpTDw38INHKjN3Nn1MauGIbxh/1rrE32hORvxJLcJ5nLGgSLqE6BHmbDXHj46W7hQnBIjTACxLP5SJuJIvvSNhzMWES0iE/5EFX835zhdRK46PiDA/6OFmohQFM+0w0Vq97sFfJprCeJ53SFcszXtdBYKyWoHmaGyadaiK8ypmfHq4wQJuvZ6jgADMkdVIb10heoKr/L0bi6qL2CIplVYn2eIDVbpSEBL4CdH1XJfb5Ov1oe/Gwds9qaEeuY3qYCEw45Kja5WcHbFMJm9JzA7/OshCdb7+cgCeRvg7sr3MRFOTeJflANao9dOO9Vy2nY30equwnKmWnalMYx29v529xr0N9EP6uUAjzNzRIyQZf0mcrRwH/LkP6hWiwHIE6oxCb6nTAzCU3iBUG0TBZWJXEFG+B54Wa13yI8QLNByJfziNz3as6ew0etALIan8zCu0PrgRoPo+D++qL+NHUuzprMD383BEYVrYzdc8ra/n6jB6QsvKSbhPGCvupyF
  template:
    metadata:
      creationTimestamp: null
      name: reader-secret
      namespace: reader
