---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: reader
spec:
  encryptedData:
    cloudflare-secret: AgAVQHhSgtzhevHg/ciVcfECW8fcnQKEhxnZb6m0XzYLNRciLOkLFwfelf3c+pa9aD1NvAZrPiuEVQJQTgfrA0YreY6KMx45nsp1AjEih+hsT7FZ0RFNLd3Def97mjnz8ysal2EijMq0c9V0WT5IgU/UpE197Tab9oWbJBuO95jT4T+XA3Bal2IqhWJ6a5yBNVxB34AVGIxoMVgUmbqPwWYAy2xMMDpYxJiBgnE4i77BogMbL+tlF/z/sK5ldfnsK+6/5XE96ln0kxVVXEi9Ul8azHQHHpQcHtnyNff2OrRhoGFbC2a7OZbhVFxW8yTEcG2Q4Xa1T0jBJCC6qkS+NVJUmnMzGlSulYY+FJjsCoQWjhRdI2xNwCnTXogaOLPdjH7R1i6V94J+geDyU4WPN71PiVUdtc6E4ZlCQ5f7L7I/zBgHdWsyMT+kpnB+7Np9W0ZbuP6rfkVMVH3p492148/4qJYwQfqY6lp8q3AzzGwMfsnmjfkGMniqyrfL+PfzVpERjgYKLrO9lq8eDsQH0ewvOwsrsZ3b2Wev6X26EDdS88B72yrFN1akv9mYSTQ69NxHsYLeaG5lmxh5PU3uXBJS0EiC5QUgGJ++6VCDqdCXSdkVGfTdwcuMzaOTeWObuEIvz6xMzu4F0g1VG5mycDq9WalsQZ+66mCte8NZg4LGadGwlTgdeKq2Z8uaNsAmoTiK2J7P7pfWLAZvJno3EdN5Kai2oGeMt5yyhplZuIrijMh1VQM1STNX
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: reader
