apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflared
resources:
  - cloudflared.yaml
  - cloudflared-sealed-secret.yaml
  - cleanup.yaml
configMapGenerator:
  - name: cloudflared-pod-cleanup
    files:
      - pod_cleanup.py
