---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --namespace netboot -o deployment.yaml
    kompose.service.expose: netboot.wayl.one
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: netbootxyz
  name: netbootxyz
  namespace: netboot
spec:
  ports:
    - name: "3333"
      port: 3333
      targetPort: 3000
    - name: "69"
      port: 69
      protocol: UDP
      targetPort: 69
  selector:
    io.kompose.service: netbootxyz
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: netboot
  namespace: netboot
spec: {}
status: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --namespace netboot -o deployment.yaml
    kompose.service.expose: netboot.wayl.one
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: netbootxyz
  name: netbootxyz
  namespace: netboot
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: netbootxyz
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --namespace netboot -o deployment.yaml
        kompose.service.expose: netboot.wayl.one
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/netboot-default: "true"
        io.kompose.service: netbootxyz
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Etc/UTC
          image: lscr.io/linuxserver/netbootxyz:latest
          name: netbootxyz
          ports:
            - containerPort: 3000
              hostPort: 3333
              protocol: TCP
            - containerPort: 69
              hostPort: 69
              protocol: UDP
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /assets
              name: assets
      restartPolicy: Always
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
        - name: assets
          persistentVolumeClaim:
            claimName: assets
status: {}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kompose.cmd: kompose convert --namespace netboot -o deployment.yaml
    kompose.service.expose: netboot.wayl.one
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: netbootxyz
  name: netbootxyz
  namespace: netboot
spec:
  rules:
    - host: netboot.wayl.one
      http:
        paths:
          - backend:
              service:
                name: netbootxyz
                port:
                  number: 3333
            path: /
            pathType: Prefix
status:
  loadBalancer: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: config
  name: config
  namespace: netboot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: assets
  name: assets
  namespace: netboot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

