---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: shots
spec:
  encryptedData:
    .dockerconfigjson: AgA2pkL1pl6jXecGm5Ix5AtGAxuAZod3fDxbYwDTHqt3T2KqOUL0atHysZc/53RcMsIgzgE19e3/jI5FB1w6ZzKo1GTMYGafCWokuSZZKWNNW5Lx3X353u0mBLnwXvB64aZyyVjeFFW7JeDMIaigTxPpg6BKYgmulJ/PS+W1yC/KDRmR0NmbCMwv6CVwcdPXvZezxrwvCjV/YuW0cottGbH2PF8Wv5KCKVdDjyBE+gQdjLzm9cgfg5nB5k2CubT78hU/VsAxC1rU4vs2Nc5ptxz4kK6e07hwvT5yuMdBHAiai0O6YL+b/CZim72oFQ/SDP1GxaCRMEvI4IxWmj5Z4np2vdmgko7EFQvfEZi4+WSH88XAYGlpLFCobdplQxHrDCiOnajbdMEUdlzvGBaM64+RbMxdYntxRWF4BR3FV0yVLGAsj43v9IGA4yLwOTRU42SsPsFBpoiupWXujEP5LVmpBRX8V7FN3xhDX6gpVhnuiodDooJKF716haw7i+J8E7iR84K3WPA6RYZ11+6eyOLFuoT1navgkKdvJiiMFj4FUbBQx/5AFYIIYB8KC/M0OK1HY0wYRlHiaPiDP0JBumm4y0hYYc34JBebB5ppFwkFGxqWt6vQAhY5CCE+Ne66heT4McuvzXYd6amg1He8AGEIE7UjHLYLea1oJp2g+wX3143QHU5oyI35SPdY1i7GDpabQRCMMXww117VYKHppCSy0pUqzJJb8mZuSIvecWcsXFHVk4c/L4rMrbQaIy0KZ3iXirLzohdv7XvPaJlYWFv+qiXgOfJzh80pvuMfWGlMs2xZB1OLSqtvcHczwTf2cqpmeaaURlgNsA==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: shots
    type: kubernetes.io/dockerconfigjson
