---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-shots
  namespace: shots
spec:
  encryptedData:
    ACCESS_KEY: AgCnzZzcU/gMNIpZ/K4CejdULPZNecjcJFLayOYRjO67kULErQZlSGuEeZtZmC3QmtQWUBGnXTZKQiQYQEU/FFzjyUpqLFkEgbFNzXf+ON6bRblngDXp5+O2Xj8+/+6uR9lGEzFS0ffI62yn5b7tInmrMYlIEJE/QTwLrMqNBpJoi3/xLc7HQHvyxC8tXXj+XCk/cDWdu3Wtzsf+PyRTlOIm3LuheCG3/qwEOwbdrXJqrjHuWEGI8tTn66E5co4lQfJ10vy00nbsFLePuv9oUAkVYd/57Rf5WVqQG1nRHctcs/IVx2Vx/wUOBHRqUGboE04zLLoIW/LDcWhOLE8mG10ohNxwDEQprSzmsJ/Fdo1rBp9iu6/rJErdoxgZT4U7uxNw/LqxDgrLJVYq25e6lBDx3DBOzgNGpzUQ2rlG+5Dz16L/7BQOGVnrdI6O+a9G9F6MgRhO2lp+vrEKLufNMN/iITtW5li65V10SBlWrJq94PFLc5ffqxHkhR3Y6IOzfvf7zzHcunwO43qQN4XefStbEdt+5lK/sCVeUEmflBs1ceu1f55dL+D4DgctDCAoZpqnxTloyarOK1y0Baz+MoJHDmbIJH/CczHI2YWkl1Y5QZWZ4tyipMyWbXV/prE6jUDMpuSol3Nvp7VqyypDdgWkINVZoIwK7hIPIYME4VdS/Yg3yvO+nZk8u/oPGfM7kSJJ8KMaYhriZWTe/zPXJAs=
    SECRET_KEY: AgBJmbhvCDbpU3/+f+fAo4Pv6w9BVnKY3JTxD2YuUF9s/a62wYeXpnctlJ0I1+/zppz/8XQqCoyKuMz7A4AFfzibLeFcMiQBzmdSPv2bJjjFuQxbj9Ztg1BPIAN0UT6JoFYj+TB6Bpmt/1ofuL7A4rCGL4x67QEK4qm5huWj8tkIB0lMBQlunAwU6Sgn6QS85+SyRwh36yS9dfx52zuNm2ZHQHzmVe4u2R6IZGxCbLuvnptT6K7mbTHKtmaaiAlsPtjbg7LqHHLCeqPgdYYOvLRgrs2hQ+oGEiMs0LAaGRxQFk/zSL6vRlECMI4zcpWrjC/C4PO1sAfpRbW6shPZhtbaHmdj2pvMJKIeT0mcQXkullVjKj9UYJt0UDFv3rKJ17N3HxhB9VwhvklRO+Op/d7zYkGA2595vrXcoVUYvfULt86AkNF06YBqaqX8Kfh7twPBn2AyR2M1ePKHkj0CWGDHzfRD50vTrz+XVU0i7zZDpX3CS7TEB+KeObrnk53y5DQ7/HSMYXcIkAoXR71HI0d4CFuPvbWfKyYmo/PX8+JPbkjDi/rdzJ2wVwM0QkckKdu3KB59h5T4Ip+TBqyX9LkAa6wxV3UMPIz40cZ9mpq0v7Bp1nCfK8CsKljBHh5WbYtvDpwa/Wu6tLXmSDhUd9ih5MoS9tYBMFjqHyaLZsm780jy/WBVzHYDYryueDyZIy68GKRHtOp9Wg7tNrNIoy+oYz1mm9eueKtQ/Vm7Fco=
  template:
    metadata:
      creationTimestamp: null
      name: minio-shots
      namespace: shots
