---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shots-secret
  namespace: shot
spec:
  encryptedData:
    ACCESS_KEY: AgAVB3HtI9EhfMa+l5NY3VeEp9HJ5o1vBD2cAMaIBEmdCkNlHMo/utfIlesfA+oIJz66YTltoBXYg9Iyc1g3qKCr3p38MwAcmqpYcP/Pvt9AIGz4lAi6jvO6bxm/u51je00TDptxqWPsukzgUqNByPD455+nqE7dPjxHKcKaVpT/MqTs5WZCbbpHJd+Ifv6P5TcXEPUeQZbaliQJRRVrt66OPyTHrsH50BWlN0wZSNqrYozkIOarqNgoYxP1rJ30lOr7UzI605gtiAVEtHp3DDmDJTkZJU8dWcwvAiEhq1JwoaOgFBZyjemfXQ00rgwxOCju5N1fZz0Tl44QibZqxuKHi0/mgvol3Z+I4p7ItSH2bh1x1FBBBb5g3+quOkAypvePwSFUNyDg6ZfY/4Op1puiaBbFRZ+j0NCfizfwwlISycCCRrjoi0w46Zqq4D8TudxuiHVDXZcppblWLCzhylm23T7esE8WNPfzWhvLt8YOYSKzNw5EKxUkiE4frikvezjSd5z8so2cN1VjOAJWc7vvZZJt0jMto2c87zqNNegbz9QT4Lpp6W94CiDoeoKXvpVF8EFo03YZbMpp2QHUlmUb96Oy6GQSGXI99zXINGPDUnl4ln4KIvlMCUooQk2dXrCkTKth75wK2W1H0zPXHtb3qpQbNkmdnVcDPaLgt47HS6qpNAx7K5z66YFG5zLTVemT1pZmtrumKtcvHJZiKQxmFmaaedM=
    SECRET_KEY: AgAnZ3yg1UWSjtpXJMYkAlC6CL2smYCCandqczQFcw1cwEiA1KcHH5/Mvd1B02vlJENerhGYXJdSpB9VjhjuPWQBHnbS3dWdboPNzzInsNs/R2fegzgVtN7G7lVPQkB1jjrElEKJwlygeAp5p3srC92YRsU+9L3g2I9hz/BtwVPp/wxpRwCWOG9e0draEgNb5w9apacVpc4emkKc+bz1TtMmv6odzWYLipiyya3f0Hjy4S2/PR0OOW8LdReSNHuhix7hNYMFZUM4+N3bkIG38LTCsZeNx4FSI9Poa+9tXKPJ529I01creAPcfytPF5F9//i77ld4YeCSD5qJoEgscPtCTlOIHS26QThlBNY16u8lE/y28Yd+MujUad+FbFLhHszC8ttT9vbP2di15aJp6GPxc2Qo8nHwtDBZCcq5tWPdU4qgrvGOk7anb+Fn3GcseOEhXfFmQOPaFHBXusRgqhap5Bd9wva4fqwWr8BCItEjr9E5VdA1CUdhjRVyEuIPJaihGkbhsEr+ZICB10bwM5wLhLx6uGNrL+axXR4dHG5vTKWwUcA6wC3TTAr7DCJ3uLYKxR1yzefHy0feniQpQC3dBHASHJ66MTRL6cuIcj319p/2Shi7nP4K5JY8uL07evTFphe1r8MsKQ8BMQOKVdi0IQh2vYKEtq01XoiXfK/RZf4quLoQwX+4ifHR7bLyHilw/Yxz091ajTnTc25l0I6/rzu3J4G3ilxoU3OcbZjnOQ52VxmTkPFuow==
  template:
    metadata:
      creationTimestamp: null
      name: shots-secret
      namespace: shot
