---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shots-secret
  namespace: shot
spec:
  encryptedData:
    ACCESS_KEY: AgBxx51bCmmed7mZGF+w208UYjluHfvdV2qDS+uXcEXh05GUDNLCBQ4undCWIcwboYL37PJrFFLJtYP78k/IcQB7HZofVstcRPdFLd/YMBJeRuSXUxm7Us0uR5R7Yc8LfGKo/JfYMKLxwjU9NONfxkEXMW5MRI22P5ym1yCIVoUO/8bKq9i2oBFzN8D+OQvqUffInl7+G2r5e9PyeoSkk3tQ4XkWqSYnWru4G1D9/RaDxZFrjJ8MZgAlXSavVrvrpqCANBCPE1q0o/jNyLCo4H2dmqHAMkAxbGgUa+KLGErKTQvd39vaaIxeVAJUjaXWNvbujMEGeYvcjZRBH44RmVABPfn9n7zs6oKXWYKi/MX/2FK1QhGz53fllSzpR4R5dnwfDOxESp/XTfbWKyt9voYO/cC4fRvtcoLvIFSvw3yiKiMsurnbq2twUH7LApNDSKN5CSX2jOkcOgpPxin+CpL4UGTvt4KBRHi5qlODfUzMeJ2+lh2lHRprHs2+7R0x10jDSTzQCCpaKo4eStb25y6VCke4gbxkZtPoIA8njL9XoMSFKUsiLQZB5XRDH7hQcCNCjhRDv9UJHLqUZohXtoNyK8lN3EM31CDtdCPIjI9fWidv58ZCXFBjD3Rg0z32YCcsg1IIVi5rUk49thaJ2cZjFqe3VCuMpfpu30+4XKTdE5dQN9ZSefjgp3UfvEdVC3m5+2AFzGO/Yuqv6pIhv0lFzFM6RYo=
    SECRET_KEY: AgANLRAIJ6dl5cqWFKZDWjRMB7a2p5/0ljccGAToPkoP1x3CIaj0iK6lfzNpfFd3lhtjCYIx7QdSebQJeps+NxbhoEb36mMUK1c6znKSNRae+GVepDDwVFjJrtMcsHiOrngfW/UrbKCLwQ2XsAgDkt5c3JnhfYJyAUFNQ27Vq+/isF44KiDUHd4tnv3D1iCOR5CF/qOnvuVgz0y6PJW+UppbwuwI2wO21ya154s6sKyTjjFS2QBI+Hl78E9IBAtzS/BbN3vDhHhhv4/9lpWcxIUjJywuzgp5nAmbVnNTibQSgOcgMGoWoV104Cize+vsR1WW0LvfJtxgquLHd7lIuPtaWmzemLAmR7l90h58POAqwl/m31kWoVlCa+vnWyRktAi+XaA684ShW/gfvfYHUZybu1dkr05b88qO/H4zS9sRA/4elegSrCCIKCk7nCPH70n6QJieCz5/tdwHXZtsb1uHxeZWDvvr38P3Yy/vkh3BYkbofLmdGXahc9ZAh9mk62aJB6o/sUYpa+dyErCViVwsR3JkZ0LH6KUYGmbFHGANWTD1vvyXDKaO8GDFqx5mzNrjKMQnVv+3UbCLWs5FCLvsM9xiII3EXYsy6QlGQFKJ+Qii3heQcTXwwXjj5h7Vxv4Uw6Tc4nQ75BgqFgsHbq/78n9ztvO/ouj7o1/2pXTHoyIGpUiWWM05QWla+3TWnEEppHGgvGpT1thidS1IW2z+Nx+CEaXWS1isC+1XvO5G3uTGRG+cjdfl+w==
  template:
    metadata:
      creationTimestamp: null
      name: shots-secret
      namespace: shot
