apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: avatars
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/waylonwalker/k8s-basic.git'
    targetRevision: HEAD
    path: helm-chart
    helm:
      values: |
        name: avatars
        image:
          name: avatars
          tag: "0.3.5"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: avatars
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
