apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: excalidraw
  namespace: argocd
spec:
  project: default
  destination:
    namespace: excalidraw
    server: 'https://kubernetes.default.svc'
  source:
    path: excalidraw
    repoURL: 'https://github.com/waylonwalker/homelab-argo'
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
