apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: headlamp
spec:
  project: default
  source:
    repoURL: https://headlamp-k8s.github.io/headlamp/
    chart: headlamp
    targetRevision: v0.27.0
    helm:
      values: |
        ingress:
          # -- Enable ingress controller resource
          enabled: true
          # -- Annotations for Ingress resource
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod

          # -- Ingress class name. replacement for the deprecated "kubernetes.io/ingress.class" annotation
          ingressClassName: ""

          # -- Hostname(s) for the Ingress resource
          # Please refer to https://kubernetes.io/docs/reference/kubernetes-api/service-resources/ingress-v1/#IngressSpec for more information.
          hosts:
            - host: headlamp.wayl.one
              paths:
              - path: /
                type: ImplementationSpecific
  destination:
    server: https://kubernetes.default.svc
    namespace: headlamp
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
