apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-pvcs
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  source:
    repoURL: 'https://github.com/waylonwalker/homelab-argo'
    targetRevision: HEAD
    path: k8s/immich
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
