apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-pages
  namespace: argocd # Namespace where Argo CD is installed.
spec:
  project: default
  source:
    repoURL: 'https://github.com/waylonwalker/k8s-pages.git'
    targetRevision: HEAD # Adjust if you need a specific branch, tag, or commit.
    path: helm-chart # For example, if the chart root is at the repository’s root, use '.'
    helm:
      # Instead of valueFiles, paste the contents of your values file inline here.
      # You can copy the content from:
      # https://github.com/waylonwalker/homelab-argo/blob/HEAD/k8s-pages/values.yaml
      values: |
        # The namespace where all resources will be created.
        namespace: k8s-pages
        # Number of replicas for the deployment.
        replicaCount: 1
        # List of sites to configure.
        bucket: "k8s-pages"
        maxAge: '120960'
        staleWhileRevalidate: '86400'
        sites:
          - name: k8s-pages-dev
            host: wayl.one
            # URL to which the proxy_pass should direct traffic. (Include protocol and path)
            minioURL: "https://minio.wayl.one"
            # The host header to set when proxying.
            minioHost: "minio.wayl.one"
            # Error Page
            errorPage: "/404.html"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mypages # Target namespace where resources will be deployed.
  syncPolicy:
    automated:
      prune: true # Remove resources that are no longer tracked in Git.
      selfHeal: true # Automatically correct any drift from the Git state.
