apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-pages
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/waylonwalker/homelab-argo.git'
    targetRevision: HEAD
    path: k8s-pages
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: k8s-pages
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
