apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: models
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/WaylonWalker/homelab-argo.git
    targetRevision: main
    path: k8s/models
  destination:
    server: https://kubernetes.default.svc
    namespace: models
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
