apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://nextcloud.github.io/helm/
    chart: nextcloud
    targetRevision: 6.6.9
    helm:
      values: |
        cronjob:
          enabled: true
          schedule: "*/5 * * * *"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          annotations:
            helm.sh/hook: post-install,post-upgrade
            helm.sh/hook-weight: "1"
        nextcloud:
          host: nextcloud.wayl.one
          username: admin
          password: changeme
          nodeSelector:
            nextcloud-storage: "true"
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 2Gi
          startupProbe:
            enabled: true
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
            successThreshold: 1
          livenessProbe:
            enabled: true
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            enabled: true
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          persistence:
            enabled: true
            existingClaim: "nextcloud-data"
          podSecurityContext:
            runAsUser: 33
            runAsGroup: 33
            fsGroup: 33
          containerSecurityContext:
            runAsUser: 33
            runAsGroup: 33
          phpConfigs:
            memory-limit.ini: |
              memory_limit = 1G
              upload_max_filesize = 16G
              post_max_size = 16G
              max_execution_time = 3600
              max_input_time = 3600
          configs:
            config.php: |
              <?php
              $CONFIG = array (
                'apps_paths' => array(
                  array(
                    'path'=> '/var/www/html/apps',
                    'url' => '/apps',
                    'writable' => false,
                  ),
                  array(
                    'path'=> '/var/www/html/custom_apps',
                    'url' => '/custom_apps',
                    'writable' => true,
                  ),
                ),
                'config_is_read_only' => true,
                'default_phone_region' => 'US',
                'enable_previews' => true,
                'enabledPreviewProviders' => array(
                  'OC\Preview\Movie',
                  'OC\Preview\Image',
                  'OC\Preview\TXT',
                  'OC\Preview\MarkDown',
                  'OC\Preview\PDF',
                  'OC\Preview\MP3',
                ),
                'preview_max_x' => 2048,
                'preview_max_y' => 2048,
                'preview_max_filesize_image' => 50,
                'preview_max_filesize_movie' => 1024,
                'preview_max_scale_factor' => 8,
                'filelocking.enabled' => true,
                'htaccess.RewriteBase' => '/',
                'integrity.check.disabled' => false,
                'knowledgebaseenabled' => false,
                'logfile' => '/var/www/html/data/nextcloud.log',
                'loglevel' => 2,
                'log_rotate_size' => 104857600,
                'maintenance' => false,
                'theme' => '',
                'default_theme' => 'dark',
                'enforce_theme' => 'dark',
                'trashbin_retention_obligation' => 'auto, 30',
                'upgrade.disable-web' => true,
                'memcache.distributed' => '\OC\Memcache\Redis',
                'memcache.locking' => '\OC\Memcache\Redis',
                'redis' => array(
                  'host' => 'nextcloud-redis',
                  'port' => 6379,
                  'dbindex' => 0,
                  'timeout' => 1.5,
                ),
              );
          extraEnv:
            - name: OVERWRITECLIURL
              value: "https://nextcloud.wayl.one"
            - name: OVERWRITEPROTOCOL
              value: "https"
            - name: OVERWRITEHOST
              value: "nextcloud.wayl.one"
            - name: TRUSTED_PROXIES
              value: "10.0.0.77"
            - name: POSTGRES_HOST
              value: nextcloud-db-rw.nextcloud.svc.cluster.local
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: nextcloud
            - name: PHP_MEMORY_LIMIT
              value: "1G"
            - name: PHP_UPLOAD_LIMIT
              value: "16G"
          existingSecret:
            enabled: false
            usernameKey: nextcloud-username
            passwordKey: nextcloud-password
            tokenKey: ""
            smtpUsernameKey: smtp-username
            smtpPasswordKey: smtp-password
            smtpHostKey: smtp-host
        externalDatabase:
          enabled: true
          type: postgresql
          host: nextcloud-db-rw.nextcloud.svc.cluster.local
          port: 5432
          database: nextcloud
          existingSecret:
            enabled: true
            secretName: nextcloud-extra-secret
            usernameKey: db-user
            passwordKey: db-password
        redis:
          enabled: false
        postgresql:
          enabled: false
        nginx:
          enabled: false
        apache:
          enabled: true
        internalDatabase:
          enabled: false
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            nginx.ingress.kubernetes.io/proxy-body-size: 16G
          ingressClassName: "nginx"
          tls:
            - secretName: nextcloud-tls
              hosts:
                - nextcloud.wayl.one
          hosts:
            - host: nextcloud.wayl.one
              paths:
              - path: /
                type: ImplementationSpecific
          initScripts:
            preview-generator.sh: |
              #!/bin/bash
              echo "Installing previewgenerator app..."
              su -s /bin/bash -c 'php occ app:install previewgenerator' "www-data"
              echo "Installing facerecognition app..."
              sudo -u www-data php occ app:install facerecognition || true
              echo "Installing recognize app..."
              sudo -u www-data php occ app:install recognize || true
              echo "Installing workflow_script app..."
              sudo -u www-data php occ app:install workflow_script || true

              echo "Listing all installed apps..."
              su -s /bin/bash -c 'php occ app:list --shipped false' "www-data"
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
