apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opengraph
  namespace: argocd # Namespace where Argo CD is installed
spec:
  project: default
  source:
    repoURL: 'https://github.com/waylonwalker/k8s-basic.git'
    targetRevision: HEAD
    path: helm-chart
    helm:
      # valueFiles:
      #   - values.yaml
      # Optional: Override values with parameters
      values: |
        name: opengraph
        image:
          name: opengraph
          tag: "0.2.2"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: opengraph # Target namespace for deployment
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
