apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: social-scheduler
  namespace: argocd
spec:
  project: default
  destination:
    namespace: social-scheduler
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s/social-scheduler
    repoURL: 'https://github.com/waylonwalker/homelab-argo'
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
