apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: whoami=traefik/whoami
    argocd-image-updater.argoproj.io/whoami.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git:create-pr
    argocd-image-updater.argoproj.io/git-branch: image-updates
    argocd-image-updater.argoproj.io/git-base-branch: main
spec:
  project: default
  destination:
    namespace: wayl-one
    server: 'https://kubernetes.default.svc'
  source:
    path: whoami
    repoURL: 'https://github.com/waylonwalker/homelab-argo'
    targetRevision: HEAD
    # plugin:
    #   name: kustomize
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
