---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aylawalker-secret
  namespace: aylawalker
spec:
  encryptedData:
    PASSWORD: AgBho8lAaD19kGLZm5GNbBBBKErJiNUsLzE+dsqcQejt0D5hN/aqnkyvShxFcDtAWSPLu+pDfPrUN/a7ypn8o8wayyAsC6ZjNoHOm0N8uXGFahuDdGqxZvkYecHlrJEj76D26QEVt6YxdWsBRo9Cgss8hys6vH8LvhKaT3kmns1ly5vQVnvNTVJTnU0h2++uBmXQHqhX5d+OG30IU43uZzyky4pKYxiFgoXJ1aLLN6KLkle4Pb53CKvt1Oc0ygRIzXMNlKKCLRGWMo4u0T9d9nS6y42pV3EhyDZO8p+xQcPw0TG9f4LZYBMCsMwvZ1F4pl7CGEfjVcUHKLDIaUx4Td4iwBiS4/e4IX6CuwnQWQQ7hSt9s+clgQYL9WY+K+tKInmTzDrJZfokWjXs4lCrsbiztL3u0X49ICE8I9Xhq8hxjboH8v7LgrSp5dN7iC7yPyMlCUVs/yw6IHu+dQwu1n6SSeEbM+vxA5iN4rKXWufHbLQznLbeNjen7orAMtl3beF+O2jsIwR1KhNzZVajRU8YLLEvGtNhQIeH268PfLgi7h1I9N2CCVs+g6nMQ+AZHfmlX/K17hVb0nmlzOjyhG8Vwp9d4kbI7sby2HZ9+eC8qaScn5+Nxj+6zvjTV47vkFAcUjnt0ZJMk7s1pOwWcdg/YERimmoXH55JKh4t1ma9PWCkV3So37uKK9xaKN1Y9zYW8u6F0UTAzVg=
  template:
    metadata:
      creationTimestamp: null
      name: aylawalker-secret
      namespace: aylawalker
