---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aylawalker-secret
  namespace: aylawalker
spec:
  encryptedData:
    PASSWORD: AgCnjyOXCRYD6XTH6MLaHreA+R9KEeoQxOiIQTmrN17P1f0AXbjjQ+sRL4iNDe0qKpffWxXFozH77daszSQCMsQrhf7tfFGb7Np1xEOnY/JSmkbbP007/UdM0i2tg7wyTobzi4nAo5UWMpy9/YXizZt6VG0uUPF8rZWcrSbAJTheSa9XbYVZPUHsBC+FYy8LEXNUYdaTBlRcoLNsXc0ShOv/jNIsy260bvNU1rtyQ+z8qPKzKkI6c3pLZuEWTmkCr9o5GXY/nDnq/yE+FbwBQTRMbefsKI+UeO3sXzWJTXwVdIKg4w6ZZVx7wwpDIEpHF+daur8De7XK385DzpMwg6a4gHFh1XhbtvRaBa7YqZFU327ZGybmhaxzZ3LTWDvUSHzlgBumqF9Fp1NxlwV9W1IU8kr5FQBSTSUStSnCbYD03YU8LNKTqUFtm+tg/c54ry7Fl5Z1Ym8RtrawmFWCY+1mIySQG7ctx6nO9QjZ/AucibcHAIANGRf0ZSaJ99NUW0PfbRzwkT2XBdc1cpFKEvOBqYZZXtOTuz4kkAnZKIGvh4Wpyro8pmo+8KiKYoZZN55hRRFuFJKWEAMuuDLI9gGwcIiq9mCf6VBigLUGIxNmIE3jysJDQXJ3Mfi/TFMq9efnrD7A5z2N5IO5DtNh8oyWjFl48txCCSZgxZ+I19C1mx/rIQ6/22mEDYYUWW+bin3GM8CnX4GFtQ==
  template:
    metadata:
      creationTimestamp: null
      name: aylawalker-secret
      namespace: aylawalker
