
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argo
    server: 'https://kubernetes.default.svc'
  source:
    path: argo
    repoURL: 'https://github.com/waylonwalker/homelab-argo'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: installer
  namespace: argocd
spec:
  project: default
  destination:
    namespace: installer
    server: 'https://kubernetes.default.svc'
  source:
    path: installer
    repoURL: 'https://github.com/waylonwalker/homelab-argo'
    targetRevision: HEAD

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: librespeed
  namespace: argocd
spec:
  project: default
  destination:
    namespace: librespeed
    server: 'https://kubernetes.default.svc'
  source:
    path: librespeed
    repoURL: 'https://github.com/waylonwalker/homelab-argo'
    targetRevision: HEAD

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: play-outside
  namespace: argocd
spec:
  project: default
  destination:
    namespace: play-outside
    server: 'https://kubernetes.default.svc'
  source:
    path: play-outside
    repoURL: 'https://github.com/waylonwalker/homelab-argo'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab
  namespace: argocd
spec:
  project: default
  destination:
    namespace: homelab
    server: 'https://kubernetes.default.svc'
  source:
    path: active
    repoURL: 'https://github.com/waylonwalker/homelab-argo'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
