apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: installer
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: installer
    name: in-cluster
  source:
    path: installer
    repoURL: 'https://github.com/waylonwalker/homelab-argo'
    targetRevision: HEAD
