apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argo
    server: 'https://kubernetes.default.svc'
  source:
    path: argo
    repoURL: 'https://github.com/waylonwalker/homelab-argo'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: installer
  namespace: argocd
spec:
  project: default
  destination:
    namespace: installer
    server: 'https://kubernetes.default.svc'
  source:
    path: installer
    repoURL: 'https://github.com/waylonwalker/homelab-argo'
    targetRevision: HEAD

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: librespeed
  namespace: argocd
spec:
  project: default
  destination:
    namespace: librespeed
    server: 'https://kubernetes.default.svc'
  source:
    path: librespeed
    repoURL: 'https://github.com/waylonwalker/homelab-argo'
    targetRevision: HEAD

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: play-outside
  namespace: argocd
spec:
  project: default
  destination:
    namespace: play-outside
    server: 'https://kubernetes.default.svc'
  source:
    path: play-outside
    repoURL: 'https://github.com/waylonwalker/homelab-argo'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab
  namespace: argocd
spec:
  project: default
  destination:
    namespace: homelab
    server: 'https://kubernetes.default.svc'
  source:
    path: active
    repoURL: 'https://github.com/waylonwalker/homelab-argo'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: excalidraw
  namespace: argocd
spec:
  project: default
  destination:
    namespace: excalidraw
    server: 'https://kubernetes.default.svc'
  source:
    path: excalidraw
    repoURL: 'https://github.com/waylonwalker/homelab-argo'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home
  namespace: argocd
spec:
  project: default
  destination:
    namespace: wayl-one
    server: 'https://kubernetes.default.svc'
  source:
    path: home
    repoURL: 'https://github.com/waylonwalker/homelab-argo'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: code-server
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: code-server
  source:
    path: code-server
    repoURL: 'https://github.com/waylonwalker/homelab-argo'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyter
  namespace: argocd
spec:
  project: default
  destination:
    namespace: jupyter
    server: 'https://kubernetes.default.svc'
  source:
    path: jupyter
    repoURL: 'https://github.com/waylonwalker/homelab-argo'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: status
  namespace: argocd
spec:
  project: default
  destination:
    namespace: status
    server: 'https://kubernetes.default.svc'
  source:
    path: status
    repoURL: 'https://github.com/waylonwalker/homelab-argo'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ntfy
  namespace: argocd
spec:
  project: default
  destination:
    namespace: ntfy
    server: 'https://kubernetes.default.svc'
  source:
    path: ntfy
    repoURL: 'https://github.com/waylonwalker/homelab-argo'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  destination:
    namespace: minio
    server: 'https://kubernetes.default.svc'
  source:
    path: minio
    repoURL: 'https://github.com/waylonwalker/homelab-argo'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry
  namespace: argocd
spec:
  project: default
  destination:
    namespace: registry
    server: 'https://kubernetes.default.svc'
  source:
    path: registry
    repoURL: 'https://github.com/waylonwalker/homelab-argo'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
