apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    helm:
      values: |
        global:
          domain: argocd.wayl.one
          networkPolicy:
            create: false
        configs:
          cm:
            application.resourceTrackingMethod: annotation
            resource.compareoptions: "ignoreResourceStatusField: all"
          params:
            "server.insecure": true
        server:
          ingress:
            enabled: true
        controller:
          nodeSelector:
            kubernetes.io/hostname: falcon1
        repoServer:
          nodeSelector:
            kubernetes.io/hostname: falcon1
          networkPolicy:
            create: false
          extraArgs:
            - --address
            - 0.0.0.0
    targetRevision: 10.4.2
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
