apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argocd-image-updater
    targetRevision: 0.12.0 # You can set this to a specific version if needed
    helm:
      values: |
        config:
          gitCommitUser: "argocd-image-updater"
          gitCommitEmail: "argocd-image-updater@users.noreply.github.com"
          allowTags: "regexp:^v[0-9]+\\.[0-9]+\\.[0-9]+$"
          registries:
            - name: Docker Hub
              prefix: docker.io
              api_url: https://registry-1.docker.io
              credentials: secret:argocd/git-creds#token
          applications:
            - name: "*"
              allow_tags: "regexp:^v[0-9]+\\.[0-9]+\\.[0-9]+$"
              update_strategy: latest
        authSecrets:
          git:
            git-creds:
              name: git-creds
              key: token
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
