apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-token
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s/argo-token
    repoURL: 'https://github.com/waylonwalker/homelab-argo'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
