apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: basic-auth
  namespace: argocd
spec:
  project: default
  destination:
    namespace: basic-auth
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s/basic-auth
    repoURL: 'https://github.com/waylonwalker/homelab-argo'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
