apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clustersecret
  namespace: argocd # This is where ArgoCD is installed
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: clustersecret # target namespace for the release
  source:
    repoURL: "https://charts.clustersecret.com/"
    chart: cluster-secret
    targetRevision: "0.5.2"
    helm:
      releaseName: clustersecret
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
