apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg-operator
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudnative-pg
  source:
    chart: cloudnative-pg
    repoURL: https://charts.cloudnative-pg.io
    targetRevision: 1.25.0
    # path: releases/cnpg-1.25.0.yaml
    # repoURL: https://github.com/cloudnative-pg/cloudnative-pg
    # targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
