apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg-operator
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudnative-pg
  source:
    path: operator-manifest.yaml
    repoURL: https://raw.githubusercontent.com/cloudnative-pg/artifacts/release-1.17/manifests/
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
