apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-longhorn-backup
  namespace: argocd
spec:
  project: default
  destination:
    namespace: minio-longhorn-backup
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s/minio-longhorn-backup
    repoURL: 'https://github.com/waylonwalker/homelab-argo'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
