apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-secrets
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  source:
    path: k8s/observability
    repoURL: https://github.com/waylonwalker/homelab-argo
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
