apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wg-easy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.wireguard.io
    targetRevision: latest
    chart: wg-easy
    helm:
      values: |
        service:
          type: LoadBalancer
        env:
          PUID: "1000"
          PGID: "1000"
          SERVERURL: "vpn.wayl.one"
          SERVERPORT: "51820"
          PEERS: "Thingino1,Thingino2,Thingino3" # Add cameras
        persistence:
          enabled: true
          storageClass: "standard"
          size: "5Gi"
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
