apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: waylon
  namespace: argo-workflows
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - clusterworkflowtemplates
      - clusterworkflowtemplates/finalizers
      - configmaps
      - cronworkflows
      - cronworkflows/finalizers
      - events
      - eventsources
      - persistentvolumeclaims
      - pods
      - pods/exec
      - pods/log
      - secrets
      - sensors
      - serviceaccounts
      - services
      - workfloweventbindings
      - workfloweventbindings/finalizers
      - workflows
      - workflows/finalizers
      - workflowtemplates
      - workflowtemplates/finalizers
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: waylon
  namespace: argo-workflows
imagePullSecrets:
  - name: regcred
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: waylon
  namespace: build
imagePullSecrets:
  - name: regcred
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: waylon
  namespace: argo-workflows
subjects:
  - kind: ServiceAccount
    name: waylon
    namespace: argo-workflows
roleRef:
  kind: Role
  name: waylon
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: waylon-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: waylon
    namespace: argo-workflows
roleRef:
  kind: ClusterRole
  name: argo-events-workflow
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: waylon.service-account-token
  namespace: argo-workflows
  annotations:
    kubernetes.io/service-account.name: waylon
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: waylon
  namespace: build
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - configmaps
      - cronworkflows
      - cronworkflows/finalizers
      - eventbus
      - events
      - eventsources
      - persistentvolumeclaims
      - pods
      - pods/exec
      - pods/log
      - secrets
      - sensors
      - services
      - workfloweventbindings
      - workfloweventbindings/finalizers
      - workflows
      - workflows/finalizers
      - workflowtaskresults
      - workflowtaskresults/finalizers
      - workflowtasksets
      - workflowtasksets/finalizers
      - workflowtemplates
      - workflowtemplates/finalizers
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: waylon
  namespace: build
subjects:
  - kind: ServiceAccount
    name: waylon
    namespace: build
roleRef:
  kind: Role
  name: waylon
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-events-workflow
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - clusterworkflowtemplates
      - clusterworkflowtemplates/finalizers
      - configmaps
      - cronworkflows
      - cronworkflows/finalizers
      - eventbus
      - events
      - eventsources
      - persistentvolumeclaims
      - pods
      - pods/exec
      - pods/log
      - secrets
      - sensors
      - services
      - workfloweventbindings
      - workfloweventbindings/finalizers
      - workflows
      - workflows/finalizers
      - workflowtaskresults
      - workflowtaskresults/finalizers
      - workflowtasksets
      - workflowtasksets/finalizers
      - workflowtemplates
      - workflowtemplates/finalizers
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
