apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: waylon
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
  - nonResourceURLs:
      - "*"
    verbs:
      - "*"
      # - apiGroups: ["argoproj.io"]
      #   resources:
      #     - workflows
      #     - workflows/finalizers
      #     - workfloweventbindings
      #     - workfloweventbindings/finalizers
      #     - workflowtemplates
      #     - workflowtemplates/finalizers
      #     - cronworkflows
      #     - cronworkflows/finalizers
      #     - clusterworkflowtemplates
      #     - clusterworkflowtemplates/finalizers
      #     - workflowtasksets
      #     - workflowtasksets/finalizers
      #     - workflowtaskresults
      #     - workflowtaskresults/finalizers
      #     - workflowartifactgctasks
      #     - workflowartifactgctasks/finalizers
      #   verbs:
      #     - create
      #     - delete
      #     - deletecollection
      #     - get
      #     - list
      #     - patch
      #     - update
      #     - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: waylon
  namespace: argo-workflows
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: waylon
  namespace: argo-workflows
subjects:
  - kind: ServiceAccount
    name: waylon
    namespace: argo-workflows
roleRef:
  kind: Role
  name: waylon
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: waylon-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: waylon
    namespace: argo-workflows
roleRef:
  kind: ClusterRole
  name: argo-workflow
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: waylon.service-account-token
  namespace: argo-workflows
  annotations:
    kubernetes.io/service-account.name: waylon
type: ckubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-admin
  namespace: argo-workflows
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-admin-role
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
  - nonResourceURLs:
      - "*"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-admin-role
subjects:
  - kind: ServiceAccount
    name: argo-admin
    namespace: argo-workflows
