---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: markata-go-encryption
  namespace: go-waylonwalker-com-notes
spec:
  encryptedData:
    MARKATA_GO_ENCRYPTION_KEY_DEFAULT: AgBH9ffPE0plLSDcSpzKkuVvwORv8eRogHdR2b+hIy/Fh4lhjNH1Wpj9qJoIQBhilfdfohh1YA2R17yrRW8GkMiNerAWpiiwSRar+ogpVQZx6tz+YWafw65TPunQZtG5ffa+V/c+mrGaLz3dNkMvmA8TpH4DLOAgSt2B3kb5vRxqr+jbQuq1/UnF7mwXdJMgbqMMN2T2SJOxIs+G06PHRCyJRkvcYaAf/se4UFn5KjaUu4lMbyPX6a4ukCOfC7qBHE3nqrr2uT5I6X6m2H8Zfp1wZonDCvxE5BAXg0DqEzuQVSg4v9bUS28hLUQlB0LIvgfP2k2ef+LARGl4qplPM+BbxIP6wKWkqaXkT4E+X6AjML/GxlrSuV5Vlxw3XntFnhSAFD0XKUSY+wvUQmyo1x4aXHggUpK0mzxHXjxQNu96fgDpc31Em8EJJAEu5U7ToaJXTp+xr0rBnAoSRyX0DZXuA6bTilIXuLle6LvULtroKKoGqJ3sNONM6gDMbTUe5XdhLzMQoO4gRHFzen8JZyxA+l3fXJqhRCyPgT7BgGE95senLt0KxoQX6i1M/aYolvP7HDnHkHUO85VpyhQFbThKuriFqtl+2uwAYyipSWx8ApWlofVodRXfmNdTmRLYT3uARItNyIzJDKCPZgffzwVffkqdmE3lB5rFGeySCLePdZ5a2wtggefOQv/0WeJo4Q4WdQT8Fn2KIcsd8Yq/8FIabjvsdCsKzcl9eGliF7X9kfSWp3m9EOHSefDPRhaurAXVS3ra4Q==
  template:
    metadata:
      name: markata-go-encryption
      namespace: go-waylonwalker-com-notes
