---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: webmention-io
  namespace: go-waylonwalker-com-notes
spec:
  encryptedData:
    WEBMENTION_IO_TOKEN: AgB7N8YgNYiTUrgQkOEyyoOKsQ8ISkKROJtDVNrg67ilUdiSxSG0WSEPIHoZTRXZWaMHuKAhPv1D9d0Fl1XDgm3X+hBvxQLIJkLALvAdEu5VjUoaxKlwhMEkzIq/EXX1UpjnVc2g6U+D/e8HlFw60UYb1uxyR3lyBJcihF/NUfuqoI2cXQZw4EflZYskjqvuavMPKrNboaiXlgzBOZIwfK95HaaWeFj6+FPirtfH0uMJNWmziqj/uMv4geuqbdfPorkuLrQsMMcnYejsc67iE/mouL8qyMpbcbGF72+fIWbB/9iBPhmCV3LLXtsuC+3uMh0OZdJvquyKImsdA2Q8miTPGQOihS+8tSBOexHPzWFHp2AjP9PqVusx88I0PWrVsoMV+z2WyzSltyt1iaAVzpnMj+w+rOZELKVlPXlfMn/dpWFeJhg65jc8TXnZDcz9vt2s89FzW3il4I2zJXuyL1UpliHhjbVSnUG07Yb1Xk6WPhvLx/Wv+dVkP29gd9jPFyKK74Y/cYtX8s9cHGS4McI2EbXXIKcnsCZl22I87dNs7y62YyBe1fsuuy6/WyYnbVCJbR20tJt5/kNC9aPYkJmTTTxcgakhSdVPKhbv7WVR/Dv4J8OVlXqXmVzJc+3JQ09Hdrln0IerZEObSc5llesU8LGUSv6y70dq2z/AC+iK+13Hd2ujxsuczpIRXggyfF2E2q+bWVMoQzDj3NGOqJxkfnOQ3Pzy
  template:
    metadata:
      name: webmention-io
      namespace: go-waylonwalker-com-notes
