apiVersion: v1
kind: ConfigMap
metadata:
  name: site-config
data:
  site: emboss
  namespace: emboss
  host: emboss.waylonwalker.com
  webrootPath: /mnt/main/walkershare/waylon/sites/emboss.waylonwalker.com
