apiVersion: v1
kind: Namespace
metadata:
  name: dev-waylonwalker-com
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-waylonwalker-com-build
  namespace: dev-waylonwalker-com
spec:
  storageClassName: longhorn-backup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-waylonwalker-com-build-hostpath2
  namespace: dev-waylonwalker-com
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: dev-waylonwalker-com-build-hostpath2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-waylonwalker-com-build-hostpath2
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /mnt/vault/nfs/general/pv/dev-waylonwalker-com
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-waylonwalker-com-site
  namespace: dev-waylonwalker-com
spec:
  storageClassName: longhorn-backup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: waylonwalker-com-cronjob
  namespace: dev-waylonwalker-com
spec:
  schedule: "0/10 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 60
  successfulJobsHistoryLimit: 6
  failedJobsHistoryLimit: 6
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: site
              persistentVolumeClaim:
                claimName: dev-waylonwalker-com-site
          containers:
            - name: waylonwalker-com-container
              image: registry.wayl.one/waylonwalker-com:64
              command: ["/bin/bash", "-c"]
              args:
                - |
                  #!/usr/bin/env bash
                  set -euo pipefail

                  ROOT=/site
                  REPO="$ROOT/build/waylonwalker.com"
                  SITE_DIR="$ROOT/site/waylonwalker.com"

                  BRANCH=${BRANCH:-main}
                  URL=${URL:-https://github.com/waylonwalker/waylonwalker.com.git}

                  mkdir -p "$REPO" "$SITE_DIR"

                  git config --global --add safe.directory "$REPO" || true

                  if [ ! -d "$REPO/.git" ]; then
                    echo "Fresh shallow clone into $REPO"
                    rm -rf "$REPO"
                    git clone \
                      --depth=1 \
                      --no-tags \
                      --single-branch \
                      --branch "$BRANCH" \
                      "$URL" \
                      "$REPO"
                  else
                    echo "Updating shallow repo in $REPO"
                    git -C "$REPO" fetch --depth=1 origin "$BRANCH"
                    git -C "$REPO" reset --hard FETCH_HEAD
                    git -C "$REPO" clean -fdx -e markout -e .markata.cache
                  fi

                  cd "$REPO"
                  mkdir -p markout

                  echo "==> Running markata build"
                  time markata build

                  echo "==> Syncing markout to $SITE_DIR"
                  set +e
                  rsync -rlt \
                    --delete \
                    --omit-dir-times \
                    markout/ "$SITE_DIR"/
                  RSYNC_EXIT=$?
                  set -e

                  case "$RSYNC_EXIT" in
                    0)
                      echo "rsync completed successfully."
                      ;;
                    24)
                      echo "rsync completed with code 24 (some files vanished) – treating as success."
                      ;;
                    *)
                      echo "rsync failed with exit code $RSYNC_EXIT"
                      exit "$RSYNC_EXIT"
                      ;;
                  esac
              env:
                - name: TZ
                  value: America/Chicago
              volumeMounts:
                - name: site
                  mountPath: /site
          imagePullSecrets:
            - name: regcred
          restartPolicy: OnFailure
          activeDeadlineSeconds: 3600
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: markata-clean-cronjob
  namespace: dev-waylonwalker-com
spec:
  schedule: "0 0 * * *" # Midnight every day
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 60
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: site
              persistentVolumeClaim:
                claimName: dev-waylonwalker-com-site
          containers:
            - name: markata-clean-container
              image: registry.wayl.one/waylonwalker-com:64
              command: ["/bin/bash", "-c"]
              args:
                - |
                  set -euo pipefail
                  ROOT=/site
                  REPO="$ROOT/build/waylonwalker.com"

                  if [ -d "$REPO" ]; then
                    cd "$REPO"
                    echo "Running markata clean in $REPO"
                    markata clean
                  else
                    echo "Repo directory $REPO does not exist, skipping clean."
                  fi
              volumeMounts:
                - name: site
                  mountPath: /site
          imagePullSecrets:
            - name: regcred
          restartPolicy: OnFailure
          activeDeadlineSeconds: 60

# dev.waylonwalker.com
---
apiVersion: v1
kind: Service
metadata:
  name: dev-waylonwalker-com
  namespace: dev-waylonwalker-com
  labels:
    app: dev-waylonwalker-com
spec:
  selector:
    app: dev-waylonwalker-com
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-waylonwalker-com
  namespace: dev-waylonwalker-com
  labels:
    app: dev-waylonwalker-com
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-waylonwalker-com
  template:
    metadata:
      labels:
        app: dev-waylonwalker-com
      annotations:
        diun.enable: "true"
    spec:
      containers:
        - name: nginx
          image: nginx:stable-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: webroot
              mountPath: /usr/share/nginx/html
              subPath: site/waylonwalker.com
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          env:
            - name: TZ
              value: America/Chicago
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
      volumes:
        - name: webroot
          persistentVolumeClaim:
            claimName: dev-waylonwalker-com-site
        - name: nginx-conf
          configMap:
            name: dev-waylonwalker-com-nginx

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-waylonwalker-com-nginx
  namespace: dev-waylonwalker-com
data:
  default.conf: |
    server {
      listen 80;
      server_name dev.waylonwalker.com;

      # Gzip for text assets
      gzip on;
      gzip_types text/plain text/css application/json application/javascript application/xml+rss application/xml application/x-javascript image/svg+xml;
      gzip_min_length 512;

      root /usr/share/nginx/html;
      index index.html;

      # HTML: fast edits + CDN cache with SWR
      location ~* \.(html)$ {
        add_header Cache-Control "public, max-age=0, s-maxage=60, stale-while-revalidate=30, stale-if-error=86400" always;
        try_files $uri =404;
      }

      # Static/fingerprinted assets
      # location ~* \.(?:css|js|mjs|json|ico|png|jpe?g|gif|webp|svg|avif|woff2?)$ {
      #   add_header Cache-Control "public, max-age=31536000, s-maxage=31536000, immutable, stale-if-error=86400" always;
      #   try_files $uri =404;
      # }

      # SPA fallback (remove if not needed)
      location / {
        add_header Cache-Control "public, max-age=0, s-maxage=60, stale-while-revalidate=30, stale-if-error=86400" always;
        try_files $uri $uri/ /index.html;
      }
    }
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-waylonwalker-com
  namespace: dev-waylonwalker-com
  labels:
    app: dev-waylonwalker-com
  annotations:
    # Uncomment if you use cert-manager:
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    # Optional: speed up TTFB while editing
    # nginx.ingress.kubernetes.io/proxy-buffering: "off"
spec:
  rules:
    - host: dev.waylonwalker.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dev-waylonwalker-com
                port:
                  number: 80
  # If you terminate TLS at the Ingress (recommended with Cloudflare "Full (strict)")
  # tls:
  #   - hosts:
  #       - fluffed-up.com
  #     secretName: fluffed-up-com-tls
