apiVersion: v1
kind: Namespace
metadata:
  name: waylonwalker-com
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-fast-replicated
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  dataLocality: "best-effort"
  replicaAutoBalance: "disabled"
  recurringJobSelector: "[]"
  snapshotDataIntegrity: "disabled"
  staleReplicaTimeout: "60"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: site-pvc-longhorn-fast
  namespace: waylonwalker-com
spec:
  storageClassName: longhorn-fast-replicated
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: waylonwalker-com-cronjob
  namespace: waylonwalker-com
spec:
  schedule: "0/10 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 60
  successfulJobsHistoryLimit: 6
  failedJobsHistoryLimit: 6
  jobTemplate:
    spec:
      template:
        spec:
          tolerations:
          volumes:
            - name: site
              persistentVolumeClaim:
                claimName: site-pvc-longhorn-fast
          containers:
            - name: waylonwalker-com-container
              image: registry.wayl.one/waylonwalker-com:64
              command: ["/bin/bash", "-c"]
              args:
                - |
                  #!/usr/bin/env bash
                  set -euxo pipefail

                  # If it's not a git repo, (re)clone it
                  if [ ! -d /site/waylonwalker.com/.git ]; then
                    rm -rf /site/waylonwalker.com || true
                    git clone https://github.com/waylonwalker/waylonwalker.com.git /site/waylonwalker.com
                  fi

                  git config --global --add safe.directory /site/waylonwalker.com

                  cd /site/waylonwalker.com
                  pwd

                  # safer than plain pull if you just want "whatever is on main"
                  git fetch origin
                  git reset --hard origin/main

                  mkdir -p markout
                  markata build

                  wrangler pages deploy markout --project-name waylonwalker-com --branch markout
              env:
                - name: CLOUDFLARE_API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: waylonwalker-com-secret
                      key: cloudflare-secret
              envFrom:
                - secretRef:
                    name: waylonwalker-com-minio-secret
              volumeMounts:
                - name: site
                  mountPath: /site
          imagePullSecrets:
            - name: regcred
          restartPolicy: OnFailure
          activeDeadlineSeconds: 3600
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: markata-clean-cronjob
  namespace: waylonwalker-com
spec:
  schedule: "0 0 * * *" # Midnight every day
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 60
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: site
              persistentVolumeClaim:
                claimName: site-pvc-longhorn-fast
          containers:
            - name: markata-clean-container
              image: registry.wayl.one/waylonwalker-com:64
              command: ["markata", "clean"]
              workingDir: /site/waylonwalker.com
              volumeMounts:
                - name: site
                  mountPath: /site
          imagePullSecrets:
            - name: regcred
          restartPolicy: OnFailure
          activeDeadlineSeconds: 60
