apiVersion: v1
kind: Namespace
metadata:
  name: waylonwalker-com
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: site-pvc-longhorn-backup
  namespace: waylonwalker-com
spec:
  storageClassName: longhorn-backup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: waylonwalker-com-cronjob
  namespace: waylonwalker-com
spec:
  schedule: "0/10 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 60
  successfulJobsHistoryLimit: 6
  failedJobsHistoryLimit: 6
  jobTemplate:
    spec:
      template:
        spec:
          tolerations:
          volumes:
            - name: site
              persistentVolumeClaim:
                claimName: site-pvc-longhorn-backup
          containers:
            - name: waylonwalker-com-container
              image: registry.wayl.one/waylonwalker-com:50
              env:
                - name: CLOUDFLARE_API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: waylonwalker-com-secret
                      key: cloudflare-secret
              volumeMounts:
                - name: site
                  mountPath: /site
          imagePullSecrets:
            - name: regcred
          restartPolicy: OnFailure
          activeDeadlineSeconds: 3600
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: markata-clean-cronjob
  namespace: waylonwalker-com
spec:
  schedule: "0 0 * * *" # Midnight every day
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 60
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: site
              persistentVolumeClaim:
                claimName: site-pvc-longhorn-backup
          containers:
            - name: markata-clean-container
              image: registry.wayl.one/waylonwalker-com:50
              command: ["markata", "clean"]
              workingDir: /site/waylonwalker.com
              volumeMounts:
                - name: site
                  mountPath: /site
          restartPolicy: OnFailure
          activeDeadlineSeconds: 60
