apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: www-fokais
spec:
  encryptedData:
    .dockerconfigjson: AgBxn1kfpO4eYeB+HegAixCOvW3BvRAbWxs8S/3sq3i6LDAslZQ4uUoWssQ75JlPHWzghHGs8qoQGx2IKFDthxwsR7BYmnJVPlbqqc1VrKLpfH4fVI5XaN2/jHm50LprxLFKYmrUqwiXPe7yNqEEYhlAaBj1xN9/T7DgKv5myuuiCX/YWlK+EC5NiQSIyF6hfFEdoxWab0Hq4oATBqdsYyFEuagI/qyX1ZHISZH0Fkb+ehWdl7C+DuZ6AVkeIds0P2HVPST+yudNecVCZDv/WRzMovang7Ung8MqstaTW6Nh8UF6jVr1sEfgR3OIHTyEOoObGDkpCQEvHGw1tC0i3Un4bF8o3+FHfjMeFjrKXJWy2p/LUlVNauA+eAjUu1PSRqOKeAGJj6fQOaVwnjlABlDM+2dp6F2qpbE7Q6uxSsJ4YFOtzhpicIms281bv4XME79oo6/qrFJtVn+oSVhWwk+52ETjt0kTMUNWt4xXTKS9SBKLIWAzpYqX4oTgtbML+lxl+HfZx0GUaZv33/ucKq6lNS6fqjPzoFVgWm78nJ+hM8vWurfOAaCaRi/2T8WfvoH2LF6OYcyxb59QmNof3+yBXXpRAXuu/bYpiCSoSO6lH0oJXOOh9W9to4QKK5YaYOYybTnr/BwGDkm5rrRyllVTfWEkZKNz/dNsCvXKw04qz5u2+ipsSKgX/h2/6NbgE6/e5vq72rnYKsJkPYTXKY9kEOEsWPLT/RW4tEvvofdNIxXJhR9LElxra5ns793LQBhF0NhsBiV0tYCWSIoVgu8AxpVvp4e8mLUPVL2ChY56xI44bAh6BQSUpashznQnSHtf2jh7SBY4wA==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: www-fokais
    type: kubernetes.io/dockerconfigjson
