apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: play-outside-open-weather-api-key
  namespace: play-outside
spec:
  encryptedData:
    PLAY_OUTSIDE_OPEN_WEATHER_API_KEY: AgCUlJCsDqlAr6j+qO5Ww3NvXWsOQg0wHfYnm2qoZ0SjrWJiwMYtmtSb5rcAAXkgIJJk78tQFf6yPdcRbCM/YlZwVBJTCUZ0XQJy221pQL1A9/1FkcZ6YPEgZu33ZgB9WewqWqhfvnwabDHp7fO6EURQmQRdbrVEwa4gPlOsryHydlHSoMy49zHxM66qVAMP4TuUuCBMnKvtKT4mHwjT+Bclyb2SX03JqsK72QMDBo6jM0MTxfMHBCvEpXgDW7rpYmsV2GGA5eYCKmCAuppqXGFCk75OQ8MVeSIs4r68jfNEKI10OyOpm09ib+06cm3n6B2PjqdgCDWT2u9AeILrJfi7E5kITLZhLoewC/r6GRwQT3mJULFMoEnL1hWVyQnMaaA7zqD9/tQVTWwRfDXsZcJFTI8LmgmzhvPryVcKuM45yYY4qDBUw07jx0udaj5L9502qf47/j6XW8sgYkLihMwreInTgKJUgUMJdqwQMNZ6DNM+I/Yl9gR3q5Ly9fxjTTTQ2H7TPMxDy8fGkhtWsqYSpt5Tf1PPAiiOMjpaRnRmbQyRJVhKUHuHCkxUc9ofi0DCLKKEjmJL5WHzn36LWiE/dWBqvCBN5yc2SEzkzBOeXrVI+O9NRDVBYPYQKGEyGwar10rtkX6HOfqy7dBWAqDPGPTiMvRQXDTNMcQVBTiERYT5qq4y27/CEAjYWjefkPE1Cihi/5JO7kvz/rm8G54bdGaXpTyjk2YzmUG/lpqozA==
  template:
    metadata:
      creationTimestamp: null
      name: play_outside_open_weather_api_key
      namespace: play-outside
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: play-outside
spec:
  encryptedData:
    .dockerconfigjson: AgBOoFY14O3VYJ/gyvmF5NVNDKyWbHI6QDK05WwsQKLWaoOZHjw8dKAXbY5kgSMInjAgC6j9ohjN5YU1aVwTVS5rqxUIOyKFw5JRzkmcoV44qym1lBaXS48rEG5uj+fDi9Rqz3Kv3LyDKHhSPyDduhj3oGQ3k2FgID7UnNEXjZaCokH6suy6s26yoifRjlFdmovFvu7TlK1gZWlTpJ1ugQaUe+E4e8erFGmmwaAlvAPIvJkzF3VBJS2csBWhvH+831nCSkRWgwgOmug1xK0iKnD9aOaa2ZBjvAk/e3pjD2Ocd6PudzYAK8zoW6e+XHM/8DyOX65AQFgHMZbof9i3Hjdoh6BFavbY9Xo1EiWIOMrlgMacL3ZYANKeUlBjBRmypu1thDx+Be6VxsoudpIaeDakkFe3bxdnHGP27Oqjvp7VKaMCP5oqH8E0xQJDY8fWYU6l9VzhEIbZMGBMGVpfNv6bVPiua4jSJSGGSjFbWC+eWClCusWsaQFi1d0rsQrvOFGn5JP0QaxOyV2JIYrb5U4P0b9QOTfWrpNuzN1TXFeu+CBpnjG8VM8fc2pjgECJPRmlPPk5YIw8UISUrMxO9LxVXhXrD5DeNUR5mh1HZo29Ocrdpk4FlOYSqOboQEaqT0fWEf1wh0FV6K1OGxPlOzhuZ7Eu241zsmVPSYwVn6W/3VmpBL2uO4lMnVyOxiaZ9Jf11sRpgWrXqGRS7OasPyfNoA8i0aejydTm9AWuabFy4ZHfQTlfVfpp6h17IAjIdKkfDBtnJiuAzzptxzgH8COFEEwGVQLKq9FOQCy7GHXzPcE51hw7b7coUB0ck+hH01GysUfGdzehEQ==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: play-outside
    type: kubernetes.io/dockerconfigjson
