---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgBmBRa2e9c1QECDVLM+ucvQ4zKClaiZstP7NOyqnn1t0QyJs5DAYWSFc8NvbwGCX46bc4PVMTaYDcThgNlRcBA/n8+CDbVEN+ul/p1mWMTl/xBUtJ5al2d1uWPaYiUNk6XNwW6r5Wr9j5IdvOEPjnDLJcrwMVnL1gvwGVm0vAs4H5Q7pI+toMXvSUfUTWsjvOSAsu96TGHsO7/Ec7xwGGPf+My8EWlNMnKhCSZCFFCjYmSqJpJbXB9RXS5vsVopD9HSLog6NaFLFR9cbz22wPBaJncEXJtZb8aWBllxCNNbRRjfHynaXOLC8eZi5KF41flFoSEH5htkCLJMwt5R/+GnPmNRtRwcYznUtqiJ5/zO0qYZDO2Ih/Or58qqzWfpLwZLwgoeHmyUcjtcyOBUU/7iL7Qb11mMkndN7eZR4m1DtIWm3ZBJWtu5p1PONcqimil0ANSJPtai4zi8tQTxg/AZ67apWuxNYpUhnzRl0nzUOdxRfW54kGwn3FDWOEazhReTtHJyDjQUFTs0X1golv81XB98GXAys0/VBnqoW3byxFXzKWm34Ws63/yKRPme2qQNuDWInAR+pkcOKfZqOTl/ugee3LWol+NtIFVgM6QUIgLZeOlpdM0RkZTN6EQsXA30ZkzOD7f2ltf4HaeEAyfzRV0fhguvsdFavcmnj2zQVAukomoBbfA2rb5VlpPKKFhOGtERC7cYjfFWomIyG6jK
    MINIO_ROOT_USER: AgA1ZsXkykZWmjPH8T711fiYnSeGRH6OVR5K7gzmDvV7H+5VfMPwH5pUwRLX1t56Kvw04Y0cmwe4UMfOWEw4oq5j09M/GaRvAN1G8M3Jv16WNbbGHbv6EOSU8m793CmFnXol3mUKGu8XbQYyHaawQsGG57dkpAbkr8Ghkqmr0OtMfmEa0RBqJguepWJM4lyOyx8wPB6QB2NyEeLSvb6jqm8qCG5GmdgM9q5n6LoDIUi8mjqOMxAQ6V22kIixHDgd8K/tLqE40OuDBkYf682wyzjN9Ph+MOcfmDGZlWZ24BBLExFDM1g3PvYcTqe2u7FPKfvH3YD6s1CltVc8sc/MDjAeaROKb/uShEDgBGxPmZ6DD5pTWGPElgF+welvRSJkTPRdHRHeaVo6G/V784z4LVtEwaCwhlr4ZQk5GO3YVHNPBDxMX57l9+eKmDUwR1OS13IEXR3KuRLvwLGZOT+Qp+/fc40qRloiWYyIeGcKDaWag54J6UySfXWAG3K3dGPY2KvcF+JeoR/+NCw/f2RstAcMebX/0CeBR3c1HrICQqYA14ag6G0svSwpwDf/L8nNkv3+VrCakLF4oH/xNzCldZR9qJ5jn6bu9aN3NfbeRvv8AsebPIaJwGJm5B2LdxVFdN4MxBrcUcyhL5Ef/CF+WWW4WeqQL0RE4jTo/KYyDjssvFrTIZolCnkY3Z1pJn6JOPqiVHTST5I=
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default
    type: Opaque
