---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: minio-homelab
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgA/PIbuwuhtonh61Fi4gKKnBirYWSZA+icElTJq7QAZ/y4L4it5P+ebBBRMz2PIXWhK08NJX+p2EuoqghJCJVcm+Kk1ivPUazDASVD8NqqehmGEtRXRbitXu4hdOagiRJTAHPBvXVyGNrKP71+fV1RAvXRojTzCIxiGyhq7cdxgmtOTgcS6TDT8M45uic+JObifqbZTOXaGxAmo2Wy/8Wr+S3T+lV5cgtt0Nq8cxOqLgNigshB6Bb3bYCWKXONlaS+y4sgtdLNuFeOvUyIF9Y7A65gD2Zjl5NSaHXRgJgcrZhBU39Sm07+Lk52Xzkblh5Z37cEqZGDEKH+PDzmftlsdxJcZa6AS0ZYeZE3+hvjqDKu2Wb+/oEqv31wSjR2QDxThh0KBHyjaCH6f90QPBBfNxtua6rlMytddsLfsZpNxXITLm2B4swl8/Ot9JFbs4aYyILa1iIdxlW/gguCyWTYY9At/OKAMJ3nRFwrpXKekNtHl9t22dZKLo5Skm9FdV+eN4nN0lpOl3hEquVtDhDY+ojlxMC73Ua/lHdkF94l49wLo9VJ8WN7KPq0pdt2YnQP9rhFbpF93Ymxrv2/fDdBr8LmeA1tjgzBxM7Mg1XMtcLnfCUGVlsToKy2aJBrz8altJsScrs28Q+EdKQdlsZmhqIuva3Dfl0K58XbA/8gwYw866LfHimUlx9L+nF5NQQ5ZeZ/yrZiwtLfNlveOm1a4
    MINIO_ROOT_USER: AgA+PAmHizHkJc/IyAgeLtvZD8tGAtWMo69f23VzRmCdpFG2QmdsNcjTaW4XulpekuVZDGirqWlB8g11kjadbKa7ttPAIezrVlqO8C5ZXw1p/JmNfqrIK3ZW+VJVj72EdH+lYN8MvTG4dPCQuYbrSOzDz1nD+1tAQkbXmn8zja3Eb4d1uUwYs7rbNsG9SUH9+5Cdbb14N5L5mmBn7qvlqzYC3maUDfjAtaQOtdgS+VqVer3SuLIWe/EWNuMW+wnyidqXInla0RQ14tJKQVBDZu6BYq6C39XjWWHS4VesUBEwGXtxb2lznMrhm7oWWakFyChpeQpqDnq42TdoJNxiWMTlyh+BIWN8TOle2oVVZAzgCFX4iyE/gfswIbAQhCAfgS0WWUBRW5wsiBc+r+irf6xrvBtxjkqtRJ/t3r1goIDbBBAdoKCMYnuve9xvJY/OjI9ENXUj7IKwKcgMvwslJXjF9OfaJTUooZ6RRoTlkoLcM6UleDsAOeHTFMPuZ3CvXHZK/Vx2d3vLg6/uz4yxo8ICmVPKAuDwumOsPh8HVlnq6xubgqJipNtdsQ4+aXv+DEve/JloP8t50ZSoWVnb4nFaSdpl7M+WrYU2fdJd+yLtIJ0FpjgaElnEUr83Y5nrqUtABxK69rJt9di6FeO0WVFxSoBebeyzRcBWRkaBO62ucPPKEVBk2fqJCuBH0gWijeMKpsniVPo=
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: minio-homelab
    type: Opaque
