apiVersion: v1
kind: Namespace
metadata:
  name: frigate
  namespace: frigate
spec: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: frigate
  namespace: frigate
spec:
  ports:
    - name: "5000"
      port: 5000
    - name: "8554"
      port: 8554
    - name: "8555"
      port: 8555
    - name: 8555-udp
      port: 8555
      protocol: UDP
  type: ClusterIP
  selector:
    service: frigate
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frigate
  name: frigate
  namespace: frigate
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frigate
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: frigate
    spec:
      containers:
        - env:
            - name: FRIGATE_RTSP_PASSWORD
              value: '"password"'
            - name: TZ
              value: America/Chicago
          # image: ghcr.io/blakeblackshear/frigate:9c75123
          image: ghcr.io/blakeblackshear/frigate:stable
          # image: ghcr.io/blakeblackshear/frigate@sha256:22e3d0b486df52c3d669682254c2b1bf4205fa6ad8bd8f8c9f7fe76b1517005d"
          name: frigate
          ports:
            - containerPort: 5000
              # hostPort: 5000
              protocol: TCP
            - containerPort: 8554
              # hostPort: 8554
              protocol: TCP
            - containerPort: 8555
              # hostPort: 8555
              protocol: TCP
            - containerPort: 8555
              # hostPort: 8555
              protocol: UDP
          securityContext:
            # privileged: true
            # Remove 'privileged: true' if present
            capabilities:
              add:
                - SYS_ADMIN
                - SYS_RAWIO
            devices:
              - devicePath: /dev/dri
                name: dri
                permissions: mrw
                # - devicePath: /dev/apex_0
                #   name: coral
                #   permissions: mrw
          volumeMounts:
            - mountPath: /config
              name: config
              # subPath: "pv/frigate/frigate-config"
            - mountPath: /media/frigate
              name: storage
              # subPath: "pv/frigate/frigate-storage"
            - mountPath: /tmp/cache
              name: frigate-temp
              # subPath: "pv/frigate/frigate-temp"
            - mountPath: /dev/shm
              name: cache-volume
            - name: dev-dri
              mountPath: /dev/dri
              # - name: coral-device
              #   mountPath: /dev/apex_0
              #   readOnly: true
      restartPolicy: Always
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
        - name: storage
          persistentVolumeClaim:
            claimName: storage
        - name: frigate-temp
          persistentVolumeClaim:
            claimName: frigate-temp
        - emptyDir:
            medium: Memory
            sizeLimit: 256Mi
          name: cache-volume
        - name: dev-dri
          hostPath:
            path: /dev/dri
        - name: coral-device
          hostPath:
            path: /dev/apex_0
            type: CharDevice
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: frigate
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  volumeName: pv-hostpath-general-config
  storageClassName: hostpath
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage
  namespace: frigate
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  volumeName: pv-hostpath-general-storage
  storageClassName: hostpath
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-temp
  namespace: frigate
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  volumeName: pv-hostpath-general-temp
  storageClassName: hostpath
status: {}

# ---
# apiVersion: traefik.containo.us/v1alpha1
# kind: Middleware
# metadata:
#   name: localfrigate-auth
#   namespace: frigate
# spec:
#   basicAuth:
#     secret: localfrigate-htpasswd
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    service: frigate
  name: frigate
  namespace: frigate
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
    - host: frigate.wayl.one
      http:
        paths:
          - backend:
              service:
                name: frigate
                port:
                  number: 5000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - frigate.wayl.one
      secretName: frigate-cert-tls
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    service: frigate
  name: ffrigate
  namespace: frigate
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: frigate-localfrigate-auth@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: f.wayl.one
      http:
        paths:
          - backend:
              service:
                name: frigate
                port:
                  number: 5000
            path: /
            pathType: Prefix
    - host: localfrigate.wayl.one
      http:
        paths:
          - backend:
              service:
                name: frigate
                port:
                  number: 5000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - f.wayl.one
      secretName: ffrigate-cert-tls
    - hosts:
        - localfrigate.wayl.one
      secretName: localfrigate-cert-tls
status:
  loadBalancer: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath-general-config
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany # Ensure your use case allows this, as hostPath is node-specific
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /mnt/vault/nfs/general/pv/frigate3/frigate-config
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath-general-storage
spec:
  capacity:
    storage: 10000Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /mnt/vault/nfs/general/pv/frigate3/frigate-storage
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath-general-temp
  namespace: frigate
spec:
  capacity:
    storage: 1000Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /mnt/vault/nfs/general/pv/frigate3/frigate-temp
    type: DirectoryOrCreate
