apiVersion: v1
kind: Service
metadata:
  name: frigate
  namespace: frigate
spec:
  ports:
    - name: "5000"
      port: 5000
    - name: "8554"
      port: 8554
    - name: "8555"
      port: 8555
    - name: 8555-udp
      port: 8555
      protocol: UDP
  type: ClusterIP
  selector:
    service: frigate
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: frigate
  namespace: frigate
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frigate
  name: frigate
  namespace: frigate
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frigate
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: frigate
    spec:
      containers:
        - env:
            - name: FRIGATE_RTSP_PASSWORD
              value: '"password"'
            - name: TZ
              value: America/Chicago
          image: ghcr.io/blakeblackshear/frigate:stable
          name: frigate
          ports:
            - containerPort: 5000
              # hostPort: 5000
              protocol: TCP
            - containerPort: 8554
              # hostPort: 8554
              protocol: TCP
            - containerPort: 8555
              # hostPort: 8555
              protocol: TCP
            - containerPort: 8555
              # hostPort: 8555
              protocol: UDP
          resources: {}
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /config
              name: config
              subPath: "pv/frigate/frigate-config"
            - mountPath: /media/frigate
              name: storage
              subPath: "pv/frigate/frigate-storage"
            - mountPath: /tmp/cache
              name: frigate-temp
              subPath: "pv/frigate/frigate-temp"
      restartPolicy: Always
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
        - name: storage
          persistentVolumeClaim:
            claimName: storage
        - name: frigate-temp
          persistentVolumeClaim:
            claimName: frigate-temp
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: frigate
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  volumeName: pv-hostpath-general-config
  storageClassName: hostpath
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage
  namespace: frigate
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  volumeName: pv-hostpath-general-storage
  storageClassName: hostpath
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-temp
  namespace: frigate
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  volumeName: pv-hostpath-general-temp
  storageClassName: hostpath
status: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    service: frigate
  name: frigate
  namespace: frigate
spec:
  rules:
    - host: frigate.wayl.one
      http:
        paths:
          - backend:
              service:
                name: frigate
                port:
                  number: 5000
            path: /
            pathType: Prefix
status:
  loadBalancer: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath-general-config
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany # Ensure your use case allows this, as hostPath is node-specific
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /mnt/vault/nfs/general/
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath-general-storage
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /mnt/vault/nfs/general/
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath-general-temp
  namespace: frigate
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /mnt/vault/nfs/general/
    type: DirectoryOrCreate
