---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: basic-auth
spec:
  encryptedData:
    users: AgCxgPiookV1Xln+50JPwV2tc1JoVYjx8n2+zBj6Abfjfh28UMe9/RpT7S5N/q2QrwJsctFXH/9ziUnbWBVXhlxfT3chbwmTkZKMqqT+we7JcHcMM17wqvfkpEhZKqEagBalQV9xlryd656YLMLfWSLPlLnXFdLnyh9ECaQzA4jMy/LDF8zNqHsKjOAZ7xJXWtlBiYDvjXhWZ9txZWdGymqmE352SzVLInH7JQgGxSsh5+iMrTPwhptE0QPYuD479KV0coPmYyXUWX9ri92eA+cX9h0O1G1KFiyQJlP0dsuu/RD1k4UrSZoVy7wBnkidDAAijj21Fq3fpQl8UQpfX+JkkyyFlRQ5MwsQwrPx2J0X/CPAolA9armolDlOetfrVahxN0cIT4GjqWuOeIo8FFxHgeaBlGPmoJPkeRIydEt7b7+gtZzGx13YzJbEMA52Ph9ahbrVSelU/yU6HuNiP05/riOF+n1vLUmKL2MMxcTHgHCetGIrb0LmqiJgRd3zgHoSmW57W4NTUfCIxknGv/J+goUhe/JaV/wtAV4nV18yliGjwxk6R0/Beq/KM4aDLQOz2s7scimeboZr34xMsMwM+S1D+r2s28ofgTABgyjFNwB8AHbyn306YF9lnFklCY++2qCFZV8kTCbpMxCmwBPqc/ptj0mFC+vuBpjP9+XYVsSRorNpcDsfYFdqITYAmksdiy4AoM6kNC5vgef2EnhwFJNlE+lDDVfgt3V0DrzK/RaQqkSYB6A6KE21JiY=
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: basic-auth
