---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: basic-auth
spec:
  encryptedData:
    users: AgAG9su4+8w+Tw6A/QDhqNs9pA9YbO4FHvkKAu122ICS5jiLG6ZxVnFujU7uXRd8YwTnGH75yVqBDm6h8JnWg2yS4fkxnn9bN/HAayss0d8XVJYX2pX4SVV1Burgc5mSW+EkzKCaqyh9u74xLAt22+HDTLsAUo/HgIjrT/V0c9/f/Ga1wPDqvh2pD/UShMdukJI/G6tl6rQXc3sjjrkb/wXqJejJDY9+5GkjU5lma9WBxjFWawTiIznV3MpSV1bgIkrrGm+Nqi/njDa1W5bnvL9CyVt4serJoBQiKi/SUhfFZWYa2TcWJG7uKx70fvbwNdvLbgOlLW0iIVH1mHiMSPofj3mg+Rq259JQ+jE2xUEcS22iu5TgoT9FlD0+Wo623hiX1+dCF+g5t3bbVXrsUKvL+znX85AYTW0B769D5FSjctTRc1L4DbJUkjLxipl/MdtCxxcI9yNxrXef+jPZw54h7mHqpITnB5cnStfZw8Nn8C6P8UE7Cu7vPl7sFqr+1wQwcMY81QvWd6lYTv+i78Lv6Cr5qtWAcozuy0GLzyESkQxVXAcyUW2fDJO+q08eP2oL1PYrpyTeLeIhxlmMCRB68eab65rQC63hJh997tzEDGFa73TfuAuTfMEUe25tnS36pknDfzEH5io3adzRZik9tRq+scH1ls7zicFqrJD9a9ZDHypRkRo1RrkyiAo423pH3KGS2EAyByovs0OTEzF07d073upIRPhvV6Y0h3MMltquphOFRLVm45CgudM=
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: basic-auth
