---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: basic-auth
spec:
  encryptedData:
    users: AgB1F+iE8ArXYjPqRENFeMkcM184WuvG/CXLR/4HG2HDNOqvcytIcjOlS4VIz5ES3oXdhzyduvzfPW8Lm8zNG7Zl1R5nU5ddp9T4O/HLQ99LDzwjw0akL/GzZDyRlft5XApvzb5EwJZHcVQaBVPgv/Q4RKcFPHV5k5fsGQKB6EHa9/UEpaX5gxaQLpTLQTY4fc0B+DO7IIkIuVxe5saSmhbgFCd8UASGUWSXm/VBOv7DgEr+Dzuh5/LDdpE57hSz2mfHDoGRq6cbM78G+UomfcLqq2LhUt/vRpUE1kVaAcB/FGi4nlLviq2lPjODsZhMq3L/bDN65rnAffxOvgCk0QAcEJJHlwZ7/2tDId472VQw7cLFizfRiF9xR9IL4ik7hzEGnOe1lJBZD6+ikQH/C+p1DEzBTn+N8NHOFR6gwSkJSJEMMhcbEpT4jxo9I+z0TOiGqjO7zzy6C52WK9P27U8PnyrP2ZuZClA2CPSNtAK7BPjsu6rvggTw0jk+LNwK1Va0rX0LUiDH9GhJ6sedI5ZGhhcNaI8ouwhq5zqm6XAguKWpMKD3V26y5VXZbSvzVKEldatYeQzC5FFEYDiSEinCgXBrJ+osuFrOAfVU69+WBTABUrIC2ccRxved23NhLOvnn03tUZmFt4Ln0LXCBwTqPMgLfVhislwa1Xen5XFGw37yyhLKsH+zWG1JMPBNg3f4dm9m4CUJaCMicQCTAZCT7vhjVnNIdT/3tsFBRbwrIIxryrN13Okre9XCTws=
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: basic-auth
