---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kraft-secret
  namespace: kraft
spec:
  encryptedData:
    rcon-password: AgBFc9Z3+cCoIR3V0+1fFEyqT2XpIzBMlO2LmX0ZS1tCedqbvjMQ9aO+q7jvWM0/JF4a+zUgJQTczU+5oS/xlYTJM4ZmFcO4BFGepLWI+RfEkvZGj8yn+E70ozDMaJsbVTEswJKbbV/ENhpPS6HNcfrQ5X38fV8l3SoQK9Bnw1jQeND7rF8J9SwYKymRCgrpzrIzHKUisqQydv726SGK6byYiVqKSdVp4oH5no8ajrABngjmCXe5/2YJZAUYdw8EXF+1ZWENDE8W4lBfsCiG+Atzpejz72taR2bbDHeaxUOvYEd0tEJdvsr6ESnWgN0fKaIP11OmUoDac9bZy9QLwobSi9SmDZASac8wSSqqkh51zAMKyM348nS3+lzLa7w2PYyIMJjI8IxpEBWkUOJeud8lPh15CnRi9+2976pk3f/We/E5JtOy0oMoPS7aQ2v9sDv0OogmBD6KKKwR3N71obv4NT7QQnQqC6T6Im14oIJcJ8MCNYfSCUSfa1XMenHlRmMV/o/iJOoLF7TtI+TB/cGkpWRebPSLF1TrXVgJFdqmAIRb5MUIjIIOyUgTgxzKPv212NkHrsRwfEYrlTG4DGPO1Ck8IrzAqf1VQHC+YSasEisk/BOnMvXuoIF0tupzKqhN5rRM04iAAWcQVDSAnTDzkvMXd+4/YJtbMwxpkvZRIOx6wWPy3R0A5/HMEHaqsekj2k4G4UnQXFd/2zLdC1+6
  template:
    metadata:
      creationTimestamp: null
      name: kraft-secret
      namespace: kraft
    type: Opaque
