---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kraft-playit-secret
  namespace: kraft
spec:
  encryptedData:
    SECRET_KEY: AgDGrlOwFBEPyImlU90P/8tOre2DfU8aPLB5q+4YWSIZaZ/dif0ohVdpaAZB25BOXWU3dQ+GPMKCx9/FBbghwcVsT3KkQRhB+/dYpQIxt1+Ur6RK5TBRVPYMPG0LlUUFE+MU/tJSQa8U8tTrnQVVxLU3tlz7AzmDw8/GsOLK1TZXlruwPQDfurA8QnoiaShp7LPmfoNjbGZLK18kqoSiF43k1WrkEmtKHIYxaT7TGPLCpr1hFf0efukxmqUYPhrklghYKJjXghLxReU6CNLyO5XGvsei9Mj/vfzYjj0CXj7Qd+WIGmBELK4cQ0PWOYi0N6RSzebtai00k1HywOHZTXZcGClxG1pvHI9tmkXIYyg+3Ahobmh446d8FRizz5dmj/80Me1oGguKdocfPqAjUmdFlsdOlhwCUgCWhZtJ0p/rvMyEBroJTC71MZDIiapezAge8XVEr6lGj6NySQp7ThfpSJBhxegYhvDVxYwOQym5Vn49+t8L3TOJr+9dv0Bd99OOZYBo0Lcocu8/+58+lv5igOms5995CJ8NRCqAJFC0PnvN+jlx2stIY+943Ub8sZw6tuMoMhU87aKtKqK4ktMaFC7T3MyABBRelFqsk1afPknJZ08VuVZZiTUJnyt7RH6D3+Emkso7fuzTHzeE/zOndDt72vzQeWFdnMStN1dbFV3gscVZEZDjHlAelFAOwe0XJbD4JpNo32kCAnpidTUK7bCSa3j3D0YYnY+i1fq9FQ/v/MVXAuZPBIBQht8wYQ2QjOXWw4iK9GnCLkwLx91I
  template:
    metadata:
      name: kraft-playit-secret
      namespace: kraft
