---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: magnet-smp-playit-secret
  namespace: magnet-smp
spec:
  encryptedData:
    SECRET_KEY: AgAuVLziPB27N48GUc5mskC6impn3hLrXh/BaUhWjK92IRVb7fKgSWXmDcCoQ1FTRyJ3IIjcpA/Cks0eiMonCYS7SK+l5n0tUjIPwj46z794A4vhPbhxYyuqGjwYwdBE4aR5PZFZnBnbJ+94WmKxWATl9/grr/GYXzgVXfSFvrASOkshUI7qUUQ0QTznTuJvQdYkwEkQ+39fPqllWbpB0MyWeSw2Jg1DU0ppkG04tiH/7+5/0r1ZEtMxugBL0Mg2hEAvJnC4NPphVsijclEwx96X+iF1h4TcfZoKHcI+rJOYYBQS04Gw9KH09hPpvI3DAXsGc4IP5KssPf6NCUQsQr9pOmkgsw3ZTz5XJ8XckRIvUQn1g95lk4OEwdNXJqjZ+YlRhMlBitBV8b+xPgva1fh9/zpsc9nEHxjFJALcKDQbDXtfgtg0vGOSk+Vaigu7k7+tQ4MiqH3qvT3GqnyFSjALrl0x4cmx80jc0oKMj63rmTgC242NJegiVqWdUMPlrHTluL90gZbnr/x6dvU7UP/W5bRd+qYzvy0jl+Wh6t6MKVk7bf2WjtvAydpjXdC+3C337PDFFddry1CSPdawN3kKJp7d3VAI8IgASl3ZJMgY+ttBKeI+GTvK7RfJck07/h3w16+1L2xL/xZec8J7AKrh6iyGMNbWmxzrUaxaViiohtQZSTsoTf3nDnv2bwoJEtZwr/V96PFdmLGCErfhehkHtwgj5UxEi35NaPjp7dr39KrpBbtzDMK3pVg2ia4vvKSGZpALVOcM/w34hRMZLeo4
  template:
    metadata:
      name: magnet-smp-playit-secret
      namespace: magnet-smp
