---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: magnet-smp-playit-secret
  namespace: magnet-smp
spec:
  encryptedData:
    SECRET_KEY: AgC+/Nhazz7bocNXigzpVAt0y2Bj5BcxcJWqSYXcZHD3krAp8pSU32dV0OezlrWb9Ra+/ZCfQqGtp5stPtE4UvKkqRbx+FQDqMSvs5CFBQe3vWBUSYr6Zlqfiv2A7fuNDykbDv+pe7d8UMwTGdYuPxDW8ThRTSbm6Gmw5rLwO/DjRvwO1OwpUHOLFhLDobwbhmitc53inVl7hA+Nwd8F73Zn3CNbaCifOpQveWNsASiHqLp/5keFRhINapVzONXD30MJc7eM8H0SW92cIbPcNwtaPFMh925SyokPkWBwGliU+1XK06e51IRNE+RoBr0CRzPAEYPP2jU4egy47QBn338yHyKj7Q195IrgcXmIFbt3sM0VIbbFuNyVYxEANQ59/ThCXTYWa/+NGcd3Q7XZd4B6bYjT6YjZvojCm5riukGmMXr3qtFJUBvLWO+u/LB+JiVKnz6gEYxWP+xkCHE6QR1aq2C3WHltzzJqXYXcE69XTVoiBRnCFmWmk78fw2vYTKZCLMH9e6ZMJhig6WhwyfZWE0VRVShA9IrNCgpxG1So+UgYipWxh8xvuif3NMM1wts5qmqcgmcbKZQgpqq3bmTgMhWL0Fb3V6e8OIDw62i6yovJmkNtDOEw09nriFUEYzlo9nhZGecvy01DD5Vc49vpdGd0qYYfS2PpCU/SkDOAc5gxeSQev2X8S30xSys/7zQ4fPOI9fYeMnctySiQ/0UDnfib8OSyxNwPO347xKqHfFPgFdZfANk46M4k5yfJ6W6EUZZRy6NVUR1tV1MXAe96
  template:
    metadata:
      name: magnet-smp-playit-secret
      namespace: magnet-smp
