---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: magnet-smp-playit-secret
  namespace: magnet-smp
spec:
  encryptedData:
    SECRET_KEY: AgBJT7aWdX2q1F8DM52MkK9BNi8Me9doOGbQxwFOdaM4zLeN1LrD9ji360iX2VvkabEzpOLcO9gj7BakoTZkFWbG5pyEM1YMZ8gfZBGv4H2UQNBvTq73Ct3IOGyyTp6RhRAb2g6oo2FbYYha3L+uvWbdAhLy/bS8Sdvg/qO3f1DerW++ftr2LFrs7+fqZfesltLewFicULdxfur6gfHKjgaCmIw8d5FNlc8Hf8AV0t+0TDy1MkK4OPlJE/l8uJ9+z4JltBP9le04cbeKd5+G30l7uIUtyS5kBsXkgNf/8eQw0uhJDp9Dr7ZxZ4Wr10hdPuy2zE8H+lNJv4tB2aoNK4dZ60swp6OnBnJDKPtxuGt6ySlpHKMPocjB1nvZLHq1xVhL2k7/fQp1wwhHgQ385znOhWIicPzlhFEKOS16pkKbjGhoULSY3EDKPLLbvnL5N/4HxFJ5sUyohD6hkcr5eM0wm5yOGrKHhpiivxHLIc/HujnY61TW8ez2bpCb3xqptz2Uc9mT3TcaQHi7kZra84PtDNxRuzYQKtHQW8ZcpVkH2BVPZIl66UVkWsNgVHVsVavQFIdZOCSLCKGlfWPVKQH9kd/L8/OZngSrhkFls6+trQjbUURSoD84SId5dyxLK1Hz4Fk6DF6nrrwaW/NoJnd2sRCR8QwfCsaaIlLGHI6Hc8nKJftiXaxmqwDHotfo1iWQRZf8xBBA/inP+QJpvxm4YYhX+o5/OBhFOPFxnq1N/gNjIlcXH7gmSnh6n9o6Gbf3rnWmkTvk5hLtAkRhbgdC
  template:
    metadata:
      name: magnet-smp-playit-secret
      namespace: magnet-smp
