---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: minio
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgBShR/dDlCwHi60P6W+jR0KpJpHXgXKH0eYxqd5H7QV7sdSBh8K2fJEG9saLQDIVoeWfdpXQ3kK7W+rezUlAaWYLTPO+qyc8Ff/TEtulxkd7zUWbAySYawtA9ZIrqwukmWhbEtBs7sZuiTHjVCGLvyTUz12za7lYLDQILc8NBjSMAEjY4GPAiEVXTt0HmGH7KMvTpPZ74RyTpeNIze+oqlbWmuCs57G2L39p35P3pvt0YB4OTcUg0e3Jqw23fT6C39fNHrgxizw5XtddH2PO3AiTRj+zcayiUDdq4Zs1qtOcB55TZ3HldkQkQD5fA7J54zwElD+4vNaiXSmKHR7gRyx52zszTE3GzaVBGO7ZBUuSxCdumrKZdkWNyIDtmDruzyeM9t5znbFs9gaUaa51ZSp+/JQtxd6sEFIQi/xg4JjNNXLKjisBnQqbo7Sg/k9MDBgNB8fhSdquqW8Dm7BUEqEfAw6xk/8nUN4EmAFrYjB18gQXgrEBvh3DDQDzjh750WQ3n6jSVLHGVAMh5lGzmzGycyPuscyqiggF2JIJvkg3wp69UrEYz27kyHbxXFZK7H/LPperQbv1tFEHJlE+CgiA1RlrNcchATEdPHuvBKEx9KGrLaI9tGADM4eVxVb6tYnPpNk6ESdkehsuqNJC1Nud/wljLOvp1N3D7iBrHyIq3hvczr93hNszRiI6f/G6IinEOrmGIfkDwCeGlSjzF0=
    MINIO_ROOT_USER: AgBwOOe8pu3wfiDB7tAblgFglwwdDjZ7zNAhRIexzz7MUYfi8VYqjz1SWhQDSdAtpv+8+SpANABlL9HeTOiLPqBTosc4sxKRi4hrM8BTArVt894p1veWrDVpf7SYp2CqaISM8PvPtcn+kJ+EOr83GSDv9wiek/ms7pY3QWmO5HBZRFwPd6ClUw4jLUwFgNR6eLER/vBmvv93ExYjikN/T8sFVW2mHELbsyvO6tVsXUje24wlfLs4lC6Rr8bDwdKS8KiW13pxbW9GEKZ9bSY/kcSoYH9njhsnADRkEcEI1Wsll5F1rFnx5NDhLcXnwQ9sakhZQC70a2gUUPS+WDN+t8WBL6railfaKojrngzDyi8GUuwiTU8IGCLHNBMegZxPrmZ4fLY5unAyhU4uDE1xbktc20/S6Iq6ug5W/UFmYSti7+ZAUsalnysk2sptR+Obqri98oICVbBK38/auNVetODRLbvNDUfYd4IlsNsREKbkGzxXFlneXeRbO5azE4G1+fJ9CoO1lX83ZXbjihCgMTW4ZgCwcLC3dbLsKEyDyggk236DG6lmd4orsOCyKWYOvFKqi+lHnQPQxWBLgSIGlCLYKmOvE0Njgnw/suXfQMxRCE/GyD5qhyXfa/EZrEMXpobGuabsOXeNULLWuuFU1zeDdinyg0runoZiw/1mDmkzhS6iAlUNuW88+/sBstXX+krhOzGGhZXl
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: minio
