---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: minio
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgB1l5r7AZcgzERGHt6PNqK8u+nDKQB1HMXFCjRDgggKQYeTrCkSaEAsBdglqEpg5W6CICjnxTtTmgvT8YC7kTBFAGRKOnZLWvlHUfnR4G5j+SuoSxIbpm0SGdxb5FJr2OwZKiCKjuNHpwqDmDPpjtu1yGKOa/lqaNdATHRsX8mtXMDqrUo09MHwYRGPYEdivd85JiUM1ntC0/i9DA6/MQqPfyf81DX83o0aXr/3WbiHWsQmkjS+vYAhcSbAJ6addiE+5hQhO94r+vMv6jjASF0ipWrypZL+AUTbWei0vhjF3cJrjX4uuVyXm2QY6AseFQ6SgW1ts8PpJV/Ii3OesVjJWXRcbbfz9zL2YHULYcBtV9VYsuo1Rn7BBB9PdTpOh6dVztm1pYXD4tjAAqcH6TYvvTmgwT8wIxcpROvneqAJOgA5YvndXIGWf2h/06Y8G0cUOs/fNa9hq0j6NhP+kfFxtgqPLM0Tcd+xUSgY82D/u0uUN/3D76jfxvVMoniVUtXXbGxYaE2UdFfdoOMLLBjui9pRq+OtL4ie53wiEpMvOg3OF2ufj+B3hmgP/0awgQvYoV44crWQpdiDvqUWV6xm3e6rBeob6njDnX14nqw+kx5Axo4VA+bOJNldQ1FbKfDHq6OsokIdKD4jv/hnbBNQqn+FFdlb3XfnCd8TdFW7tzbU9GlFwoQsJXQorYJbCfcqwaHwEBpFKtNjiaBaNNc=
    MINIO_ROOT_USER: AgCR4dGg6FBgO19NPMHlPkRjp9MaxTcW4weTxeveila5AZx9K+l0FqzdUspFB6WDhbugFhr/6p36CuDmNrAktut8m9yci5AooCbqBLpqXPxSdh5BNfDhuirBeofCNp8pF5Dw1UE2evmaXtc3DGWk/i1uHeHbgayWiresLLYrWQDTffzgqNlsa9T4Sl7fv/ZGOGl6Pkyt7s6PPJma/HR1ntLuUocNDsAAn+trvm13+LxB7e48NgIDMX2HUaE50hSv4gBICEPgyY7YrgYP86yRNFnFaq7cQwKpv686J3mRcScpX//ObU4HjRbiO8Yls7I0PmmXah9o9g4z+6fwB4XCnF2HuytVDH0wMhU0fXgZ6AH96Ppp/BJoyFHCLcddQYW1lXvManyuTgg/k1MOxjWRcrX5ih68oTUr8hptLdGQD+n7f948tlXN4gGMVc0+b9egagqaJyt9sTWmqmltdIvETUQclVFVnVySlGuYvNGOZr91WgscEEn7A4tX9vgs5G/MO+pSrY2PKRh3/U4nAocs6w3ie6mXvgGv5U+pLBz8FHriEfTa53tMrgcSNiw9m9QmCT7NVmNuBVUuvyYC6AtkGIbq/yKk2CPX5xok2xmifrMBFIAsznXFqNyxHK4uf/+JAwGKlH5lOaf0pv4TOsMeWGVUVgP6F2WEsON/PeLWnvqcvXMcqPCu+U7NeOoEeG3gvf6NSe1eZTu7
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: minio
