---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: minio
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgDQG56iFI+wKu6ivm7Y1q8C5AgNObKro0+kSdTWIf9TT/swNjrfs3aFcy11yo1QGTcSXlua0NUHUeJv7tgAxQK/tsTbZ+Sf/gajERfrQX+Byi2zSat4Y6akOIOfQTQTViLnnJ+OTOYVCSp+5VyFeT40VMKlQabvqSQShDDGdoahE7OLcA0Du8l7/+rh2c5PPaEwe0E35E7RGPu1JKl9oJcBQESMDTxDtrGL+0EkhHa229ZJdakjRdp0v2OCyFTxwCAmcmMHxn5pS69IMCOeusj9bilN3BQgjLFtvEua7CbHZcYpyQgTjKvh46ntUAo//n8h9VkWf2eBNFIACqHKj79o9klF5OSFzzbP5MwbZ4Ukke9SvUw1DFlEsmPnoYShV7xNKOmbSI4uCF0em7BHJrfUC5ohqCn8NdYi+gSlIaceMzmvBlRq0VOADsVXQmNMCyDPWOH58F88sX2th7Cbn2eaFeqIQ8oaNamS9qvxEEAbPQlPM06Bm5kS2JMjCfOtSc01q5HyLYEGunmhXwiL3S+U+83KgZ1de8KNAMIx4i8wsCJy1bOVsG2TJvZou3/8enGFiBQ/mFd0vQtBJQ1gvUZlTzQn8gV7XswZuKsf380yrHWg4lxdF6Oo82PoO6Od7I5WCXK3B7lASR7BrOkiZBn38+326jZH1cQoa81XLebfTk1l27A4y5AAV43NIkHzZT+n7LSV3CgL4BxWIzoytEE=
    MINIO_ROOT_USER: AgACTVt07su7hbc5wN4DAyWSvMtLFFqMb6IVryUdWHegFhLMU9DVZXUwLIhgynodL0dZ25ZIY2iM28amjE5/SoUfHiWdE2ttbSVrmMCZkfrAS7RM4ovdXQEO22wc0Gv9jNADbGhHIjreBRfVcrlCd7M4WTl5gOExWWAuD9LtDR9xSKR6CPZ2g+41tj2mwqoXUALsDBId2cg9o2OmCfzJX6VPhi6JZfgAG0Ub2cN19oe9wAcaa/4jWWIp2vESTaTvM3cBGpZP9o3mxkR0ZNB5EnszNgYId8EQutBsouDbgqJhGbnMHCFQCdL1hXUPtvVMfDjxVqKiwOoLoyFbmSdF51IgMW3pnz7gHnAD1W8Lzec7Mqe+D+18hnnloyRAsV3hbHL4S8H2n6Zj10CRJKraeG0tpSLsogmhXZ9GjCH8ZTBPCtuR/pxMNqrpsvFf+UQ4RGWySbYwwek2KF940ZTfh0X0S+gK1Y9uJZ/bpJiNpgxOjNtcv8pNlukB7iOMaTRMh33391fdQaJ5PikarMSiEyg02O5/T/ZiV5suQ/vznlRK4andC4DXML8wi1vYrnJVnE7G8F2F9sfJ/cvNcrMIR2vYv9xQqpnaYIW4bRKaHiWMWaVZqWK3Ym57CzivA5P0VEowHl2f/AJjRxS1U8YGPnYcNB3wcvnyl+j9B92OkfsrW8tYcO7UCVtHylYPqsizEsi2+LYVls93
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: minio
