---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: minio
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgBOqHgiBZG0a8a4UGGe5BOoizD6cD8dQ13nZHNB/sMKFvW8SOSEQPu6kBpydNFri0Z8XUpm6rea/F8Q0RM/5wuPY5eyYJ3xwdwHbIkBl1rGYFygr7iH4oEAWmDR+cOG38orx7ReIG7VDvPlrDqIe1VcFJ0PDZXCsCsTEHuc7CUGJON0/+trEqi4vGBMRm56i0VJquRad4cgSbq16h1sSC31DO9YOY8JaUwuYahDHwMq5goJaOJgnYhAsHFMnYJQdaxydeEOjnyvOpJq58bSSeAtq5depRNSPVWcE4V5gviZdZVhqgy1jlyrBg4fAdt2qpDGgurXl9512V2A/mOOmO0r7x3A1ceFwwp7AjLFu5ssB1czIq8RrYbxF46w6S9zK50oRmK9DXYvmwJRZ9cDer9ed+lcl4B8BoU/RSm6vHhlAhJ4FA9OIJLVdnjtkEeVNjimAaIjWVv7WQ/KfyQWW34VwFS9Ugu6AvNZEjNoJqPDxrmzhaON1ahTeAUN+bihxO1H3Q0pGYhJBYqsoXUY9h0POrahHgF29L/6qQhRHTXo1+l+gJCOR9Mbd7gZ4qj3SziRCoCynzWTBtmsYNbwlyKhdMz0TS3Wfm1iiuglJryk/ovh5tCNSFCsNOgVP28+94zxRmmq1GqE5KozLsumIjXY+LkjvVXWvHz18OX9FYR1B5pn6Ki9zsEkLCdtMnJX+YYMfZ2m2Z0RXb9x0S1EslQ=
    MINIO_ROOT_USER: AgActkYe1wdrOfFEx/FwULklVD+MzIhw1lAdlaoyahJSLWnenqVpbL763WbNFRzVhyjoMUja89lmrPXF0xdyXMFTDXO3YFs9Oyw5a4+K/at7fklu7yQS1Pa15uRLzlvGlPLSZTS0bKlcVbEDST5fmsx5TAxd/c/wYpnJQllDEnJ+gZrELM4y81J5jOwOiN7d1+228oZYaOqr3CzGPc+2JIGeVEzyEYGgQI2hHlpQQ+mjCwmQCYENwA+/BuEGRbvXoAJ4tfO9BbXmBjnomkVnvJwmZ30ekXE3nPk2rWZ5X7R7u8er+V4rfZxxOOhZcizsWOwCf22FclbQJ5vbN3/4Jg/v/2ukauhPAUZxGFAfgwf57Cuwo8HbXJ/usuP5npi2WZFIkn/FvqPydzLeN20zL/wnxV7i336zf/3pnUuCXPk1IFOK+TUQIHls14RamXnwVHPiRu+vnhmcGiHIMp25w479DQc4Q7ddJbG5Z1IO3pSAuzKphtXBhAk1oBtTZfAUS8g2yKZLP4UWcCWyMqowVhgN7hyj9mCUddM0jvyD9FtMZzuaYVOn6lv93Z4CpSylECGwHwK+u8GSTj9UsLD21V9w7fRxkhReGMJy907PmLCtXrlsyEyyNTb426TUWaXPutcctWFgZ2RgqD4PeEaXfViGDkxhXRXiv6vnn8FVbGm517AwpKa0V/W1FLrYveghAUzohsEAvmUx
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: minio
