---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: minio
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgCbA4P/qv8wWMU4o/VO0x2dNlrEoZnVFEEl1BJrST1IsK4ZOrMWBaaQYjUIw9t7vav+zZYz9wmjHyIM5GJiTPoyWDRXylFjTHO1g7DCh7CDuB68IbTeHoq5avBe33evR6jhnMI9ck0w53RWDE3KT+bssUXK5HW1Jc0r7x43eUnfIy/tU2TlvFYpW8NBjaezSb3lMjR3f3W5AfLbKUyeGmmqHLCZsDhLLchmZrydmuDpN6AX9F+UoXDmamoiFsW2FOGwcgP8bcX50tnCEGUKm7m+tWBapxMi6B4u1CGsBJ4pBIsPb/DdUpmt+eF2u6hMbcLom83UILEQpN1dC1JnY41URg1G4xYT4UuKFwty8gKKCMxoa91OH3DxwqLTsws7PSKR0AqH8T4oPF9vX1MLWM70p9KPBd9E92pxcbBHaMxUItf2Dqqxgg1QJyeHl4IusMDQk09/MrCGyixMgw7+oXcZyvjjT/iCIOns21LU/h9EkpK67FQ1ljkwsj6jqFHjYOlHMhMMj1iTfuTXP9Ko6xuJ1A3DDtUz3G5uJ8RFsadXrdHz3j60hNcOYgZ+Y0rdIyGLwsgcvZD5YqVsJVu6J4Asm2crELofOfmVUonKn2801CqnxYhYWLpEvMcIRE6+XkEU8K2FcC4rjlHpgTjtVV95wGZ5tXVwjh97SaLZcVZRyeuGLo6PkgdFwruG/f97ydyhRbUcEVV8T8Ys5VFNcNI=
    MINIO_ROOT_USER: AgAQILTA9udGodn9OVAfTSh9zsIHNMr39SWl0pBLQ/qvoC6MWJvUi0gF/M7zv4qX7orwuZq3DQ92SCopBxqokWnPqRUhHfZ4QXvCEOAUzj96Vb9/4T5kRaajUD/ho7EyHdNmNnffhgzp0usyDbBo49l3jScg1I2lupAVJ3BNxQjvWZPLY9UozFa13XLE+fG1/btgQ/4MMf4lN/BQvrJOOnYySLvpgX6LtV1WPPaT5qdhYqkF5RqFh1/IDLW0D8msv9OJsxZRbpMAdz+xP5GMOhhAQNeZVpz/pa46vRv11s+hNp6zgy0Mx02u1K4TFg68tFf+IV2jS3jdz0HDmih92JusUAX0PnN/8C63ycSyumFDPHiwNzXWk7Zlgzt1JWFOH9TrDBXzs3YS9Q19BAejpLZCMQGNy++T0Sr+XiHS12a3+Gml0SR3p8Lvnje8lIeAB9gFaKXPH5id/rd53XMYNKbOqQTXHh2CAebu/Ny48vrrEiQw2vGyK8K9Li2+WoxZQQD7tx5N5wC1YDtIHe3xKfHL1HwS4+azIipO2Y++Ab3/ZkXpe1wLyHC3SlVB8OsvgzZ2nxPrxJXySvAou19c45lxeEP5nK0RPnFiAu+ZbhyQfZ6n8hq0hWL2p454jw2xl3zSfHpMbNns09qTF7RPVErRP6jgImzNk+7XHyb0JE65sbkdvHgbEG4YVNxlxaFp0qFxJedhIS2B
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: minio
