---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: minio
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgBB4hn+bqVzeX2ES7NtRz+QglXa9GhsWqxrK1XVIkouG1UJJ2JIG9HgYa4yGL+tVN+FOh0zL5768/oQnIB6RFQDmhSM/bxQiVDwilcmRyc72XcU0R7j+sTKWaPXekFW+QwU8U6fe0qu49Dp2x3Ll+0DXBt9JoQjj0z3ipsXAXYq5lFvHYFvbskDkguJtg7uKlW1whHYHLPmZfMlpqR2CZhK3kIXRywasZCp8zFqNIRR/4pCf+9ZTxJbZm+A1viNEg7KfJmhDs8+pYzLIRMM96Q+crR2+lpihMFZttPAv0H2sM2WSCpVbATwgslcQqcGms1v31IvfEW0k9vryXX2bu8Wu0ka0K6ki1O0QzBJtjq4uKG7YJ1T6DOYhW3WNhHqTR7OY7bJ6FSA46XcCHpcZqaLn9ByS1BxJIVEAwA9DjeeR9h6bVE0ywjpLNX2SQnaQ9nAO2A4JGbPDuJ3bqQC9T24gGHfVQ++38tQ6hDrr6zSXjjvsFrmX1eayDUbpqLLDChrqx9Xl/QMrHk5HLpgKt+jRnY6h2VHiOxss6QuVvr4/neCgqccNUwrvYZoV2+syDINlf+w3gPcBLBsQRK/EgbTKc7lv1+2PMuAFk0eNvQHK/pf4Allyh4qT1/fM2tD4qN/5jMT3L4tz9L0aMvmOlRjLqJZHsgMU7RjtEjoDJ2NhtibA9raEWOzEHABpIBXKDpPayuaB75UHlMdAGGIHC0=
    MINIO_ROOT_USER: AgCSi6SmXPA+LB/ZhBe5S0DydqF2oRRG+pZ0qa5jqtIiByzGZQaIkuzoo1G9nvnHdQj8Qn2t0W7NmJ29XecqH8tWfYD029SXBkZJrKOOkQ/UZzuqUeRPpmBvy636Zlb8KQOqv8cE+fyROLtC3L0UjpEB+eznfhkcKTRm4/XMFnGAc+uylIwoKIljICSqivIuC0Cq+g4HgHLJAuhIBUrvZbb0hybiaOx9VK8kGUUBAWYdY2IFzA2ycFG5Xrg5/c3fiYYz5F+Ahp93SpgSpIR6SaFeCjWM8HzSVwrRNtsXM88UCwHsi3/QLniu9/bWBz2draCW6JPNhImhrPAecNmFF+6z/Es087Ngr0bvwn70DE7G2aPcHtEcUKn9w+9jvFsft8wT3YNrIeaO+GUusMKMeNwAF/0vhfN0t0iJYVUhOAXFyOH83vPK3yqSuMXgkZLuq/+66ZM2dhvysYWyTbtCWt3ZUeqX73PPOnDx9Dm23fFOmT+bHKerzF56PVzfVU510LevSlSJC0Lvbrm0Ree3iwkeHEFwY1zSO4UmEq9OM23S+gWQjZf0951imVNyB6lkH2ed+CgP9OzdXNeb+mccm/LIvuTKT9MnDnXUStTQdpo7KaYMeBaVOuQprQsIWG1AiaBb2NVQHrR4PmtKjOrNuMSlDMWEUWJQxfmfQS3A4jBO6NxNfGAo8qBDipqhKm+qXgwDMUIJZQGq
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: minio
