apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: hlab-auth
  namespace: hlab-auth
spec:
  instances: 1
  storage:
    size: 8Gi
  bootstrap:
    initdb:
      database: hlab_auth
      owner: hlab_auth
      secret:
        name: hlab-auth-pg-app
  monitoring:
    enablePodMonitor: false
