---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hlab-auth-pg-app
  namespace: hlab-auth
spec:
  encryptedData:
    password: AgDCaYUXZrkubzKoxsaUvdZaKvKFZbk3ZltKU86NJ97JnCJn89cLjdrKfjtyK+RU3hAjnsG7DR8sx4pMNDIp4L8G1ig0z3UKLJLPtSeoNax51RmzWjYXD32o/N83xy7RSO8omVwCuAmx+DYOxRgVuk9sHVDnpxPbREiy87R6dtHF+ZKNlbRYDUNbE5kkxWAKfYIjUt0lqZCgZSDcrUW64YxaBMSl0jXdIklLzjlwUL4Q3famW8uwDodW/MaDbEG/ze2WHgk1ZJdAewmuhqnqsDhWns59zMpWlSGG5tb/yR7rrq/uWA976H24Lr+UWBPAofpBT42mMCEK6mSAz07OA79uJX7yU7Eh+/xP2dDxSNAgvqS8tsOD3tSV8dxFphtuNRxXDs2VhKsAe8q0OV49xAWlxDAnBXu0y/3nOoIIzB4fuzIhDP9yrz/tBW4ZS0uC1Qzs/xVYayGHDw5ybPqV0sUJ15eK1HgAhlX0g0v0F+ucmmICAVFX3aFbklpJ2D+/ctEQWsCFJ/+6gHJ8kiYh7E7eMfGC08wgJ+AczuD8tWMCI3SyrPzFnVwzUoVUhXFe7pKvyVTEqHeAmGYSm5Q03n06205cCHioWHPcunNVe6ZDvINMi5Wn4ASa+LVhCmNQIDbfpWcwtsPCd65Xz8mvRrAV4lahNNCyfk8siOdXE7HBtASiQN9kQdUQdVMhkfcDOtct4eTiEnlNhtGfnWLk63AHUohIosaqnVM=
    username: AgAupUEAIl+v14fFzqZmEFzxMrt0Sg9OGrkPY70IcnGJNKnIEWRHsLvbd/KytO8TIGPa2FZoWnV8qLqJmWEMpt4pSaHt8grEiCuyTK6wD7Tq6gNT4hQU3kS07VqmBjBnNjRNXc5poJv3s2h0UvzEGcokjzRxcmUtFk75GehBOMFAvnlgvoInrO9RiMYIxH/w4VvuKYdgg1c9K+uI47Jxi/CiV4ZRl4bDUuxZEly5vSvwMqlgc5afgP6UzMQADqg9bHzWO91rBpRqTvfghwo5RN4IZ8IgnQZ1bt4pkkmcGELUGyJTs8wH7TR11IK8b0rA0s/hTF13x4NycBZnwD6XaLRPgE96dqBXDDI4/0nOO04ZFXFJbmnNHgzRXR9FzTg7weq006mdrvVbVsWj8MYL7Sh4cRpGFgJ7YBQj72GT9fl1PQDiA22IMdArk34/ddSEl9RxLp9AkI80HCnbs2RoFF+1Unuh/KGtz14l+Vz3FtYQtFU6U1ouEd4qA4gxTS8yQ0vgeNMNZFxI0PCzk+L3sZYvpD7BozjX6yzhB8jUM8Ap+xFQCH+6j0xInovvTsKF+NUfli0Pf82vbpAtzrAgYD1UKN9fqKYRIYrJoVxXq+PKu0jDZ3zForqVtFN3GPvJl3DQ0dKqvFl4JV75GBrwniePKWV4Z5E56sAF24YapiA64+2eXR/pIv/ha2gKulc5uYsNrgWLWtuRixk=
  template:
    metadata:
      name: hlab-auth-pg-app
      namespace: hlab-auth
