apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hlab-auth
  namespace: hlab-auth
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
spec:
  ingressClassName: traefik
  rules:
    - host: auth.wayl.one
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hlab-auth
                port:
                  number: 8000
    - host: auth.waylonwalker.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hlab-auth
                port:
                  number: 8000
  tls:
      - hosts:
          - auth.wayl.one
        secretName: auth-wayl-one-tls
      - hosts:
          - auth.waylonwalker.com
        secretName: auth-waylonwalker-com-tls
