apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - hlab-auth-pg-app-sealed-secret.yaml
  - hlab-auth-sealed-secret.yaml
  - cnpg-cluster.yaml
  - redis.yaml
  - app.yaml
  - ingress.yaml
  - traefik-middleware.yaml
