---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: observability-grafana-admin
  namespace: observability
spec:
  encryptedData:
    admin-password: AgCZhBIZMEmgpnCb7OkfO5IoGlKu8WKA+CwVf4a7U3LaDAMi/Zov1565OCe8Lf1D/UeBfnwNAZlAsbzr+Zj00I4SSwVxKChvpxGDsdYFH36IA40741b/R8HDQ1VCzAdiDGA7ddEhiSwNsE/rTY7o3pjsplTaoZTqXYQ4zPaW7wWOhhHCGTqvLhojxHFbpSKCeMAbAZpzr0r2UBv8oyEDCXFRuzWkDD7fp964fvB9R+mSvC6duu1HDG6XFIXbXaUQpl8kx7Jw4mySpEO9CZmxNeokdD4Wdgejl5BzCuvdlGGgMalI2iKs5TYPvlxHIuIYUnF/VYC7fK2YuQQVFk/I9Mx8+F06fZIZipJ0h6ARW/Y0Hy1UCeX/f7adAdMqn7fNNel34XAsq2+ScW8kmK+eMsvJ2iQqpv60hJHjQUvgGKg5g1FrKTNHySpbO/hB6qmd61QRdDKb/mI4Rshrzw9Km1rc0lT+Um8OJvZvrX3S3uvqClXZR9z9p2Q1GLF1hVF7R/u/sJr4HNAJgjrFp1RfvwD5xKfu2Ecet4G1dV6R/wiTp/EJYq3o3YMzpSUSVNS8OhCJ2odW4knINDj0/8GTLw5I8W7McUL18PY396hMqylXWo0ksU0p2LUpRvaFTtT9UofPOAiqOIzcd139ncTsc+tmE3GIe5Wyvn6f8fkypsleHU3AFyog0OnfUbrKLAYBZ8rcCaAT1xlbeQqs0bKwQm6hTw8jJOoIh4KbT0XsqhG5mXckdutl7uOC
    admin-user: AgCOBBDNUbpMOs1uZ78+LlrXrW9eyqzjOGP9ePzsHm2RQflPPpXTJzvcmZU57a1CrEyyaX0I0UAHpAbeYdbuonKC8XOR2aFVDrzxCPo9EFOR0wV2m0FwudPFBV8+1rEeW9CmVT0exvIAYwcyFzoHOVU44FsPo2U3z45w4VuzKxcRxS0xd8YflgBzHrvF8RMpxvrOF58uKTvPSxGgDhiAylCqQjrZUg20ZVielqMWbeoAlaq2lDnFddPf00cDH60Swx/+SoFBFgbrGhWiTfDs7oq8VZb0Wo8hRBUA/fD3KuJVCydivjvLFU6SkHm8kE+s+idRpDpwwWYBKiaCEGtIR7ExHR71eY3np+qjy2pFcjvW13EdyQKqn5679eCUm/HmHiXvHo3QRTnU7JWQ5WLh2zlEYHT3g411x4lrRL/vyWNG55BLnxqAuFfvmz0yaAzjPG/wqeRL62B4y+4xRwBsRPyIa0miRQLbQWYWG4pXsAy3/ZaFDuJtWJotxGW3RMKlAix55s9qMonSL+2qvt4u7GjHzkue3Pisy7uiLTnXntjCRTvGTJHPaCvOFjEI/+0bj4oarnhZNgKKO54cGSuLWl5+ljVc29jOU0+Ts8FujfU4ptwX0HrWGyYP0LKyeFQ5qSIcN5t4as8Xe8UJ31a/cVUWtX/cy1YzKCvea5VhbA5vAtul2zIqLOFPVsAxuhfk/RG1RIBOow==
  template:
    metadata:
      name: observability-grafana-admin
      namespace: observability
