apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    providers:
      kubernetesIngress:
        publishedService:
          enabled: false
        ingressEndpoint:
          hostname: 1bdd7ce3-6476-43bc-a9e0-6e30167617e5.cfargotunnel.com
