apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  hostPath:
    path: /mnt/vault/nfs/general/pv/immich/immich-library
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-typesense-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  hostPath:
    path: /mnt/vault/nfs/general/pv/immich/immich-typesense
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-redis-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  hostPath:
    path: /mnt/vault/nfs/general/pv/immich/immich-redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgres-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  hostPath:
    path: /mnt/vault/nfs/general/pv/immich/immich-postgres
