# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: immich-library-pvc
#   namespace: immich
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 100Gi
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: immich-library-pv
#   namespace: immich
# spec:
#   capacity:
#     storage: 100Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   hostPath:
#     path: /mnt/vault/nfs/general/pv/immich/immich-library
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: immich-typesense-pvc
#   namespace: immich
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: immich-typesense-pv
#   namespace: immich
# spec:
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   hostPath:
#     path: /mnt/vault/nfs/general/pv/immich/immich-typesense
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: immich-redis-pvc
#   namespace: immich
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: immich-postgres-pvc
#   namespace: immich
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 20Gi
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: immich-postgres-pv
#   namespace: immich
# spec:
#   capacity:
#     storage: 20Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   hostPath:
#     path: /mnt/vault/nfs/general/pv/immich/immich-postgres
