---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-secret
  namespace: immich
spec:
  encryptedData:
    db-password: AgBB8fHvvd28phaJ96h4qMeigckWsLIv+1zEyTYl2PF/WZQaYyKE+Dg/rHjk3WCirMnpIcB7tRKUdRLvn4Z3Gm6KURoJ2971baoZxY1AJGj94fe3eUIC+OdrVmkk/uS1ZDUXUv6VrCULjxCpi9FXFYUg1FX+y02SeGLFgrsO6dK2d9/vK9bmITNk75l4LiQ2lXp0/iii5kjGpFrngwopgxY8NRR/SA/udjyWPHa3jAbgthhxyi3b+8B6vqxDx2k11EN7VJsvOFO1kpp80uWnlYATdP7yAeD9mnDEWXhXGb4cRKSfaq4jd6UjqQ6g83kX5hezim+IRvDTZGm9kqbBHh6Yz5exGoXSdSw55tlOMPVNO0KD2se1BK/tIIH3nqznmZ9Cf+LdXhczptlzEJ6K7Gbm+KuId3uy88g2PydUA8m7t8EvcisSuvtsGejYyfuq2QoZR+fJsGEq3C/4WKU8LAlqkXCyo8gwCCDbXbodbHs/rlMuBqbVriDXtNnbjLX4zwHTdM9X8wbyQrJ5oKTk9zUiCZYEmxel+07gJkdicKbiCDq4KJOm45UV52/fKnnh1Ev7W9ysIl67MwsE5Z+WK6p/2zXZ34JL5QddErXeSB7Uh9TeXB5Yls6n4GIycWVMt1KNof44Od1F01TBv8DsOCjSjIImUssZoXMGTejUrXh+qbC9d0ajtccWPubRZ6FDYheoGQuQS/xo4X8uhMaWAQ==
  template:
    metadata:
      creationTimestamp: null
      name: immich-secret
      namespace: immich
