apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1-core-apps
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: argo-apps/core-apps
    repoURL: 'https://github.com/waylonwalker/homelab-argo'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: prometheus-community
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://prometheus-community.github.io/helm-charts
#     targetRevision: 66.2.1
#     chart: kube-prometheus-stack
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: monitoring
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: prometheus
#   namespace: argocd
# spec:
#   project: default
#   destination:
#     namespace: prometheus
#     server: 'https://kubernetes.default.svc'
#   source:
#     path: prometheus
#     repoURL: 'https://github.com/waylonwalker/homelab-argo'
#     targetRevision: HEAD
#   syncPolicy:
#     automated:
#       prune: true
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: argo-workflows
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: 'https://github.com/waylonwalker/homelab-argo'
#     targetRevision: HEAD
#     path: argo-workflows
#     helm:
#       valueFiles:
#         - values.yaml
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: argo-workflows
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: argo-token
#   namespace: argocd
# spec:
#   project: default
#   destination:
#     namespace: argo-token
#     server: 'https://kubernetes.default.svc'
#   source:
#     path: argo-token
#     repoURL: 'https://github.com/waylonwalker/homelab-argo'
#     targetRevision: HEAD
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: workflow-templates
#   namespace: argocd
# spec:
#   project: default
#   destination:
#     namespace: argo
#     server: 'https://kubernetes.default.svc'
#   source:
#     path: workflow-templates
#     repoURL: 'https://github.com/waylonwalker/homelab-argo'
#     targetRevision: HEAD
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
