---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: registry
spec:
  encryptedData:
    .dockerconfigjson: AgCOHQwcEGZpQYx9RN2JQjgW+UzQdqzwHpJ7lZa9OX0aceaZv4NBvSRFcRORKTtVhJRXQqcoKtWzR6j7sXYYc+Hj2PIG88QaLAiCvr1U3Up2tkpd1Drnga/CEtSEODyWn9AmDOHRPLhjkHhJzAYx3QyXCPj+euiunZpcXvesg+1vTp5PJnyFv8boHQy/mWBxgDqiatfT1LzMVSVCgUcwYuecGgmi4Gwzu7re3gUKdO+WW/XKhFTdinB8VcWhlvu1FM42eCCHTcpf67z6DfoU3HfQetVdvaXr4PKrYiW+NykNafNp2ZhMsuO0IyNXsSkei+VH9JCeIo6miqzdf8LF6W16ncAnQALy96XU7J6x6/szolWZ1h2FiYkEVR8dchGwoXrEV8izGYNIYBafJ2v4Nb5Ke+xMrVXfVaAyOpfuc03eLW3K9xJo7OQTyq2gZOXbcaxIdbkOqx5umPPMQ98lcvXAD0WeP1LfydoSRFfmGz72gBj2V/CELnXJqJNjnue3h/VEoMfPS7V6uSpshJ8J1AEMhfQTUYix4Z9idA8SpwhnC8NxTCIZhDguYVVr9m/R2OuKOg3+B67VHEGCV1yVDMKa0lxI5fxCPaysH6VzQTaSRpKPRHWOOyFiGrZCRyHbHkRnVJqNVTFiM0TVXg9e9VktpMdph+E7hdjoSGWR9uhFfgNuN4+BHexuJWhNpmCRVe+iRBIGeeXJlq0j/QQ8xTHgYVQeVB0H1Gdw160dJoh9Nh9EJDpgdheoqRKU96cfYluQwfwXQKCte3RqUcTxe4Eea558J2G2VXazoqEgTBreoL7cugKapHkZLKT2ZWcY04te4Gm/uMuw7g==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: registry
    type: kubernetes.io/dockerconfigjson
